db:
  host: "134.175.67.79"
  port: 3306
  user: "app"
  password: ""
  database: "douyin_mall"
  params: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "106.52.154.235:6379"
  password: ""
  db: 0

etcd:
  endpoints:
    - "42.193.160.221:2379"

grpc:
  server:
    name: payment.service
    port: 8092
    etcdTTL: 60

http:
  server:
    port: 8093

payment:
  mode: "real"
  provider: "alipay"

wechat:
  api_base_url: "http://localhost:8888"
  app_id: "wx_mock_app_id"
  mch_id: "1234567890"
  cert_serial_no: "MOCK_CERT_SERIAL_NO"
  private_key_path: "./mock_key.pem"
  api_v3_key: ""
  notify_url: "http://localhost:8093/payment/wechat/callback"

alipay:
  app_id: "9021000163631795"
  pid: "2088721101056182"
  gateway: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"
  private_key: ""
  public_key: ""
  sandbox: true
  notify_url: "http://localhost:8093/api/pay/alipay/notify"
  return_url: "http://localhost:8093/pay/success"

kafka:
  brokers:
    - "10.1.4.4:29092"

rocketmq:
  endpoint: "43.136.121.171:8081"
  access_key: ""
  secret_key: ""
  producer_max_attempts: 3

canal:
  mysql:
    host: "localhost"
    port: 13316
    user: "root"
    password: ""
  server_id: 1234
