syntax = "proto3";

package cart;

option go_package = "cart/v1;cartv1";

service CartService {
    rpc AddItem(AddItemReq) returns (AddItemResp) {}
    rpc DeleteItem(DeleteItemReq) returns (DeleteItemResp) {}
    rpc GetCart(GetCartReq) returns (GetCartResp) {}
    rpc EmptyCart(EmptyCartReq) returns (EmptyCartResp) {}
    rpc ChangeQty(ChangeQtyReq) returns (ChangeQtyResp) {}
    rpc IncrementQty(IncrementQtyReq) returns (IncrementQtyResp) {}
    rpc DecrementQty(DecrementQtyReq) returns (DecrementQtyResp) {}
}

message CartItem {
    int64 product_id = 1;
    int64 quantity = 2;
    int64 sku_id = 3;
}

message AddItemReq {
    int64 user_id = 1;
    repeated CartItem items = 2;
}

message AddItemResp {}

message DeleteItemReq {
    int64 user_id = 1;
    repeated int64 sku_ids = 2;
}

message DeleteItemResp {}

message GetCartReq {
    int64 user_id = 1;
}

message Cart {
    int64 user_id = 1;
    repeated CartItem items = 2;
}

message GetCartResp {
    Cart cart = 1;
}

message EmptyCartReq {
    int64 user_id = 1;
}

message EmptyCartResp {}

message ChangeQtyReq {
    int64 user_id = 1;
    CartItem item = 2;
}

message ChangeQtyResp {}

message IncrementQtyReq {
    int64 user_id = 1;
    int64 sku_id = 2;
}

message IncrementQtyResp {
    int64 new_quantity = 1;
}

message DecrementQtyReq {
    int64 user_id = 1;
    int64 sku_id = 2;
}

message DecrementQtyResp {
    int64 new_quantity = 1;
}
