syntax = "proto3";

package order;

option go_package="order/v1;orderv1";

service OrderService {
    rpc CreateOrder(CreateOrderReq) returns (CreateOrderResp) {}
    rpc ChangeOrderStatus(ChangeOrderStatusReq) returns (ChangeOrderStatusResp) {}
    rpc GetOrder(GetOrderReq) returns (GetOrderResp) {}
    rpc ListOrder(ListOrderReq) returns (ListOrderResp) {}
}

enum OrderStatus {
    ORDER_STATUS_UNKNOWN   = 0;
    ORDER_STATUS_CREATED   = 1;
    ORDER_STATUS_PAID      = 2;
    ORDER_STATUS_SHIPPED   = 3;
    ORDER_STATUS_COMPLETED = 4;
    ORDER_STATUS_CANCELED  = 5;
    ORDER_STATUS_REFUNDED  = 6;
}

enum ChangeOrderAction {
    CHANGE_ORDER_ACTION_UNKNOWN  = 0;
    CHANGE_ORDER_ACTION_PAY      = 1;
    CHANGE_ORDER_ACTION_SHIP     = 2;
    CHANGE_ORDER_ACTION_COMPLETE = 3;
    CHANGE_ORDER_ACTION_CANCEL   = 4;
    CHANGE_ORDER_ACTION_REFUND   = 5;
}

message ChangeOrderStatusReq {
    int64 order_id = 1;
    ChangeOrderAction action = 2;
}

message ChangeOrderStatusResp {
    bool changed = 1;
}

message Address {
    string street_address = 1;
    string city = 2;
    string state = 3;
    string country = 4;
    string zip_code = 5;
    string phone = 6;
}

message OrderItem {
    int64 product_id = 1;
    int64 quantity = 2;
    int64 snapshot_price = 3;
    string snapshot_currency = 4;
    int64 converted_price = 5;
    int64 sku_id = 6;
}

message CreateOrderReq {
    int64 user_id = 1;
    string currency = 2;
    Address address = 3;
    repeated OrderItem items = 5;
    int64 order_id = 6;
    string order_kind = 7;
    int64 activity_id = 8;
    string remark = 9;
    int64 payable_amount = 10;
}

message CreateOrderResp {
    int64 order_id = 1;
}

message GetOrderReq {
    int64 order_id = 1;
}

message GetOrderResp {
    Order order = 1;
}

message ListOrderReq {
    int64 user_id = 1;
    int64 cursor = 2;
    int32 limit = 3;
}

message Order {
    int64 order_id = 1;
    int64 user_id = 2;
    OrderStatus order_status = 3;
    repeated OrderItem items = 4;
    int64 total_amount = 5;
    string currency = 6;
    Address address = 7;
    int64 created_at = 9;
    int64 expire_at = 10;
    string order_kind = 11;
    int64 activity_id = 12;
    string remark = 13;
}

message ListOrderResp {
    repeated Order orders = 1;
    int64 next_cursor = 2;
}
