syntax = "proto3";

package order;

option go_package="order/v1;orderv1";

service OrderService {
    rpc CreateOrder(CreateOrderReq) returns (CreateOrderResp) {}
    rpc ChangeOrderStatus(ChangeOrderStatusReq) returns (ChangeOrderStatusResp) {}
    rpc ListOrder(ListOrderReq) returns (ListOrderResp) {}
}

// 更改订单状态
message ChangeOrderStatusReq {
    int64 order_id = 1;
    uint32 order_status = 2;
}

message ChangeOrderStatusResp {}

message Address {
    string street_address = 1;
    string city = 2;
    string state = 3;
    string country = 4;
    string zip_code = 5;
}

// 订单项：只存储商品ID、数量、价格快照（目的是审计，不冗余存储商品详情，展示时从Product服务查询）
message OrderItem {
    int64 product_id = 1;
    int64 quantity = 2;
    int64 snapshot_price = 3; // 商品原始单价快照
    string snapshot_currency = 4;
    int64 converted_price = 5; // 转换为支付货币类型的价格
}

message CreateOrderReq {
    int64 user_id = 1;
    string currency = 2; // 用户选择的支付货币
    Address address = 3;
    string phone = 4;
    repeated OrderItem items = 5;
    //  int64 total = 6; 本来还想直接算出total传过来，后面发现不对，正确订单服务的业务理解：
    //  接收一组已定价的商品项，
    //  根据订单业务规则，（可以扣税，优惠，减小数点）
    //  生成唯一、不可变的订单金额事实，返回
}

message CreateOrderResp {
    int64 order_id = 1;
}

message ListOrderReq {
    int64 user_id = 1;
    int64 cursor = 2;
    int32 limit = 3;
}

message Order {
    int64 order_id = 1;
    int64 user_id = 2;
    uint32 order_status = 3; // 订单状态：0-未知 1-待支付 2-待发货 3-待收货 4-已完成 5-已取消 6-已退款
    repeated OrderItem items = 4;
    int64 total_amount = 5;
    string currency = 6; // 订单支付货币
    Address address = 7;
    string phone = 8;
    int64 created_at = 9;
}

message ListOrderResp {
    repeated Order orders = 1;
}