syntax = "proto3";

package payment.v1;

option go_package = "payment/v1;paymentv1";

service PaymentService {
  rpc NativePrepay(NativePrePayRequest) returns (NativePrePayResponse);
  rpc GetPayment(GetPaymentRequest) returns (GetPaymentResponse);
  rpc ConfirmPayment(ConfirmPaymentRequest) returns (ConfirmPaymentResponse);
}

message NativePrePayRequest {
  Amount amt = 1;
  string biz_trade_no = 2;
  string description = 3;
}

message NativePrePayResponse {
  string code_url = 1;
}

message Amount {
  int64 total = 1;
  string currency = 2;
}

message GetPaymentRequest {
  string biz_trade_no = 1;
}

message GetPaymentResponse {
  PaymentStatus status = 1;
}

message ConfirmPaymentRequest {
  string biz_trade_no = 1;
}

message ConfirmPaymentResponse {
  PaymentStatus status = 1;
  string txn_id = 2;
}

enum PaymentStatus {
  PaymentStatusUnknown = 0;
  PaymentStatusInit = 1;
  PaymentStatusSuccess = 2;
  PaymentStatusFailed = 3;
  PaymentStatusRefund = 4;
}
