syntax = "proto3";

package payment.v1;

option go_package="payment/v1;paymentv1";

service PaymentService {
    // 预支付，也就是创建一个支付单
    rpc NativePrepay(NativePrePayRequest) returns (NativePrePayResponse);
		rpc GetPayment(GetPaymentRequest) returns (GetPaymentResponse);
}

message NativePrePayRequest {
	// 带一个 type，标记是扫码支付，还是 js 跳转支付，还是唤醒本地 APP
	// type = "native"
	Amount amt = 1;
	string biz_trade_no = 2;
	string description = 3;
}

// 支付方式不同，所以响应的含义也会有不同，这里就是一个能打开支付二维码的 url
message NativePrePayResponse {
	string code_url = 1;
}

message Amount {
	int64 total = 1;
	string currency = 2;
}

// 业务方的唯一 no，通用
message GetPaymentRequest {
	string biz_trade_no = 1;
}

message GetPaymentResponse {
	// 有需要再加字段
	PaymentStatus status = 1;
}

enum PaymentStatus {
	PaymentStatusUnknown = 0;
	PaymentStatusInit = 1;
	PaymentStatusSuccess = 2;
	PaymentStatusFailed = 3;
	PaymentStatusRefund = 4;
}