// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/checkout/ioc"
	transportgrpc "github.com/XDWow/DouyinMall/backend/internal/checkout/transport/grpc"
	"github.com/XDWow/DouyinMall/backend/internal/checkout/usecase"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	idGenerator := ioc.InitIDGenerator()
	productClient := ioc.InitProductClient()
	inventoryClient := ioc.InitInventoryClient()
	couponClient := ioc.InitCouponClient()
	orderClient := ioc.InitOrderClient()
	paymentClient := ioc.InitPaymentClient()
	previewOrderUseCase := usecase.NewPreviewOrderUseCase(productClient, couponClient)
	placeOrderUseCase := usecase.NewPlaceOrderUseCase(
		productClient,
		inventoryClient,
		couponClient,
		orderClient,
		paymentClient,
		idGenerator,
		loggerV1,
	)
	checkoutHandler := transportgrpc.NewCheckoutHandler(previewOrderUseCase, placeOrderUseCase)
	grpcServer := ioc.InitGRPCServer(checkoutHandler)
	app := newApp(grpcServer)
	return app
}

// wire.go:

type App struct {
	GRPCServer server.Server
}

func newApp(grpcServer server.Server) *App {
	return &App{GRPCServer: grpcServer}
}
