// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/checkout/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/checkout/transport/grpc"
	"github.com/XDWow/DouyinMall/backend/internal/checkout/usecase"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitProductClient()
	couponserviceClient := ioc.InitCouponClient()
	previewOrderUseCase := usecase.NewPreviewOrderUseCase(client, couponserviceClient)
	inventoryserviceClient := ioc.InitInventoryClient()
	orderserviceClient := ioc.InitOrderClient()
	paymentserviceClient := ioc.InitPaymentClient()
	idGenerator := ioc.InitIDGenerator()
	loggerV1 := ioc.InitLogger()
	placeOrderUseCase := usecase.NewPlaceOrderUseCase(client, inventoryserviceClient, couponserviceClient, orderserviceClient, paymentserviceClient, idGenerator, loggerV1)
	payOrderUseCase := usecase.NewPayOrderUseCase(orderserviceClient, paymentserviceClient)
	checkoutHandler := grpc.NewCheckoutHandler(previewOrderUseCase, placeOrderUseCase, payOrderUseCase)
	server := ioc.InitGRPCServer(checkoutHandler)
	app := newApp(server)
	return app
}

// wire.go:

type App struct {
	GRPCServer server.Server
}

func newApp(grpcServer server.Server) *App {
	return &App{GRPCServer: grpcServer}
}
