// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/agent/handler"
	"github.com/XDWow/DouyinMall/backend/internal/agent/infra/cache"
	"github.com/XDWow/DouyinMall/backend/internal/agent/infra/mq"
	"github.com/XDWow/DouyinMall/backend/internal/agent/infra/repository"
	"github.com/XDWow/DouyinMall/backend/internal/agent/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/agent/knowledge"
	"github.com/XDWow/DouyinMall/backend/internal/agent/usecase"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	pipelineMetrics := usecase.NewPipelineMetrics()
	cmdable := ioc.InitRedis()
	fallbackLLMClient := ioc.InitFallbackLLMClient(loggerV1, pipelineMetrics, cmdable)
	embedder := ioc.InitEmbedder()
	reranker := ioc.InitReranker()
	gormDB := ioc.InitDB()
	agentRedis := cache.NewAgentRedis(cmdable)
	sdkClient := ioc.InitMilvusClient()
	knowledgeRepo := repository.NewMilvusKnowledgeRepo(sdkClient, agentRedis, gormDB, loggerV1)
	semanticCache := repository.NewSemanticCache(agentRedis, sdkClient, loggerV1)
	client := ioc.InitMCPClient()
	aiService := usecase.NewAIService(fallbackLLMClient, embedder, reranker, knowledgeRepo, semanticCache, client, pipelineMetrics, loggerV1)
	saramaClient := ioc.InitKafkaClient()
	syncProducer := ioc.InitKafkaSyncProducer(saramaClient)
	messageProducer := mq.NewMessageProducer(syncProducer)
	sessionRepo := repository.NewSessionRepo(agentRedis, messageProducer, gormDB, loggerV1)
	systemLimiter := ioc.InitSystemRateLimiter(cmdable)
	userLimiter := ioc.InitUserRateLimiter(cmdable)
	chatUseCase := usecase.NewChatUseCase(aiService, sessionRepo, systemLimiter, userLimiter, pipelineMetrics, loggerV1)
	sessionUseCase := usecase.NewSessionUseCase(sessionRepo)
	agentHandler := handler.NewAgentHandler(chatUseCase, sessionUseCase)
	server2 := ioc.InitGRPCServer(agentHandler)
	indexer := knowledge.NewIndexer(embedder, sdkClient, gormDB, agentRedis, loggerV1)
	messageConsumer := mq.NewMessageConsumer(saramaClient, gormDB, loggerV1)
	app := newApp(server2, messageConsumer, indexer)
	return app
}

// wire.go:

func newApp(svr server.Server, consumer *mq.MessageConsumer, indexer *knowledge.Indexer) *App {
	return &App{Server: svr, Consumer: consumer, Indexer: indexer}
}
