# ============================================
# MySQL 实例配置（DouyinMall 实例）
# ============================================

# MySQL 连接地址（docker-compose 中的服务名）
canal.instance.master.address=mysql:3306

# MySQL 用户名和密码
canal.instance.dbUsername=root
canal.instance.dbPassword=root
canal.instance.connectionCharset=UTF-8

# 监听哪些表（.*\\..* 表示所有数据库的所有表）
canal.instance.filter.regex=.*\\..*

# Kafka Topic 名称
canal.mq.topic=DouyinMall_binlog

