// Code generated by Kitex v0.16.1. DO NOT EDIT.

package searchv1

import (
	"context"
	"strconv"

	"github.com/cloudwego/prutal"
)

// 排序类型
type SortType int32

const (
	SortType_RELEVANCE   SortType = 0 // 相关性（默认）
	SortType_PRICE_ASC   SortType = 1 // 价格从低到高
	SortType_PRICE_DESC  SortType = 2 // 价格从高到低
	SortType_SALES_DESC  SortType = 3 // 销量从高到低（预留）
	SortType_NEW_ARRIVAL SortType = 4 // 新品优先（预留）
)

// Enum value maps for SortType.
var SortType_name = map[int32]string{
	0: "RELEVANCE",
	1: "PRICE_ASC",
	2: "PRICE_DESC",
	3: "SALES_DESC",
	4: "NEW_ARRIVAL",
}

var SortType_value = map[string]int32{
	"RELEVANCE":   0,
	"PRICE_ASC":   1,
	"PRICE_DESC":  2,
	"SALES_DESC":  3,
	"NEW_ARRIVAL": 4,
}

func (x SortType) String() string {
	s, ok := SortType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 建议类型
type SuggestType int32

const (
	SuggestType_PRODUCT  SuggestType = 0 // 商品建议
	SuggestType_MERCHANT SuggestType = 1 // 商家建议
)

// Enum value maps for SuggestType.
var SuggestType_name = map[int32]string{
	0: "PRODUCT",
	1: "MERCHANT",
}

var SuggestType_value = map[string]int32{
	"PRODUCT":  0,
	"MERCHANT": 1,
}

func (x SuggestType) String() string {
	s, ok := SuggestType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 建议来源
type SuggestSource int32

const (
	SuggestSource_HISTORY    SuggestSource = 0 // 历史搜索
	SuggestSource_HOT        SuggestSource = 1 // 热门搜索
	SuggestSource_NAME_MATCH SuggestSource = 2 // 名称匹配（商品名或商家名）
)

// Enum value maps for SuggestSource.
var SuggestSource_name = map[int32]string{
	0: "HISTORY",
	1: "HOT",
	2: "NAME_MATCH",
}

var SuggestSource_value = map[string]int32{
	"HISTORY":    0,
	"HOT":        1,
	"NAME_MATCH": 2,
}

func (x SuggestSource) String() string {
	s, ok := SuggestSource_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 商家排序类型
type MerchantSortType int32

const (
	MerchantSortType_MERCHANT_RELEVANCE   MerchantSortType = 0 // 相关性（默认）
	MerchantSortType_MERCHANT_SALES_DESC  MerchantSortType = 1 // 销量从高到低
	MerchantSortType_MERCHANT_RATING_DESC MerchantSortType = 2 // 评分从高到低
	MerchantSortType_MERCHANT_NEW_ARRIVAL MerchantSortType = 3 // 新入驻优先
)

// Enum value maps for MerchantSortType.
var MerchantSortType_name = map[int32]string{
	0: "MERCHANT_RELEVANCE",
	1: "MERCHANT_SALES_DESC",
	2: "MERCHANT_RATING_DESC",
	3: "MERCHANT_NEW_ARRIVAL",
}

var MerchantSortType_value = map[string]int32{
	"MERCHANT_RELEVANCE":   0,
	"MERCHANT_SALES_DESC":  1,
	"MERCHANT_RATING_DESC": 2,
	"MERCHANT_NEW_ARRIVAL": 3,
}

func (x MerchantSortType) String() string {
	s, ok := MerchantSortType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type SearchProductsReq struct {
	Keyword  string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
	Page     int64  `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=page_size" json:"page_size,omitempty"`

	// 筛选条件
	Categories []string `protobuf:"bytes,4,rep,name=categories" json:"categories,omitempty"`    // 分类筛选（多选）
	MinPrice   int64    `protobuf:"varint,5,opt,name=min_price" json:"min_price,omitempty"`     // 最低价格（分）
	MaxPrice   int64    `protobuf:"varint,6,opt,name=max_price" json:"max_price,omitempty"`     // 最高价格（分）
	MerchantId int64    `protobuf:"varint,7,opt,name=merchant_id" json:"merchant_id,omitempty"` // 商家 ID
	SortBy     SortType `protobuf:"varint,8,opt,name=sort_by" json:"sort_by,omitempty"`         // 排序方式

	// 高级选项
	EnableHighlight bool `protobuf:"varint,9,opt,name=enable_highlight" json:"enable_highlight,omitempty"` // 是否启用高亮
}

func (x *SearchProductsReq) Reset() { *x = SearchProductsReq{} }

func (x *SearchProductsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchProductsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchProductsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchProductsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProductsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchProductsReq) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *SearchProductsReq) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchProductsReq) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchProductsReq) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *SearchProductsReq) GetSortBy() SortType {
	if x != nil {
		return x.SortBy
	}
	return SortType_RELEVANCE
}

func (x *SearchProductsReq) GetEnableHighlight() bool {
	if x != nil {
		return x.EnableHighlight
	}
	return false
}

type SearchProductsResp struct {
	Products []*ProductSearchResult `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
	Total    int64                  `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Page     int64                  `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize int64                  `protobuf:"varint,4,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *SearchProductsResp) Reset() { *x = SearchProductsResp{} }

func (x *SearchProductsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchProductsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchProductsResp) GetProducts() []*ProductSearchResult {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *SearchProductsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchProductsResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProductsResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ProductSearchResult struct {
	Id           int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Picture      string   `protobuf:"bytes,4,opt,name=picture" json:"picture,omitempty"`
	SliderImgs   []string `protobuf:"bytes,5,rep,name=slider_imgs" json:"slider_imgs,omitempty"`
	Price        int64    `protobuf:"varint,6,opt,name=price" json:"price,omitempty"`          // 价格（分）
	Categories   []string `protobuf:"bytes,7,rep,name=categories" json:"categories,omitempty"` // 分类列表
	InStock      bool     `protobuf:"varint,8,opt,name=in_stock" json:"in_stock,omitempty"`    // 是否有货（搜索结果不显示具体库存数量）
	MerchantId   int64    `protobuf:"varint,9,opt,name=merchant_id" json:"merchant_id,omitempty"`
	MerchantName string   `protobuf:"bytes,10,opt,name=merchant_name" json:"merchant_name,omitempty"`

	// 搜索相关字段
	Score                float32 `protobuf:"fixed32,11,opt,name=score" json:"score,omitempty"`                               // 相关性评分
	NameHighlight        string  `protobuf:"bytes,12,opt,name=name_highlight" json:"name_highlight,omitempty"`               // 名称高亮片段
	DescriptionHighlight string  `protobuf:"bytes,13,opt,name=description_highlight" json:"description_highlight,omitempty"` // 描述高亮片段
}

func (x *ProductSearchResult) Reset() { *x = ProductSearchResult{} }

func (x *ProductSearchResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ProductSearchResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ProductSearchResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductSearchResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductSearchResult) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *ProductSearchResult) GetSliderImgs() []string {
	if x != nil {
		return x.SliderImgs
	}
	return nil
}

func (x *ProductSearchResult) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductSearchResult) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ProductSearchResult) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *ProductSearchResult) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *ProductSearchResult) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *ProductSearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProductSearchResult) GetNameHighlight() string {
	if x != nil {
		return x.NameHighlight
	}
	return ""
}

func (x *ProductSearchResult) GetDescriptionHighlight() string {
	if x != nil {
		return x.DescriptionHighlight
	}
	return ""
}

type SearchSuggestReq struct {
	Keyword string      `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"` // 输入关键字
	Limit   int64       `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`    // 返回数量，默认 10
	Type    SuggestType `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`      // 建议类型（商品/商家）
}

func (x *SearchSuggestReq) Reset() { *x = SearchSuggestReq{} }

func (x *SearchSuggestReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchSuggestReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchSuggestReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchSuggestReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchSuggestReq) GetType() SuggestType {
	if x != nil {
		return x.Type
	}
	return SuggestType_PRODUCT
}

type SearchSuggestResp struct {
	Suggestions []*SearchSuggestion `protobuf:"bytes,1,rep,name=suggestions" json:"suggestions,omitempty"`
}

func (x *SearchSuggestResp) Reset() { *x = SearchSuggestResp{} }

func (x *SearchSuggestResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchSuggestResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchSuggestResp) GetSuggestions() []*SearchSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

// 搜索建议项
type SearchSuggestion struct {
	Keyword string        `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"` // 建议的关键字
	Source  SuggestSource `protobuf:"varint,2,opt,name=source" json:"source,omitempty"`  // 来源（历史/热门/名称匹配）
	Count   int64         `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`    // 搜索次数（热门度，可选）
}

func (x *SearchSuggestion) Reset() { *x = SearchSuggestion{} }

func (x *SearchSuggestion) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchSuggestion) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchSuggestion) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchSuggestion) GetSource() SuggestSource {
	if x != nil {
		return x.Source
	}
	return SuggestSource_HISTORY
}

func (x *SearchSuggestion) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchAggregationsResp struct {
	Categories  []*CategoryAggregation   `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`     // 分类聚合
	PriceRanges []*PriceRangeAggregation `protobuf:"bytes,2,rep,name=price_ranges" json:"price_ranges,omitempty"` // 价格区间聚合
}

func (x *SearchAggregationsResp) Reset() { *x = SearchAggregationsResp{} }

func (x *SearchAggregationsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *SearchAggregationsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchAggregationsResp) GetCategories() []*CategoryAggregation {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *SearchAggregationsResp) GetPriceRanges() []*PriceRangeAggregation {
	if x != nil {
		return x.PriceRanges
	}
	return nil
}

type CategoryAggregation struct {
	Category string `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"` // 分类名称
	Count    int64  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`      // 该分类下的商品数量
}

func (x *CategoryAggregation) Reset() { *x = CategoryAggregation{} }

func (x *CategoryAggregation) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CategoryAggregation) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CategoryAggregation) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryAggregation) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PriceRangeAggregation struct {
	MinPrice int64  `protobuf:"varint,1,opt,name=min_price" json:"min_price,omitempty"` // 区间最低价（分）
	MaxPrice int64  `protobuf:"varint,2,opt,name=max_price" json:"max_price,omitempty"` // 区间最高价（分）
	Count    int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`         // 该区间的商品数量
	Label    string `protobuf:"bytes,4,opt,name=label" json:"label,omitempty"`          // 显示标签，如 "0-100元"
}

func (x *PriceRangeAggregation) Reset() { *x = PriceRangeAggregation{} }

func (x *PriceRangeAggregation) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *PriceRangeAggregation) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PriceRangeAggregation) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *PriceRangeAggregation) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *PriceRangeAggregation) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PriceRangeAggregation) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// 商家搜索请求
type SearchMerchantsReq struct {
	Keyword  string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`      // 搜索关键字（商家名称）
	Page     int64  `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`           // 页码，从 1 开始
	PageSize int64  `protobuf:"varint,3,opt,name=page_size" json:"page_size,omitempty"` // 每页数量

	// 筛选条件
	Region       string  `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`                // 地区筛选（如 "北京"、"上海"）
	MinRating    float32 `protobuf:"fixed32,5,opt,name=min_rating" json:"min_rating,omitempty"`      // 最低评分（0-5）
	VerifiedOnly bool    `protobuf:"varint,6,opt,name=verified_only" json:"verified_only,omitempty"` // 只看认证商家

	// 排序
	SortBy MerchantSortType `protobuf:"varint,7,opt,name=sort_by" json:"sort_by,omitempty"` // 排序方式
}

func (x *SearchMerchantsReq) Reset() { *x = SearchMerchantsReq{} }

func (x *SearchMerchantsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchMerchantsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchMerchantsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchMerchantsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMerchantsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchMerchantsReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *SearchMerchantsReq) GetMinRating() float32 {
	if x != nil {
		return x.MinRating
	}
	return 0
}

func (x *SearchMerchantsReq) GetVerifiedOnly() bool {
	if x != nil {
		return x.VerifiedOnly
	}
	return false
}

func (x *SearchMerchantsReq) GetSortBy() MerchantSortType {
	if x != nil {
		return x.SortBy
	}
	return MerchantSortType_MERCHANT_RELEVANCE
}

// 商家搜索响应
type SearchMerchantsResp struct {
	Merchants []*MerchantSearchResult `protobuf:"bytes,1,rep,name=merchants" json:"merchants,omitempty"`  // 商家列表
	Total     int64                   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`         // 总数
	Page      int64                   `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`           // 当前页
	PageSize  int64                   `protobuf:"varint,4,opt,name=page_size" json:"page_size,omitempty"` // 每页数量
}

func (x *SearchMerchantsResp) Reset() { *x = SearchMerchantsResp{} }

func (x *SearchMerchantsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SearchMerchantsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SearchMerchantsResp) GetMerchants() []*MerchantSearchResult {
	if x != nil {
		return x.Merchants
	}
	return nil
}

func (x *SearchMerchantsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchMerchantsResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMerchantsResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 商家搜索结果
type MerchantSearchResult struct {
	Id           int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`                    // 商家名称
	Description  string  `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`      // 商家描述
	Logo         string  `protobuf:"bytes,4,opt,name=logo" json:"logo,omitempty"`                    // 商家 Logo
	Region       string  `protobuf:"bytes,5,opt,name=region" json:"region,omitempty"`                // 所在地区
	Rating       float32 `protobuf:"fixed32,6,opt,name=rating" json:"rating,omitempty"`              // 评分（0-5）
	SalesCount   int64   `protobuf:"varint,7,opt,name=sales_count" json:"sales_count,omitempty"`     // 销量
	ProductCount int64   `protobuf:"varint,8,opt,name=product_count" json:"product_count,omitempty"` // 商品数量
	Verified     bool    `protobuf:"varint,9,opt,name=verified" json:"verified,omitempty"`           // 是否认证

	// 搜索相关字段
	Score         float32 `protobuf:"fixed32,10,opt,name=score" json:"score,omitempty"`                 // 相关性评分
	NameHighlight string  `protobuf:"bytes,11,opt,name=name_highlight" json:"name_highlight,omitempty"` // 名称高亮片段
}

func (x *MerchantSearchResult) Reset() { *x = MerchantSearchResult{} }

func (x *MerchantSearchResult) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *MerchantSearchResult) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *MerchantSearchResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantSearchResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MerchantSearchResult) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *MerchantSearchResult) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *MerchantSearchResult) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *MerchantSearchResult) GetSalesCount() int64 {
	if x != nil {
		return x.SalesCount
	}
	return 0
}

func (x *MerchantSearchResult) GetProductCount() int64 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

func (x *MerchantSearchResult) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *MerchantSearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MerchantSearchResult) GetNameHighlight() string {
	if x != nil {
		return x.NameHighlight
	}
	return ""
}

// ES 数据初始化请求
// 注意：索引结构已在服务启动时自动创建（类似数据库的 AutoMigrate）
// 此接口用于从数据源（MySQL/Product Service）全量导入数据到 ES
// 适用场景：首次部署、重建索引、数据修复
type InitESReq struct {
	RecreateIndices bool `protobuf:"varint,1,opt,name=recreate_indices" json:"recreate_indices,omitempty"` // 是否重建索引（删除后重新创建），默认 false
	SyncProducts    bool `protobuf:"varint,2,opt,name=sync_products" json:"sync_products,omitempty"`       // 是否同步商品数据（从数据源拉取全量数据）
	SyncMerchants   bool `protobuf:"varint,3,opt,name=sync_merchants" json:"sync_merchants,omitempty"`     // 是否同步商家数据（从数据源拉取全量数据）

	// 分批同步参数（避免一次性加载过多数据）
	BatchSize int64 `protobuf:"varint,4,opt,name=batch_size" json:"batch_size,omitempty"` // 每批次数量，默认 1000
}

func (x *InitESReq) Reset() { *x = InitESReq{} }

func (x *InitESReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *InitESReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *InitESReq) GetRecreateIndices() bool {
	if x != nil {
		return x.RecreateIndices
	}
	return false
}

func (x *InitESReq) GetSyncProducts() bool {
	if x != nil {
		return x.SyncProducts
	}
	return false
}

func (x *InitESReq) GetSyncMerchants() bool {
	if x != nil {
		return x.SyncMerchants
	}
	return false
}

func (x *InitESReq) GetBatchSize() int64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

// ES 数据初始化响应
type InitESResp struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`

	// 索引创建结果（如果执行了重建）
	IndicesCreated bool `protobuf:"varint,3,opt,name=indices_created" json:"indices_created,omitempty"` // 索引是否创建/重建成功

	// 数据同步结果（如果执行了同步）
	ProductsSynced  int64    `protobuf:"varint,4,opt,name=products_synced" json:"products_synced,omitempty"`   // 同步成功的商品数量
	ProductsFailed  int64    `protobuf:"varint,5,opt,name=products_failed" json:"products_failed,omitempty"`   // 同步失败的商品数量
	MerchantsSynced int64    `protobuf:"varint,6,opt,name=merchants_synced" json:"merchants_synced,omitempty"` // 同步成功的商家数量
	MerchantsFailed int64    `protobuf:"varint,7,opt,name=merchants_failed" json:"merchants_failed,omitempty"` // 同步失败的商家数量
	Errors          []string `protobuf:"bytes,8,rep,name=errors" json:"errors,omitempty"`                      // 错误信息列表
}

func (x *InitESResp) Reset() { *x = InitESResp{} }

func (x *InitESResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *InitESResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *InitESResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitESResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitESResp) GetIndicesCreated() bool {
	if x != nil {
		return x.IndicesCreated
	}
	return false
}

func (x *InitESResp) GetProductsSynced() int64 {
	if x != nil {
		return x.ProductsSynced
	}
	return 0
}

func (x *InitESResp) GetProductsFailed() int64 {
	if x != nil {
		return x.ProductsFailed
	}
	return 0
}

func (x *InitESResp) GetMerchantsSynced() int64 {
	if x != nil {
		return x.MerchantsSynced
	}
	return 0
}

func (x *InitESResp) GetMerchantsFailed() int64 {
	if x != nil {
		return x.MerchantsFailed
	}
	return 0
}

func (x *InitESResp) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type AISearchProductsReq struct {
	Query           string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"` // 用户原始查询（自然语言）
	Page            int64  `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize        int64  `protobuf:"varint,3,opt,name=page_size" json:"page_size,omitempty"`
	EnableRag       bool   `protobuf:"varint,4,opt,name=enable_rag" json:"enable_rag,omitempty"` // 是否生成 RAG 摘要
	EnableHighlight bool   `protobuf:"varint,5,opt,name=enable_highlight" json:"enable_highlight,omitempty"`
}

func (x *AISearchProductsReq) Reset() { *x = AISearchProductsReq{} }

func (x *AISearchProductsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AISearchProductsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AISearchProductsReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AISearchProductsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AISearchProductsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AISearchProductsReq) GetEnableRag() bool {
	if x != nil {
		return x.EnableRag
	}
	return false
}

func (x *AISearchProductsReq) GetEnableHighlight() bool {
	if x != nil {
		return x.EnableHighlight
	}
	return false
}

type AISearchProductsResp struct {
	Products    []*ProductSearchResult `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
	Total       int64                  `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Page        int64                  `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize    int64                  `protobuf:"varint,4,opt,name=page_size" json:"page_size,omitempty"`
	QueryIntent *QueryIntent           `protobuf:"bytes,5,opt,name=query_intent" json:"query_intent,omitempty"` // LLM 解析的意图
	RagSummary  string                 `protobuf:"bytes,6,opt,name=rag_summary" json:"rag_summary,omitempty"`   // RAG 生成的搜索摘要
	Metrics     *PipelineMetrics       `protobuf:"bytes,7,opt,name=metrics" json:"metrics,omitempty"`           // 管线各阶段耗时
}

func (x *AISearchProductsResp) Reset() { *x = AISearchProductsResp{} }

func (x *AISearchProductsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AISearchProductsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AISearchProductsResp) GetProducts() []*ProductSearchResult {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *AISearchProductsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AISearchProductsResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AISearchProductsResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AISearchProductsResp) GetQueryIntent() *QueryIntent {
	if x != nil {
		return x.QueryIntent
	}
	return nil
}

func (x *AISearchProductsResp) GetRagSummary() string {
	if x != nil {
		return x.RagSummary
	}
	return ""
}

func (x *AISearchProductsResp) GetMetrics() *PipelineMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// LLM 解析的查询意图
type QueryIntent struct {
	RewrittenQuery string   `protobuf:"bytes,1,opt,name=rewritten_query" json:"rewritten_query,omitempty"` // 重写后的关键词
	Categories     []string `protobuf:"bytes,2,rep,name=categories" json:"categories,omitempty"`           // 识别的类目
	MinPrice       int64    `protobuf:"varint,3,opt,name=min_price" json:"min_price,omitempty"`            // 价格下限（分）
	MaxPrice       int64    `protobuf:"varint,4,opt,name=max_price" json:"max_price,omitempty"`            // 价格上限（分）
	SortBy         string   `protobuf:"bytes,5,opt,name=sort_by" json:"sort_by,omitempty"`                 // 排序意图
	Intent         string   `protobuf:"bytes,6,opt,name=intent" json:"intent,omitempty"`                   // 意图描述
	NeedRag        bool     `protobuf:"varint,7,opt,name=need_rag" json:"need_rag,omitempty"`              // 是否需要 RAG
}

func (x *QueryIntent) Reset() { *x = QueryIntent{} }

func (x *QueryIntent) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *QueryIntent) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *QueryIntent) GetRewrittenQuery() string {
	if x != nil {
		return x.RewrittenQuery
	}
	return ""
}

func (x *QueryIntent) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *QueryIntent) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *QueryIntent) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *QueryIntent) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *QueryIntent) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *QueryIntent) GetNeedRag() bool {
	if x != nil {
		return x.NeedRag
	}
	return false
}

// 管线可观测性指标（各阶段耗时 ms）
type PipelineMetrics struct {
	QueryUnderstandingMs int64 `protobuf:"varint,1,opt,name=query_understanding_ms" json:"query_understanding_ms,omitempty"`
	KeywordRecallMs      int64 `protobuf:"varint,2,opt,name=keyword_recall_ms" json:"keyword_recall_ms,omitempty"`
	VectorRecallMs       int64 `protobuf:"varint,3,opt,name=vector_recall_ms" json:"vector_recall_ms,omitempty"`
	RankingMs            int64 `protobuf:"varint,4,opt,name=ranking_ms" json:"ranking_ms,omitempty"`
	FetchMs              int64 `protobuf:"varint,5,opt,name=fetch_ms" json:"fetch_ms,omitempty"`
	RagMs                int64 `protobuf:"varint,6,opt,name=rag_ms" json:"rag_ms,omitempty"`
	TotalMs              int64 `protobuf:"varint,7,opt,name=total_ms" json:"total_ms,omitempty"`
	KeywordRecallCount   int32 `protobuf:"varint,8,opt,name=keyword_recall_count" json:"keyword_recall_count,omitempty"`
	VectorRecallCount    int32 `protobuf:"varint,9,opt,name=vector_recall_count" json:"vector_recall_count,omitempty"`
}

func (x *PipelineMetrics) Reset() { *x = PipelineMetrics{} }

func (x *PipelineMetrics) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PipelineMetrics) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PipelineMetrics) GetQueryUnderstandingMs() int64 {
	if x != nil {
		return x.QueryUnderstandingMs
	}
	return 0
}

func (x *PipelineMetrics) GetKeywordRecallMs() int64 {
	if x != nil {
		return x.KeywordRecallMs
	}
	return 0
}

func (x *PipelineMetrics) GetVectorRecallMs() int64 {
	if x != nil {
		return x.VectorRecallMs
	}
	return 0
}

func (x *PipelineMetrics) GetRankingMs() int64 {
	if x != nil {
		return x.RankingMs
	}
	return 0
}

func (x *PipelineMetrics) GetFetchMs() int64 {
	if x != nil {
		return x.FetchMs
	}
	return 0
}

func (x *PipelineMetrics) GetRagMs() int64 {
	if x != nil {
		return x.RagMs
	}
	return 0
}

func (x *PipelineMetrics) GetTotalMs() int64 {
	if x != nil {
		return x.TotalMs
	}
	return 0
}

func (x *PipelineMetrics) GetKeywordRecallCount() int32 {
	if x != nil {
		return x.KeywordRecallCount
	}
	return 0
}

func (x *PipelineMetrics) GetVectorRecallCount() int32 {
	if x != nil {
		return x.VectorRecallCount
	}
	return 0
}

type SearchService interface {
	SearchProducts(ctx context.Context, req *SearchProductsReq) (res *SearchProductsResp, err error)
	GetSearchAggregations(ctx context.Context, req *SearchProductsReq) (res *SearchAggregationsResp, err error)
	SearchMerchants(ctx context.Context, req *SearchMerchantsReq) (res *SearchMerchantsResp, err error)
	SearchSuggest(ctx context.Context, req *SearchSuggestReq) (res *SearchSuggestResp, err error)
	InitES(ctx context.Context, req *InitESReq) (res *InitESResp, err error)
	AISearchProducts(ctx context.Context, req *AISearchProductsReq) (res *AISearchProductsResp, err error)
}
