// Code generated by Kitex v0.16.1. DO NOT EDIT.

package cartv1

import (
	"context"

	"github.com/cloudwego/prutal"
)

type CartItem struct {
	// 璺熻喘鐗╄溅鐩稿叧鐨勫瓧娈?	ProductId int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	Quantity  int64 `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *CartItem) Reset() { *x = CartItem{} }

func (x *CartItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CartItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CartItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddItemReq struct {
	UserId     int64   `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	ProductIds []int64 `protobuf:"varint,2,rep,packed,name=product_ids" json:"product_ids,omitempty"`
}

func (x *AddItemReq) Reset() { *x = AddItemReq{} }

func (x *AddItemReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AddItemReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AddItemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemReq) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type AddItemResp struct {
}

func (x *AddItemResp) Reset() { *x = AddItemResp{} }

func (x *AddItemResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AddItemResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type DeleteItemReq struct {
	UserId     int64   `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	ProductIds []int64 `protobuf:"varint,2,rep,packed,name=product_ids" json:"product_ids,omitempty"`
}

func (x *DeleteItemReq) Reset() { *x = DeleteItemReq{} }

func (x *DeleteItemReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteItemReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteItemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteItemReq) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type DeleteItemResp struct {
}

func (x *DeleteItemResp) Reset() { *x = DeleteItemResp{} }

func (x *DeleteItemResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteItemResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type GetCartReq struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetCartReq) Reset() { *x = GetCartReq{} }

func (x *GetCartReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetCartReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Cart struct {
	UserId int64       `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Items  []*CartItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (x *Cart) Reset() { *x = Cart{} }

func (x *Cart) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Cart) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Cart) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetCartResp struct {
	Cart *Cart `protobuf:"bytes,1,opt,name=cart" json:"cart,omitempty"`
}

func (x *GetCartResp) Reset() { *x = GetCartResp{} }

func (x *GetCartResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetCartResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetCartResp) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type EmptyCartReq struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *EmptyCartReq) Reset() { *x = EmptyCartReq{} }

func (x *EmptyCartReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EmptyCartReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *EmptyCartReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EmptyCartResp struct {
}

func (x *EmptyCartResp) Reset() { *x = EmptyCartResp{} }

func (x *EmptyCartResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *EmptyCartResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type ChangeQtyReq struct {
	UserId int64     `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Item   *CartItem `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
}

func (x *ChangeQtyReq) Reset() { *x = ChangeQtyReq{} }

func (x *ChangeQtyReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChangeQtyReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChangeQtyReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangeQtyReq) GetItem() *CartItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ChangeQtyResp struct {
}

func (x *ChangeQtyResp) Reset() { *x = ChangeQtyResp{} }

func (x *ChangeQtyResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChangeQtyResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type IncrementQtyReq struct {
	UserId    int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	ProductId int64 `protobuf:"varint,2,opt,name=product_id" json:"product_id,omitempty"`
}

func (x *IncrementQtyReq) Reset() { *x = IncrementQtyReq{} }

func (x *IncrementQtyReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IncrementQtyReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IncrementQtyReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IncrementQtyReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type IncrementQtyResp struct {
	NewQuantity int64 `protobuf:"varint,1,opt,name=new_quantity" json:"new_quantity,omitempty"`
}

func (x *IncrementQtyResp) Reset() { *x = IncrementQtyResp{} }

func (x *IncrementQtyResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IncrementQtyResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IncrementQtyResp) GetNewQuantity() int64 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

type DecrementQtyReq struct {
	UserId    int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	ProductId int64 `protobuf:"varint,2,opt,name=product_id" json:"product_id,omitempty"`
}

func (x *DecrementQtyReq) Reset() { *x = DecrementQtyReq{} }

func (x *DecrementQtyReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DecrementQtyReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DecrementQtyReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DecrementQtyReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DecrementQtyResp struct {
	NewQuantity int64 `protobuf:"varint,1,opt,name=new_quantity" json:"new_quantity,omitempty"`
}

func (x *DecrementQtyResp) Reset() { *x = DecrementQtyResp{} }

func (x *DecrementQtyResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DecrementQtyResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DecrementQtyResp) GetNewQuantity() int64 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

type CartService interface {
	AddItem(ctx context.Context, req *AddItemReq) (res *AddItemResp, err error)
	DeleteItem(ctx context.Context, req *DeleteItemReq) (res *DeleteItemResp, err error)
	GetCart(ctx context.Context, req *GetCartReq) (res *GetCartResp, err error)
	EmptyCart(ctx context.Context, req *EmptyCartReq) (res *EmptyCartResp, err error)
	ChangeQty(ctx context.Context, req *ChangeQtyReq) (res *ChangeQtyResp, err error)
	IncrementQty(ctx context.Context, req *IncrementQtyReq) (res *IncrementQtyResp, err error)
	DecrementQty(ctx context.Context, req *DecrementQtyReq) (res *DecrementQtyResp, err error)
}


