// Code generated by Kitex v0.15.4. DO NOT EDIT.

package productv1

import (
	"context"

	"github.com/cloudwego/prutal"
)

type Product struct {
	Id           int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`                     // Product ID.
	Name         string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`                  // Product name.
	Description  string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`    // Product description.
	Picture      string   `protobuf:"bytes,4,opt,name=picture" json:"picture,omitempty"`            // Cover image URL.
	SliderImgs   []string `protobuf:"bytes,5,rep,name=sliderImgs" json:"sliderImgs,omitempty"`      // Gallery image URLs.
	Price        int64    `protobuf:"varint,6,opt,name=price" json:"price,omitempty"`               // Price in minor units, for example cents/fen.
	Categories   []string `protobuf:"bytes,7,rep,name=categories" json:"categories,omitempty"`      // Category labels.
	InStock      bool     `protobuf:"varint,8,opt,name=in_stock" json:"in_stock,omitempty"`         // Availability flag; exact inventory is owned by inventory service.
	MerchantID   int64    `protobuf:"varint,9,opt,name=merchantID" json:"merchantID,omitempty"`     // Merchant ID.
	MerchantName string   `protobuf:"bytes,10,opt,name=merchantName" json:"merchantName,omitempty"` // Merchant name.
	Currency     string   `protobuf:"bytes,11,opt,name=currency" json:"currency,omitempty"`         // Currency code, for example CNY or USD.
	SkuId        int64    `protobuf:"varint,12,opt,name=sku_id" json:"sku_id,omitempty"`            // SKU ID used for SKU-specific price and stock.
}

func (x *Product) Reset() { *x = Product{} }

func (x *Product) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Product) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *Product) GetSliderImgs() []string {
	if x != nil {
		return x.SliderImgs
	}
	return nil
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *Product) GetMerchantID() int64 {
	if x != nil {
		return x.MerchantID
	}
	return 0
}

func (x *Product) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

type CreateProductReq struct {
	Product *Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}

func (x *CreateProductReq) Reset() { *x = CreateProductReq{} }

func (x *CreateProductReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateProductReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateProductReq) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateProductResp struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *CreateProductResp) Reset() { *x = CreateProductResp{} }

func (x *CreateProductResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateProductResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateProductResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProductReq struct {
	Product *Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}

func (x *UpdateProductReq) Reset() { *x = UpdateProductReq{} }

func (x *UpdateProductReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateProductReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProductReq) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductResp struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (x *UpdateProductResp) Reset() { *x = UpdateProductResp{} }

func (x *UpdateProductResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateProductResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProductResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductReq struct {
	Id     int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *DeleteProductReq) Reset() { *x = DeleteProductReq{} }

func (x *DeleteProductReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteProductReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteProductReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteProductResp struct {
}

func (x *DeleteProductResp) Reset() { *x = DeleteProductResp{} }

func (x *DeleteProductResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteProductResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type ListProductsReq struct {
	Page     int64  `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	PageSize int64  `protobuf:"varint,2,opt,name=pageSize" json:"pageSize,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=category" json:"category,omitempty"`
}

func (x *ListProductsReq) Reset() { *x = ListProductsReq{} }

func (x *ListProductsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListProductsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListProductsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListProductsResp struct {
	Products []*Product `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
}

func (x *ListProductsResp) Reset() { *x = ListProductsResp{} }

func (x *ListProductsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListProductsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListProductsResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductQuery struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	SkuId     int64 `protobuf:"varint,2,opt,name=sku_id" json:"sku_id,omitempty"`
}

func (x *ProductQuery) Reset() { *x = ProductQuery{} }

func (x *ProductQuery) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ProductQuery) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ProductQuery) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductQuery) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

type GetProductsReq struct {
	Items []*ProductQuery `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (x *GetProductsReq) Reset() { *x = GetProductsReq{} }

func (x *GetProductsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetProductsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductsReq) GetItems() []*ProductQuery {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetProductsResp struct {
	Product []*Product `protobuf:"bytes,1,rep,name=product" json:"product,omitempty"`
}

func (x *GetProductsResp) Reset() { *x = GetProductsResp{} }

func (x *GetProductsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetProductsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductsResp) GetProduct() []*Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ProductQuote struct {
	ProductId int64  `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	SkuId     int64  `protobuf:"varint,2,opt,name=sku_id" json:"sku_id,omitempty"`
	Price     int64  `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Currency  string `protobuf:"bytes,4,opt,name=currency" json:"currency,omitempty"`
	InStock   bool   `protobuf:"varint,5,opt,name=in_stock" json:"in_stock,omitempty"`
}

func (x *ProductQuote) Reset() { *x = ProductQuote{} }

func (x *ProductQuote) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ProductQuote) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ProductQuote) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductQuote) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *ProductQuote) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductQuote) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProductQuote) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

type GetProductQuotesReq struct {
	Items []*ProductQuery `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (x *GetProductQuotesReq) Reset() { *x = GetProductQuotesReq{} }

func (x *GetProductQuotesReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetProductQuotesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductQuotesReq) GetItems() []*ProductQuery {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetProductQuotesResp struct {
	ProductQuotes []*ProductQuote `protobuf:"bytes,1,rep,name=product_quotes" json:"product_quotes,omitempty"`
}

func (x *GetProductQuotesResp) Reset() { *x = GetProductQuotesResp{} }

func (x *GetProductQuotesResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetProductQuotesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetProductQuotesResp) GetProductQuotes() []*ProductQuote {
	if x != nil {
		return x.ProductQuotes
	}
	return nil
}

type ProductService interface {
	ListProducts(ctx context.Context, req *ListProductsReq) (res *ListProductsResp, err error)
	GetProducts(ctx context.Context, req *GetProductsReq) (res *GetProductsResp, err error)
	GetProductQuotes(ctx context.Context, req *GetProductQuotesReq) (res *GetProductQuotesResp, err error)
	CreateProduct(ctx context.Context, req *CreateProductReq) (res *CreateProductResp, err error)
	UpdateProduct(ctx context.Context, req *UpdateProductReq) (res *UpdateProductResp, err error)
	DeleteProduct(ctx context.Context, req *DeleteProductReq) (res *DeleteProductResp, err error)
}
