// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/search/events"
	"github.com/XDWow/DouyinMall/backend/internal/search/handler"
	"github.com/XDWow/DouyinMall/backend/internal/search/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/search/repo"
	"github.com/XDWow/DouyinMall/backend/internal/search/service"
	"github.com/XDWow/DouyinMall/backend/pkg/saramax"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

// InitApp 初始化整个应用
func InitApp() *App {
	esClient := ioc.InitES()
	loggerV1 := ioc.InitLogger()
	productRepo := repo.NewProductRepo(esClient, loggerV1)
	merchantRepo := repo.NewMerchantRepo(esClient, loggerV1)
	searchService := service.NewSearchService(productRepo, merchantRepo, loggerV1)
	syncService := service.NewSyncService(productRepo, merchantRepo, loggerV1)
	client := ioc.InitProductClient()
	searchHandler := handler.NewSearchHandler(searchService, syncService, esClient, client)
	server := ioc.InitGRPCServer(searchHandler)
	saramaClient := ioc.InitKafkaClient()
	productConsumer := events.NewProductConsumer(saramaClient, loggerV1, syncService)
	merchantConsumer := events.NewMerchantConsumer(saramaClient, loggerV1, syncService)
	app := newApp(server, productConsumer, merchantConsumer)
	return app
}

// wire.go:

// newApp 组装 App
func newApp(
	svr server.Server,
	productConsumer *events.ProductConsumer,
	merchantConsumer *events.MerchantConsumer,
) *App {
	return &App{
		Server: svr,
		Consumers: []saramax.Consumer{
			productConsumer,
			merchantConsumer,
		},
	}
}
