// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/product/handler"
	"github.com/XDWow/DouyinMall/backend/internal/product/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/product/producer"
	"github.com/XDWow/DouyinMall/backend/internal/product/repo"
	"github.com/XDWow/DouyinMall/backend/internal/product/repo/cache"
	"github.com/XDWow/DouyinMall/backend/internal/product/repo/dao"
	"github.com/XDWow/DouyinMall/backend/internal/product/service"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	productDao := dao.NewGORMProductDao(db)
	cmdable := ioc.InitRedis()
	productCache := cache.NewRedisProductCache(cmdable)
	loggerV1 := ioc.InitLogger()
	productRepo := repo.NewCachedProductRepo(productDao, productCache, loggerV1)
	productService := service.NewProductService(productRepo, loggerV1)
	productHandler := handler.NewProductHandler(productService)
	server := ioc.InitGRPCServer(productHandler)
	client := ioc.InitKafkaClient()
	syncProducer := ioc.InitKafkaSyncProducer(client)
	producer := ioc.InitCanalProducer(syncProducer, loggerV1, db)
	app := newApp(server, producer)
	return app
}

// wire.go:

// newApp 组装 App
func newApp(svr server.Server, p producer.Producer) *App {
	return &App{
		Server: svr,
		Producers: []ProducerComponent{
			&producerWrapper{Producer: p},
		},
	}
}
