// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/product/handler"
	"github.com/XDWow/DouyinMall/backend/internal/product/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/product/repo"
	"github.com/XDWow/DouyinMall/backend/internal/product/repo/cache"
	"github.com/XDWow/DouyinMall/backend/internal/product/repo/dao"
	"github.com/XDWow/DouyinMall/backend/internal/product/service"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

func InitApp() server.Server {
	db := ioc.InitDB()
	productDao := dao.NewGORMProductDao(db)
	cmdable := ioc.InitRedis()
	productCache := cache.NewRedisProductCache(cmdable)
	loggerV1 := ioc.InitLogger()
	productRepo := repo.NewCachedProductRepo(productDao, productCache, loggerV1)
	productService := service.NewProductService(productRepo, loggerV1)
	productHandler := handler.NewProductHandler(productService)
	serverServer := ioc.InitGRPCServer(productHandler)
	return serverServer
}
