// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/coupon/infra/mq"
	"github.com/XDWow/DouyinMall/backend/internal/coupon/infra/repository"
	"github.com/XDWow/DouyinMall/backend/internal/coupon/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/coupon/transport/grpc"
	"github.com/XDWow/DouyinMall/backend/internal/coupon/usecase"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

func InitApp() *App {
	db := ioc.InitDB()
	loggerV1 := ioc.InitLogger()
	couponRepository := repository.NewCouponRepository(db, loggerV1)
	listUserCouponsUseCase := usecase.NewListUserCouponsUseCase(couponRepository)
	evaluateOrderCouponsUseCase := usecase.NewEvaluateOrderCouponsUseCase(couponRepository)
	reserveCouponUseCase := usecase.NewReserveCouponUseCase(couponRepository)
	commitCouponUseCase := usecase.NewCommitCouponUseCase(couponRepository)
	releaseCouponUseCase := usecase.NewReleaseCouponUseCase(couponRepository)
	refundCouponUseCase := usecase.NewRefundCouponUseCase(couponRepository)
	couponTemplateRepository := repository.NewCouponTemplateRepository(db, loggerV1)
	couponOperationRepository := repository.NewCouponOperationRepository(db, loggerV1)
	issueCouponUseCase := usecase.NewIssueCouponUseCase(couponTemplateRepository, couponRepository, couponOperationRepository)
	couponHandler := grpc.NewCouponHandler(listUserCouponsUseCase, evaluateOrderCouponsUseCase, reserveCouponUseCase, commitCouponUseCase, releaseCouponUseCase, refundCouponUseCase, issueCouponUseCase)
	server := ioc.InitGRPCServer(couponHandler)
	client := ioc.InitKafkaClient()
	orderConsumer := mq.NewOrderConsumer(client, commitCouponUseCase, releaseCouponUseCase, refundCouponUseCase, loggerV1)
	app := newApp(server, orderConsumer)
	return app
}

// wire.go:

type App struct {
	GRPCServer    server.Server
	OrderConsumer *mq.OrderConsumer
}

func newApp(
	grpcServer server.Server,
	orderConsumer *mq.OrderConsumer,
) *App {
	return &App{
		GRPCServer:    grpcServer,
		OrderConsumer: orderConsumer,
	}
}


