// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/seckill/infra/cache"
	"github.com/XDWow/DouyinMall/backend/internal/seckill/infra/local"
	"github.com/XDWow/DouyinMall/backend/internal/seckill/infra/mq"
	"github.com/XDWow/DouyinMall/backend/internal/seckill/infra/repository"
	"github.com/XDWow/DouyinMall/backend/internal/seckill/ioc"
	transportgrpc "github.com/XDWow/DouyinMall/backend/internal/seckill/transport/grpc"
	transporthttp "github.com/XDWow/DouyinMall/backend/internal/seckill/transport/http"
	"github.com/XDWow/DouyinMall/backend/internal/seckill/usecase"
	"github.com/XDWow/DouyinMall/backend/pkg/ginx"
	"github.com/cloudwego/kitex/server"
)

type App struct {
	GRPCServer          server.Server
	HTTPServer          *ginx.Server
	Producer            *mq.Producer
	SeckillConsumer     *mq.SeckillConsumer
	DeadLetterConsumer  *mq.DeadLetterConsumer
	OrderStatusConsumer *mq.OrderStatusConsumer
}

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	gormDB := ioc.InitDB()
	cmdable := ioc.InitRedis()
	redisCache := cache.NewRedisCache(cmdable)
	cache2 := repository.NewCacheRepository(redisCache)
	soldOutMarker := local.NewSoldOutMarker()
	activityRepository := repository.NewActivityRepository(gormDB)
	requestRepository := repository.NewRequestRepository(gormDB)
	transactionListener := mq.NewTransactionListener(cache2, soldOutMarker, loggerV1)
	producerClient := ioc.InitRocketMQProducerClient(transactionListener)
	producer := mq.NewProducer(producerClient, transactionListener, loggerV1)
	seckillPushConsumer := ioc.InitSeckillPushConsumer()
	deadLetterPushConsumer := ioc.InitSeckillDeadLetterPushConsumer()
	deadLetterTopic := ioc.InitSeckillDeadLetterTopic()
	seckillConsumerOptions := ioc.InitSeckillConsumerOptions()
	idGenerator := ioc.InitIDGenerator()
	createActivityUseCase := usecase.NewCreateActivityUseCase(activityRepository, cache2, soldOutMarker)
	updateActivityStatusUseCase := usecase.NewUpdateActivityStatusUseCase(activityRepository, cache2, soldOutMarker)
	getActivityUseCase := usecase.NewGetActivityUseCase(activityRepository, cache2)
	submitUseCase := usecase.NewSubmitUseCase(activityRepository, requestRepository, cache2, soldOutMarker, producer, idGenerator, loggerV1)
	getResultUseCase := usecase.NewGetResultUseCase(requestRepository, cache2)
	handler := transportgrpc.NewHandler(createActivityUseCase, updateActivityStatusUseCase, getActivityUseCase, submitUseCase, getResultUseCase)
	grpcServer := ioc.InitGRPCServer(handler)
	httpHandler := transporthttp.NewHandler(getActivityUseCase, submitUseCase, getResultUseCase)
	httpServer := ioc.InitHTTPServer(httpHandler)
	orderClient := ioc.InitOrderClient()
	processor := mq.NewEventProcessor(orderClient, requestRepository, activityRepository, cache2, soldOutMarker, loggerV1)
	seckillConsumer := mq.NewSeckillConsumer(seckillPushConsumer, processor, loggerV1, seckillConsumerOptions)
	deadLetterConsumer := mq.NewDeadLetterConsumer(deadLetterPushConsumer, deadLetterTopic, processor, loggerV1, seckillConsumerOptions)
	orderStatusPushConsumer := ioc.InitSeckillOrderStatusPushConsumer()
	orderStatusConsumer := mq.NewOrderStatusConsumer(orderStatusPushConsumer, requestRepository, activityRepository, cache2, soldOutMarker, loggerV1, seckillConsumerOptions)
	return &App{
		GRPCServer:          grpcServer,
		HTTPServer:          httpServer,
		Producer:            producer,
		SeckillConsumer:     seckillConsumer,
		DeadLetterConsumer:  deadLetterConsumer,
		OrderStatusConsumer: orderStatusConsumer,
	}
}
