db:
  host: "douyinmall-mysql"
  port: 3306
  user: "root"
  password: ""
  database: "douyin_mall"
  params: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "106.52.154.235:6379"
  password: ""

etcd:
  endpoints:
    - "douyinmall-etcd:2379"

grpc:
  server:
    name: inventory.service
    port: 8094

rocketmq:
  endpoint: "43.136.121.171:8081"
  access_key: ""
  secret_key: ""
  consumer_group: "inventory-consumer"
  await_duration_sec: 5
  max_message_num: 16
  invisible_duration_sec: 30
  producer_max_attempts: 3
