db:
  host: "douyinmall-mysql"
  port: 3306
  user: "root"
  password: ""
  database: "douyinmall"
  params: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "douyinmall-redis:6379"

etcd:
  endpoints:
    - "douyinmall-etcd:2379"

grpc:
  server:
    name: inventory.service
    port: 8094

kafka:
  brokers:
    - "10.1.4.4:29092"
