// Code generated by Kitex v0.16.1. DO NOT EDIT.

package cartservice

import (
	"context"
	"errors"
	cartv1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/cart/v1"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/cart/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddItem": kitex.NewMethodInfo(
		addItemHandler,
		newAddItemArgs,
		newAddItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteItem": kitex.NewMethodInfo(
		deleteItemHandler,
		newDeleteItemArgs,
		newDeleteItemResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCart": kitex.NewMethodInfo(
		getCartHandler,
		newGetCartArgs,
		newGetCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"EmptyCart": kitex.NewMethodInfo(
		emptyCartHandler,
		newEmptyCartArgs,
		newEmptyCartResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ChangeQty": kitex.NewMethodInfo(
		changeQtyHandler,
		newChangeQtyArgs,
		newChangeQtyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"IncrementQty": kitex.NewMethodInfo(
		incrementQtyHandler,
		newIncrementQtyArgs,
		newIncrementQtyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DecrementQty": kitex.NewMethodInfo(
		decrementQtyHandler,
		newDecrementQtyArgs,
		newDecrementQtyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	cartServiceServiceInfo                = NewServiceInfo()
	cartServiceServiceInfoForClient       = NewServiceInfoForClient()
	cartServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return cartServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return cartServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CartService"
	handlerType := (*cartv1.CartService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "cart",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func addItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.AddItemReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cartv1.CartService).AddItem(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AddItemArgs:
		success, err := handler.(cartv1.CartService).AddItem(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AddItemResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAddItemArgs() interface{} {
	return &AddItemArgs{}
}

func newAddItemResult() interface{} {
	return &AddItemResult{}
}

type AddItemArgs struct {
	Req *v1.AddItemReq
}

func (p *AddItemArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AddItemArgs) Unmarshal(in []byte) error {
	msg := new(v1.AddItemReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AddItemArgs_Req_DEFAULT *v1.AddItemReq

func (p *AddItemArgs) GetReq() *v1.AddItemReq {
	if !p.IsSetReq() {
		return AddItemArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AddItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AddItemArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AddItemResult struct {
	Success *v1.AddItemResp
}

var AddItemResult_Success_DEFAULT *v1.AddItemResp

func (p *AddItemResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AddItemResult) Unmarshal(in []byte) error {
	msg := new(v1.AddItemResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AddItemResult) GetSuccess() *v1.AddItemResp {
	if !p.IsSetSuccess() {
		return AddItemResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AddItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.AddItemResp)
}

func (p *AddItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AddItemResult) GetResult() interface{} {
	return p.Success
}

func deleteItemHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DeleteItemReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cartv1.CartService).DeleteItem(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteItemArgs:
		success, err := handler.(cartv1.CartService).DeleteItem(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteItemResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteItemArgs() interface{} {
	return &DeleteItemArgs{}
}

func newDeleteItemResult() interface{} {
	return &DeleteItemResult{}
}

type DeleteItemArgs struct {
	Req *v1.DeleteItemReq
}

func (p *DeleteItemArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteItemArgs) Unmarshal(in []byte) error {
	msg := new(v1.DeleteItemReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteItemArgs_Req_DEFAULT *v1.DeleteItemReq

func (p *DeleteItemArgs) GetReq() *v1.DeleteItemReq {
	if !p.IsSetReq() {
		return DeleteItemArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteItemArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteItemArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteItemResult struct {
	Success *v1.DeleteItemResp
}

var DeleteItemResult_Success_DEFAULT *v1.DeleteItemResp

func (p *DeleteItemResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteItemResult) Unmarshal(in []byte) error {
	msg := new(v1.DeleteItemResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteItemResult) GetSuccess() *v1.DeleteItemResp {
	if !p.IsSetSuccess() {
		return DeleteItemResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteItemResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DeleteItemResp)
}

func (p *DeleteItemResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteItemResult) GetResult() interface{} {
	return p.Success
}

func getCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetCartReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cartv1.CartService).GetCart(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCartArgs:
		success, err := handler.(cartv1.CartService).GetCart(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCartResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCartArgs() interface{} {
	return &GetCartArgs{}
}

func newGetCartResult() interface{} {
	return &GetCartResult{}
}

type GetCartArgs struct {
	Req *v1.GetCartReq
}

func (p *GetCartArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCartArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetCartReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCartArgs_Req_DEFAULT *v1.GetCartReq

func (p *GetCartArgs) GetReq() *v1.GetCartReq {
	if !p.IsSetReq() {
		return GetCartArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCartArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCartArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCartResult struct {
	Success *v1.GetCartResp
}

var GetCartResult_Success_DEFAULT *v1.GetCartResp

func (p *GetCartResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCartResult) Unmarshal(in []byte) error {
	msg := new(v1.GetCartResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCartResult) GetSuccess() *v1.GetCartResp {
	if !p.IsSetSuccess() {
		return GetCartResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCartResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetCartResp)
}

func (p *GetCartResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCartResult) GetResult() interface{} {
	return p.Success
}

func emptyCartHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.EmptyCartReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cartv1.CartService).EmptyCart(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *EmptyCartArgs:
		success, err := handler.(cartv1.CartService).EmptyCart(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EmptyCartResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newEmptyCartArgs() interface{} {
	return &EmptyCartArgs{}
}

func newEmptyCartResult() interface{} {
	return &EmptyCartResult{}
}

type EmptyCartArgs struct {
	Req *v1.EmptyCartReq
}

func (p *EmptyCartArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EmptyCartArgs) Unmarshal(in []byte) error {
	msg := new(v1.EmptyCartReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EmptyCartArgs_Req_DEFAULT *v1.EmptyCartReq

func (p *EmptyCartArgs) GetReq() *v1.EmptyCartReq {
	if !p.IsSetReq() {
		return EmptyCartArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EmptyCartArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EmptyCartArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EmptyCartResult struct {
	Success *v1.EmptyCartResp
}

var EmptyCartResult_Success_DEFAULT *v1.EmptyCartResp

func (p *EmptyCartResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EmptyCartResult) Unmarshal(in []byte) error {
	msg := new(v1.EmptyCartResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EmptyCartResult) GetSuccess() *v1.EmptyCartResp {
	if !p.IsSetSuccess() {
		return EmptyCartResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EmptyCartResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.EmptyCartResp)
}

func (p *EmptyCartResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EmptyCartResult) GetResult() interface{} {
	return p.Success
}

func changeQtyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ChangeQtyReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cartv1.CartService).ChangeQty(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ChangeQtyArgs:
		success, err := handler.(cartv1.CartService).ChangeQty(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ChangeQtyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newChangeQtyArgs() interface{} {
	return &ChangeQtyArgs{}
}

func newChangeQtyResult() interface{} {
	return &ChangeQtyResult{}
}

type ChangeQtyArgs struct {
	Req *v1.ChangeQtyReq
}

func (p *ChangeQtyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ChangeQtyArgs) Unmarshal(in []byte) error {
	msg := new(v1.ChangeQtyReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ChangeQtyArgs_Req_DEFAULT *v1.ChangeQtyReq

func (p *ChangeQtyArgs) GetReq() *v1.ChangeQtyReq {
	if !p.IsSetReq() {
		return ChangeQtyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ChangeQtyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChangeQtyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ChangeQtyResult struct {
	Success *v1.ChangeQtyResp
}

var ChangeQtyResult_Success_DEFAULT *v1.ChangeQtyResp

func (p *ChangeQtyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ChangeQtyResult) Unmarshal(in []byte) error {
	msg := new(v1.ChangeQtyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ChangeQtyResult) GetSuccess() *v1.ChangeQtyResp {
	if !p.IsSetSuccess() {
		return ChangeQtyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ChangeQtyResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ChangeQtyResp)
}

func (p *ChangeQtyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChangeQtyResult) GetResult() interface{} {
	return p.Success
}

func incrementQtyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.IncrementQtyReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cartv1.CartService).IncrementQty(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *IncrementQtyArgs:
		success, err := handler.(cartv1.CartService).IncrementQty(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*IncrementQtyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newIncrementQtyArgs() interface{} {
	return &IncrementQtyArgs{}
}

func newIncrementQtyResult() interface{} {
	return &IncrementQtyResult{}
}

type IncrementQtyArgs struct {
	Req *v1.IncrementQtyReq
}

func (p *IncrementQtyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *IncrementQtyArgs) Unmarshal(in []byte) error {
	msg := new(v1.IncrementQtyReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var IncrementQtyArgs_Req_DEFAULT *v1.IncrementQtyReq

func (p *IncrementQtyArgs) GetReq() *v1.IncrementQtyReq {
	if !p.IsSetReq() {
		return IncrementQtyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *IncrementQtyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IncrementQtyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type IncrementQtyResult struct {
	Success *v1.IncrementQtyResp
}

var IncrementQtyResult_Success_DEFAULT *v1.IncrementQtyResp

func (p *IncrementQtyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *IncrementQtyResult) Unmarshal(in []byte) error {
	msg := new(v1.IncrementQtyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *IncrementQtyResult) GetSuccess() *v1.IncrementQtyResp {
	if !p.IsSetSuccess() {
		return IncrementQtyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *IncrementQtyResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.IncrementQtyResp)
}

func (p *IncrementQtyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IncrementQtyResult) GetResult() interface{} {
	return p.Success
}

func decrementQtyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DecrementQtyReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(cartv1.CartService).DecrementQty(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DecrementQtyArgs:
		success, err := handler.(cartv1.CartService).DecrementQty(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DecrementQtyResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDecrementQtyArgs() interface{} {
	return &DecrementQtyArgs{}
}

func newDecrementQtyResult() interface{} {
	return &DecrementQtyResult{}
}

type DecrementQtyArgs struct {
	Req *v1.DecrementQtyReq
}

func (p *DecrementQtyArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DecrementQtyArgs) Unmarshal(in []byte) error {
	msg := new(v1.DecrementQtyReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DecrementQtyArgs_Req_DEFAULT *v1.DecrementQtyReq

func (p *DecrementQtyArgs) GetReq() *v1.DecrementQtyReq {
	if !p.IsSetReq() {
		return DecrementQtyArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DecrementQtyArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DecrementQtyArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DecrementQtyResult struct {
	Success *v1.DecrementQtyResp
}

var DecrementQtyResult_Success_DEFAULT *v1.DecrementQtyResp

func (p *DecrementQtyResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DecrementQtyResult) Unmarshal(in []byte) error {
	msg := new(v1.DecrementQtyResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DecrementQtyResult) GetSuccess() *v1.DecrementQtyResp {
	if !p.IsSetSuccess() {
		return DecrementQtyResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DecrementQtyResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.DecrementQtyResp)
}

func (p *DecrementQtyResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DecrementQtyResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddItem(ctx context.Context, Req *v1.AddItemReq) (r *v1.AddItemResp, err error) {
	var _args AddItemArgs
	_args.Req = Req
	var _result AddItemResult
	if err = p.c.Call(ctx, "AddItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteItem(ctx context.Context, Req *v1.DeleteItemReq) (r *v1.DeleteItemResp, err error) {
	var _args DeleteItemArgs
	_args.Req = Req
	var _result DeleteItemResult
	if err = p.c.Call(ctx, "DeleteItem", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCart(ctx context.Context, Req *v1.GetCartReq) (r *v1.GetCartResp, err error) {
	var _args GetCartArgs
	_args.Req = Req
	var _result GetCartResult
	if err = p.c.Call(ctx, "GetCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) EmptyCart(ctx context.Context, Req *v1.EmptyCartReq) (r *v1.EmptyCartResp, err error) {
	var _args EmptyCartArgs
	_args.Req = Req
	var _result EmptyCartResult
	if err = p.c.Call(ctx, "EmptyCart", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeQty(ctx context.Context, Req *v1.ChangeQtyReq) (r *v1.ChangeQtyResp, err error) {
	var _args ChangeQtyArgs
	_args.Req = Req
	var _result ChangeQtyResult
	if err = p.c.Call(ctx, "ChangeQty", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IncrementQty(ctx context.Context, Req *v1.IncrementQtyReq) (r *v1.IncrementQtyResp, err error) {
	var _args IncrementQtyArgs
	_args.Req = Req
	var _result IncrementQtyResult
	if err = p.c.Call(ctx, "IncrementQty", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DecrementQty(ctx context.Context, Req *v1.DecrementQtyReq) (r *v1.DecrementQtyResp, err error) {
	var _args DecrementQtyArgs
	_args.Req = Req
	var _result DecrementQtyResult
	if err = p.c.Call(ctx, "DecrementQty", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
