// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/cart/handler"
	"github.com/XDWow/DouyinMall/backend/internal/cart/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository/cache"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository/dao"
	"github.com/XDWow/DouyinMall/backend/internal/cart/service"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	cartCache := cache.NewRedisCache(cmdable)
	db := ioc.InitDB()
	cartDAO := dao.NewGORMCartDAO(db)
	loggerV1 := ioc.InitLogger()
	cartRepository := repository.NewCachedCartRepository(cartCache, cartDAO, loggerV1)
	cartService := service.NewCartService(cartRepository)
	cartHandler := handler.NewCartHandler(cartService)
	server := ioc.InitGRPCServer(cartHandler)
	app := newApp(server)
	return app
}

// wire.go:

// newApp 组装 App
func newApp(svr server.Server) *App {
	return &App{Server: svr}
}
