// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/cart/handler"
	"github.com/XDWow/DouyinMall/backend/internal/cart/infra/mq"
	"github.com/XDWow/DouyinMall/backend/internal/cart/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository/cache"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository/dao"
	"github.com/XDWow/DouyinMall/backend/internal/cart/service"
	"github.com/cloudwego/kitex/server"
)

// Injectors from wire.go:

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	cartCache := cache.NewRedisCache(cmdable)
	db := ioc.InitDB()
	cartDAO := dao.NewGORMCartDAO(db)
	cartRepository := repository.NewCachedCartRepository(cartCache, cartDAO, loggerV1)
	cartService := service.NewCartService(cartRepository)
	cartHandler := handler.NewCartHandler(cartService)
	grpcServer := ioc.InitGRPCServer(cartHandler)
	kafkaClient := ioc.InitKafkaClient()
	orderConsumer := mq.NewOrderConsumer(kafkaClient, cartService, loggerV1)
	app := newApp(grpcServer, orderConsumer)
	return app
}

// wire.go:

// newApp 缁勮 App
func newApp(svr server.Server, consumer *mq.OrderConsumer) *App {
	return &App{Server: svr, OrderConsumer: consumer}
}


