// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/cart/handler"
	"github.com/XDWow/DouyinMall/backend/internal/cart/infra/mq"
	"github.com/XDWow/DouyinMall/backend/internal/cart/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository/cache"
	"github.com/XDWow/DouyinMall/backend/internal/cart/repository/dao"
	"github.com/XDWow/DouyinMall/backend/internal/cart/service"
	transporthttp "github.com/XDWow/DouyinMall/backend/internal/cart/transport/http"
	"github.com/XDWow/DouyinMall/backend/pkg/ginx"
	"github.com/cloudwego/kitex/server"
)

func InitApp() *App {
	loggerV1 := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	cartCache := cache.NewRedisCache(cmdable)
	db := ioc.InitDB()
	cartDAO := dao.NewGORMCartDAO(db)
	cartRepository := repository.NewCachedCartRepository(cartCache, cartDAO, loggerV1)
	cartService := service.NewCartService(cartRepository)
	cartHandler := handler.NewCartHandler(cartService)
	grpcServer := ioc.InitGRPCServer(cartHandler)
	httpHandler := transporthttp.NewHandler(cartService)
	httpServer := ioc.InitHTTPServer(httpHandler)
	simpleConsumer := ioc.InitRocketMQOrderStatusConsumer()
	consumerOptions := ioc.InitRocketMQConsumerOptions()
	orderConsumer := mq.NewOrderConsumer(simpleConsumer, cartService, loggerV1, consumerOptions)
	app := newApp(grpcServer, httpServer, orderConsumer)
	return app
}

func newApp(svr server.Server, httpServer *ginx.Server, consumer *mq.OrderConsumer) *App {
	return &App{Server: svr, HTTPServer: httpServer, OrderConsumer: consumer}
}
