// Code generated by Kitex v0.15.4. DO NOT EDIT.

package paymentservice

import (
	"context"

	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/payment/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

type Client interface {
	NativePrepay(ctx context.Context, req *v1.NativePrePayRequest, callOptions ...callopt.Option) (*v1.NativePrePayResponse, error)
	GetPayment(ctx context.Context, req *v1.GetPaymentRequest, callOptions ...callopt.Option) (*v1.GetPaymentResponse, error)
	ConfirmPayment(ctx context.Context, req *v1.ConfirmPaymentRequest, callOptions ...callopt.Option) (*v1.ConfirmPaymentResponse, error)
}

func NewClient(destService string, opts ...client.Option) (Client, error) {
	options := []client.Option{client.WithDestService(destService)}
	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPaymentServiceClient{kClient: newServiceClient(kc)}, nil
}

func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPaymentServiceClient struct {
	*kClient
}

func (p *kPaymentServiceClient) NativePrepay(ctx context.Context, req *v1.NativePrePayRequest, callOptions ...callopt.Option) (*v1.NativePrePayResponse, error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.NativePrepay(ctx, req)
}

func (p *kPaymentServiceClient) GetPayment(ctx context.Context, req *v1.GetPaymentRequest, callOptions ...callopt.Option) (*v1.GetPaymentResponse, error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPayment(ctx, req)
}

func (p *kPaymentServiceClient) ConfirmPayment(ctx context.Context, req *v1.ConfirmPaymentRequest, callOptions ...callopt.Option) (*v1.ConfirmPaymentResponse, error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfirmPayment(ctx, req)
}


