// Code generated by Kitex v0.15.4. DO NOT EDIT.

package paymentservice

import (
	"context"
	"errors"
	paymentv1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/payment/v1"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/payment/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"NativePrepay": kitex.NewMethodInfo(
		nativePrepayHandler,
		newNativePrepayArgs,
		newNativePrepayResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPayment": kitex.NewMethodInfo(
		getPaymentHandler,
		newGetPaymentArgs,
		newGetPaymentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	paymentServiceServiceInfo                = NewServiceInfo()
	paymentServiceServiceInfoForClient       = NewServiceInfoForClient()
	paymentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return paymentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return paymentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PaymentService"
	handlerType := (*paymentv1.PaymentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "payment.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func nativePrepayHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.NativePrePayRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(paymentv1.PaymentService).NativePrepay(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *NativePrepayArgs:
		success, err := handler.(paymentv1.PaymentService).NativePrepay(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*NativePrepayResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newNativePrepayArgs() interface{} {
	return &NativePrepayArgs{}
}

func newNativePrepayResult() interface{} {
	return &NativePrepayResult{}
}

type NativePrepayArgs struct {
	Req *v1.NativePrePayRequest
}

func (p *NativePrepayArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *NativePrepayArgs) Unmarshal(in []byte) error {
	msg := new(v1.NativePrePayRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var NativePrepayArgs_Req_DEFAULT *v1.NativePrePayRequest

func (p *NativePrepayArgs) GetReq() *v1.NativePrePayRequest {
	if !p.IsSetReq() {
		return NativePrepayArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *NativePrepayArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *NativePrepayArgs) GetFirstArgument() interface{} {
	return p.Req
}

type NativePrepayResult struct {
	Success *v1.NativePrePayResponse
}

var NativePrepayResult_Success_DEFAULT *v1.NativePrePayResponse

func (p *NativePrepayResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *NativePrepayResult) Unmarshal(in []byte) error {
	msg := new(v1.NativePrePayResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *NativePrepayResult) GetSuccess() *v1.NativePrePayResponse {
	if !p.IsSetSuccess() {
		return NativePrepayResult_Success_DEFAULT
	}
	return p.Success
}

func (p *NativePrepayResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.NativePrePayResponse)
}

func (p *NativePrepayResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *NativePrepayResult) GetResult() interface{} {
	return p.Success
}

func getPaymentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetPaymentRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(paymentv1.PaymentService).GetPayment(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPaymentArgs:
		success, err := handler.(paymentv1.PaymentService).GetPayment(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPaymentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPaymentArgs() interface{} {
	return &GetPaymentArgs{}
}

func newGetPaymentResult() interface{} {
	return &GetPaymentResult{}
}

type GetPaymentArgs struct {
	Req *v1.GetPaymentRequest
}

func (p *GetPaymentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPaymentArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetPaymentRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPaymentArgs_Req_DEFAULT *v1.GetPaymentRequest

func (p *GetPaymentArgs) GetReq() *v1.GetPaymentRequest {
	if !p.IsSetReq() {
		return GetPaymentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPaymentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPaymentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPaymentResult struct {
	Success *v1.GetPaymentResponse
}

var GetPaymentResult_Success_DEFAULT *v1.GetPaymentResponse

func (p *GetPaymentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPaymentResult) Unmarshal(in []byte) error {
	msg := new(v1.GetPaymentResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPaymentResult) GetSuccess() *v1.GetPaymentResponse {
	if !p.IsSetSuccess() {
		return GetPaymentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPaymentResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetPaymentResponse)
}

func (p *GetPaymentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPaymentResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) NativePrepay(ctx context.Context, Req *v1.NativePrePayRequest) (r *v1.NativePrePayResponse, err error) {
	var _args NativePrepayArgs
	_args.Req = Req
	var _result NativePrepayResult
	if err = p.c.Call(ctx, "NativePrepay", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPayment(ctx context.Context, Req *v1.GetPaymentRequest) (r *v1.GetPaymentResponse, err error) {
	var _args GetPaymentArgs
	_args.Req = Req
	var _result GetPaymentResult
	if err = p.c.Call(ctx, "GetPayment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
