// Code generated by Kitex v0.16.1. DO NOT EDIT.

package checkoutservice

import (
	"context"
	"errors"
	checkoutv1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/checkout/v1"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/checkout/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PreviewOrder": kitex.NewMethodInfo(
		previewOrderHandler,
		newPreviewOrderArgs,
		newPreviewOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"PlaceOrder": kitex.NewMethodInfo(
		placeOrderHandler,
		newPlaceOrderArgs,
		newPlaceOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	checkoutServiceServiceInfo                = NewServiceInfo()
	checkoutServiceServiceInfoForClient       = NewServiceInfoForClient()
	checkoutServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return checkoutServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return checkoutServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return checkoutServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CheckoutService"
	handlerType := (*checkoutv1.CheckoutService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "checkout.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func previewOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.PreviewOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(checkoutv1.CheckoutService).PreviewOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PreviewOrderArgs:
		success, err := handler.(checkoutv1.CheckoutService).PreviewOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PreviewOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPreviewOrderArgs() interface{} {
	return &PreviewOrderArgs{}
}

func newPreviewOrderResult() interface{} {
	return &PreviewOrderResult{}
}

type PreviewOrderArgs struct {
	Req *v1.PreviewOrderReq
}

func (p *PreviewOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PreviewOrderArgs) Unmarshal(in []byte) error {
	msg := new(v1.PreviewOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PreviewOrderArgs_Req_DEFAULT *v1.PreviewOrderReq

func (p *PreviewOrderArgs) GetReq() *v1.PreviewOrderReq {
	if !p.IsSetReq() {
		return PreviewOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PreviewOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PreviewOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PreviewOrderResult struct {
	Success *v1.PreviewOrderResp
}

var PreviewOrderResult_Success_DEFAULT *v1.PreviewOrderResp

func (p *PreviewOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PreviewOrderResult) Unmarshal(in []byte) error {
	msg := new(v1.PreviewOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PreviewOrderResult) GetSuccess() *v1.PreviewOrderResp {
	if !p.IsSetSuccess() {
		return PreviewOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PreviewOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.PreviewOrderResp)
}

func (p *PreviewOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PreviewOrderResult) GetResult() interface{} {
	return p.Success
}

func placeOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.PlaceOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(checkoutv1.CheckoutService).PlaceOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PlaceOrderArgs:
		success, err := handler.(checkoutv1.CheckoutService).PlaceOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PlaceOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPlaceOrderArgs() interface{} {
	return &PlaceOrderArgs{}
}

func newPlaceOrderResult() interface{} {
	return &PlaceOrderResult{}
}

type PlaceOrderArgs struct {
	Req *v1.PlaceOrderReq
}

func (p *PlaceOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PlaceOrderArgs) Unmarshal(in []byte) error {
	msg := new(v1.PlaceOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PlaceOrderArgs_Req_DEFAULT *v1.PlaceOrderReq

func (p *PlaceOrderArgs) GetReq() *v1.PlaceOrderReq {
	if !p.IsSetReq() {
		return PlaceOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PlaceOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PlaceOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PlaceOrderResult struct {
	Success *v1.PlaceOrderResp
}

var PlaceOrderResult_Success_DEFAULT *v1.PlaceOrderResp

func (p *PlaceOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PlaceOrderResult) Unmarshal(in []byte) error {
	msg := new(v1.PlaceOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PlaceOrderResult) GetSuccess() *v1.PlaceOrderResp {
	if !p.IsSetSuccess() {
		return PlaceOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PlaceOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.PlaceOrderResp)
}

func (p *PlaceOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PlaceOrderResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PreviewOrder(ctx context.Context, Req *v1.PreviewOrderReq) (r *v1.PreviewOrderResp, err error) {
	var _args PreviewOrderArgs
	_args.Req = Req
	var _result PreviewOrderResult
	if err = p.c.Call(ctx, "PreviewOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PlaceOrder(ctx context.Context, Req *v1.PlaceOrderReq) (r *v1.PlaceOrderResp, err error) {
	var _args PlaceOrderArgs
	_args.Req = Req
	var _result PlaceOrderResult
	if err = p.c.Call(ctx, "PlaceOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
