// Code generated by Kitex v0.16.1. DO NOT EDIT.

package checkoutservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/checkout/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PreviewOrder(ctx context.Context, Req *v1.PreviewOrderReq, callOptions ...callopt.Option) (r *v1.PreviewOrderResp, err error)
	PlaceOrder(ctx context.Context, Req *v1.PlaceOrderReq, callOptions ...callopt.Option) (r *v1.PlaceOrderResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCheckoutServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCheckoutServiceClient struct {
	*kClient
}

func (p *kCheckoutServiceClient) PreviewOrder(ctx context.Context, Req *v1.PreviewOrderReq, callOptions ...callopt.Option) (r *v1.PreviewOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PreviewOrder(ctx, Req)
}

func (p *kCheckoutServiceClient) PlaceOrder(ctx context.Context, Req *v1.PlaceOrderReq, callOptions ...callopt.Option) (r *v1.PlaceOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PlaceOrder(ctx, Req)
}
