// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/user/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Signup(ctx context.Context, Req *v1.SignupReq, callOptions ...callopt.Option) (r *v1.SignupResp, err error)
	Login(ctx context.Context, Req *v1.LoginReq, callOptions ...callopt.Option) (r *v1.LoginResp, err error)
	UpdateProfile(ctx context.Context, Req *v1.UpdateProfileReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	ChangePassword(ctx context.Context, Req *v1.ChangePasswordReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	ChangeEmail(ctx context.Context, Req *v1.ChangeEmailReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	ChangePhone(ctx context.Context, Req *v1.ChangePhoneReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	Delete(ctx context.Context, Req *v1.DeleteUserReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	Query(ctx context.Context, Req *v1.QueryUserReq, callOptions ...callopt.Option) (r *v1.QueryUserResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Signup(ctx context.Context, Req *v1.SignupReq, callOptions ...callopt.Option) (r *v1.SignupResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Signup(ctx, Req)
}

func (p *kUserServiceClient) Login(ctx context.Context, Req *v1.LoginReq, callOptions ...callopt.Option) (r *v1.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kUserServiceClient) UpdateProfile(ctx context.Context, Req *v1.UpdateProfileReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProfile(ctx, Req)
}

func (p *kUserServiceClient) ChangePassword(ctx context.Context, Req *v1.ChangePasswordReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePassword(ctx, Req)
}

func (p *kUserServiceClient) ChangeEmail(ctx context.Context, Req *v1.ChangeEmailReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeEmail(ctx, Req)
}

func (p *kUserServiceClient) ChangePhone(ctx context.Context, Req *v1.ChangePhoneReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePhone(ctx, Req)
}

func (p *kUserServiceClient) Delete(ctx context.Context, Req *v1.DeleteUserReq, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, Req)
}

func (p *kUserServiceClient) Query(ctx context.Context, Req *v1.QueryUserReq, callOptions ...callopt.Option) (r *v1.QueryUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Query(ctx, Req)
}


