// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	userv1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/user/v1"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/user/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Signup": kitex.NewMethodInfo(
		signupHandler,
		newSignupArgs,
		newSignupResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newLoginArgs,
		newLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdateProfile": kitex.NewMethodInfo(
		updateProfileHandler,
		newUpdateProfileArgs,
		newUpdateProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ChangePassword": kitex.NewMethodInfo(
		changePasswordHandler,
		newChangePasswordArgs,
		newChangePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ChangeEmail": kitex.NewMethodInfo(
		changeEmailHandler,
		newChangeEmailArgs,
		newChangeEmailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ChangePhone": kitex.NewMethodInfo(
		changePhoneHandler,
		newChangePhoneArgs,
		newChangePhoneResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Delete": kitex.NewMethodInfo(
		deleteHandler,
		newDeleteArgs,
		newDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Query": kitex.NewMethodInfo(
		queryHandler,
		newQueryArgs,
		newQueryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*userv1.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func signupHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.SignupReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userv1.UserService).Signup(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SignupArgs:
		success, err := handler.(userv1.UserService).Signup(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SignupResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSignupArgs() interface{} {
	return &SignupArgs{}
}

func newSignupResult() interface{} {
	return &SignupResult{}
}

type SignupArgs struct {
	Req *v1.SignupReq
}

func (p *SignupArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SignupArgs) Unmarshal(in []byte) error {
	msg := new(v1.SignupReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SignupArgs_Req_DEFAULT *v1.SignupReq

func (p *SignupArgs) GetReq() *v1.SignupReq {
	if !p.IsSetReq() {
		return SignupArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SignupArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SignupArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SignupResult struct {
	Success *v1.SignupResp
}

var SignupResult_Success_DEFAULT *v1.SignupResp

func (p *SignupResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SignupResult) Unmarshal(in []byte) error {
	msg := new(v1.SignupResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SignupResult) GetSuccess() *v1.SignupResp {
	if !p.IsSetSuccess() {
		return SignupResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SignupResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.SignupResp)
}

func (p *SignupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SignupResult) GetResult() interface{} {
	return p.Success
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.LoginReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userv1.UserService).Login(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LoginArgs:
		success, err := handler.(userv1.UserService).Login(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LoginResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLoginArgs() interface{} {
	return &LoginArgs{}
}

func newLoginResult() interface{} {
	return &LoginResult{}
}

type LoginArgs struct {
	Req *v1.LoginReq
}

func (p *LoginArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LoginArgs) Unmarshal(in []byte) error {
	msg := new(v1.LoginReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LoginArgs_Req_DEFAULT *v1.LoginReq

func (p *LoginArgs) GetReq() *v1.LoginReq {
	if !p.IsSetReq() {
		return LoginArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LoginArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LoginResult struct {
	Success *v1.LoginResp
}

var LoginResult_Success_DEFAULT *v1.LoginResp

func (p *LoginResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LoginResult) Unmarshal(in []byte) error {
	msg := new(v1.LoginResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LoginResult) GetSuccess() *v1.LoginResp {
	if !p.IsSetSuccess() {
		return LoginResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.LoginResp)
}

func (p *LoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LoginResult) GetResult() interface{} {
	return p.Success
}

func updateProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.UpdateProfileReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userv1.UserService).UpdateProfile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdateProfileArgs:
		success, err := handler.(userv1.UserService).UpdateProfile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdateProfileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdateProfileArgs() interface{} {
	return &UpdateProfileArgs{}
}

func newUpdateProfileResult() interface{} {
	return &UpdateProfileResult{}
}

type UpdateProfileArgs struct {
	Req *v1.UpdateProfileReq
}

func (p *UpdateProfileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdateProfileArgs) Unmarshal(in []byte) error {
	msg := new(v1.UpdateProfileReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdateProfileArgs_Req_DEFAULT *v1.UpdateProfileReq

func (p *UpdateProfileArgs) GetReq() *v1.UpdateProfileReq {
	if !p.IsSetReq() {
		return UpdateProfileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdateProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdateProfileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdateProfileResult struct {
	Success *emptypb.Empty
}

var UpdateProfileResult_Success_DEFAULT *emptypb.Empty

func (p *UpdateProfileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdateProfileResult) Unmarshal(in []byte) error {
	msg := new(emptypb.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdateProfileResult) GetSuccess() *emptypb.Empty {
	if !p.IsSetSuccess() {
		return UpdateProfileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdateProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*emptypb.Empty)
}

func (p *UpdateProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdateProfileResult) GetResult() interface{} {
	return p.Success
}

func changePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ChangePasswordReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userv1.UserService).ChangePassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ChangePasswordArgs:
		success, err := handler.(userv1.UserService).ChangePassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ChangePasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newChangePasswordArgs() interface{} {
	return &ChangePasswordArgs{}
}

func newChangePasswordResult() interface{} {
	return &ChangePasswordResult{}
}

type ChangePasswordArgs struct {
	Req *v1.ChangePasswordReq
}

func (p *ChangePasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ChangePasswordArgs) Unmarshal(in []byte) error {
	msg := new(v1.ChangePasswordReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ChangePasswordArgs_Req_DEFAULT *v1.ChangePasswordReq

func (p *ChangePasswordArgs) GetReq() *v1.ChangePasswordReq {
	if !p.IsSetReq() {
		return ChangePasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ChangePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChangePasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ChangePasswordResult struct {
	Success *emptypb.Empty
}

var ChangePasswordResult_Success_DEFAULT *emptypb.Empty

func (p *ChangePasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ChangePasswordResult) Unmarshal(in []byte) error {
	msg := new(emptypb.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ChangePasswordResult) GetSuccess() *emptypb.Empty {
	if !p.IsSetSuccess() {
		return ChangePasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ChangePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*emptypb.Empty)
}

func (p *ChangePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChangePasswordResult) GetResult() interface{} {
	return p.Success
}

func changeEmailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ChangeEmailReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userv1.UserService).ChangeEmail(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ChangeEmailArgs:
		success, err := handler.(userv1.UserService).ChangeEmail(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ChangeEmailResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newChangeEmailArgs() interface{} {
	return &ChangeEmailArgs{}
}

func newChangeEmailResult() interface{} {
	return &ChangeEmailResult{}
}

type ChangeEmailArgs struct {
	Req *v1.ChangeEmailReq
}

func (p *ChangeEmailArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ChangeEmailArgs) Unmarshal(in []byte) error {
	msg := new(v1.ChangeEmailReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ChangeEmailArgs_Req_DEFAULT *v1.ChangeEmailReq

func (p *ChangeEmailArgs) GetReq() *v1.ChangeEmailReq {
	if !p.IsSetReq() {
		return ChangeEmailArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ChangeEmailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChangeEmailArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ChangeEmailResult struct {
	Success *emptypb.Empty
}

var ChangeEmailResult_Success_DEFAULT *emptypb.Empty

func (p *ChangeEmailResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ChangeEmailResult) Unmarshal(in []byte) error {
	msg := new(emptypb.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ChangeEmailResult) GetSuccess() *emptypb.Empty {
	if !p.IsSetSuccess() {
		return ChangeEmailResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ChangeEmailResult) SetSuccess(x interface{}) {
	p.Success = x.(*emptypb.Empty)
}

func (p *ChangeEmailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChangeEmailResult) GetResult() interface{} {
	return p.Success
}

func changePhoneHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ChangePhoneReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userv1.UserService).ChangePhone(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ChangePhoneArgs:
		success, err := handler.(userv1.UserService).ChangePhone(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ChangePhoneResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newChangePhoneArgs() interface{} {
	return &ChangePhoneArgs{}
}

func newChangePhoneResult() interface{} {
	return &ChangePhoneResult{}
}

type ChangePhoneArgs struct {
	Req *v1.ChangePhoneReq
}

func (p *ChangePhoneArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ChangePhoneArgs) Unmarshal(in []byte) error {
	msg := new(v1.ChangePhoneReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ChangePhoneArgs_Req_DEFAULT *v1.ChangePhoneReq

func (p *ChangePhoneArgs) GetReq() *v1.ChangePhoneReq {
	if !p.IsSetReq() {
		return ChangePhoneArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ChangePhoneArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ChangePhoneArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ChangePhoneResult struct {
	Success *emptypb.Empty
}

var ChangePhoneResult_Success_DEFAULT *emptypb.Empty

func (p *ChangePhoneResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ChangePhoneResult) Unmarshal(in []byte) error {
	msg := new(emptypb.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ChangePhoneResult) GetSuccess() *emptypb.Empty {
	if !p.IsSetSuccess() {
		return ChangePhoneResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ChangePhoneResult) SetSuccess(x interface{}) {
	p.Success = x.(*emptypb.Empty)
}

func (p *ChangePhoneResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ChangePhoneResult) GetResult() interface{} {
	return p.Success
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.DeleteUserReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userv1.UserService).Delete(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteArgs:
		success, err := handler.(userv1.UserService).Delete(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteArgs() interface{} {
	return &DeleteArgs{}
}

func newDeleteResult() interface{} {
	return &DeleteResult{}
}

type DeleteArgs struct {
	Req *v1.DeleteUserReq
}

func (p *DeleteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteArgs) Unmarshal(in []byte) error {
	msg := new(v1.DeleteUserReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteArgs_Req_DEFAULT *v1.DeleteUserReq

func (p *DeleteArgs) GetReq() *v1.DeleteUserReq {
	if !p.IsSetReq() {
		return DeleteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteResult struct {
	Success *emptypb.Empty
}

var DeleteResult_Success_DEFAULT *emptypb.Empty

func (p *DeleteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteResult) Unmarshal(in []byte) error {
	msg := new(emptypb.Empty)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteResult) GetSuccess() *emptypb.Empty {
	if !p.IsSetSuccess() {
		return DeleteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*emptypb.Empty)
}

func (p *DeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteResult) GetResult() interface{} {
	return p.Success
}

func queryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.QueryUserReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userv1.UserService).Query(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *QueryArgs:
		success, err := handler.(userv1.UserService).Query(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newQueryArgs() interface{} {
	return &QueryArgs{}
}

func newQueryResult() interface{} {
	return &QueryResult{}
}

type QueryArgs struct {
	Req *v1.QueryUserReq
}

func (p *QueryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *QueryArgs) Unmarshal(in []byte) error {
	msg := new(v1.QueryUserReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryArgs_Req_DEFAULT *v1.QueryUserReq

func (p *QueryArgs) GetReq() *v1.QueryUserReq {
	if !p.IsSetReq() {
		return QueryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QueryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QueryResult struct {
	Success *v1.QueryUserResp
}

var QueryResult_Success_DEFAULT *v1.QueryUserResp

func (p *QueryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *QueryResult) Unmarshal(in []byte) error {
	msg := new(v1.QueryUserResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryResult) GetSuccess() *v1.QueryUserResp {
	if !p.IsSetSuccess() {
		return QueryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.QueryUserResp)
}

func (p *QueryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QueryResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Signup(ctx context.Context, Req *v1.SignupReq) (r *v1.SignupResp, err error) {
	var _args SignupArgs
	_args.Req = Req
	var _result SignupResult
	if err = p.c.Call(ctx, "Signup", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, Req *v1.LoginReq) (r *v1.LoginResp, err error) {
	var _args LoginArgs
	_args.Req = Req
	var _result LoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProfile(ctx context.Context, Req *v1.UpdateProfileReq) (r *emptypb.Empty, err error) {
	var _args UpdateProfileArgs
	_args.Req = Req
	var _result UpdateProfileResult
	if err = p.c.Call(ctx, "UpdateProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePassword(ctx context.Context, Req *v1.ChangePasswordReq) (r *emptypb.Empty, err error) {
	var _args ChangePasswordArgs
	_args.Req = Req
	var _result ChangePasswordResult
	if err = p.c.Call(ctx, "ChangePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeEmail(ctx context.Context, Req *v1.ChangeEmailReq) (r *emptypb.Empty, err error) {
	var _args ChangeEmailArgs
	_args.Req = Req
	var _result ChangeEmailResult
	if err = p.c.Call(ctx, "ChangeEmail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePhone(ctx context.Context, Req *v1.ChangePhoneReq) (r *emptypb.Empty, err error) {
	var _args ChangePhoneArgs
	_args.Req = Req
	var _result ChangePhoneResult
	if err = p.c.Call(ctx, "ChangePhone", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, Req *v1.DeleteUserReq) (r *emptypb.Empty, err error) {
	var _args DeleteArgs
	_args.Req = Req
	var _result DeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Query(ctx context.Context, Req *v1.QueryUserReq) (r *v1.QueryUserResp, err error) {
	var _args QueryArgs
	_args.Req = Req
	var _result QueryResult
	if err = p.c.Call(ctx, "Query", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
