// Code generated by Kitex v0.15.4. DO NOT EDIT.

package couponservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/coupon/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListUserCoupons(ctx context.Context, Req *v1.ListUserCouponsReq, callOptions ...callopt.Option) (r *v1.ListUserCouponsResp, err error)
	ListAvailableCoupons(ctx context.Context, Req *v1.ListAvailableCouponsReq, callOptions ...callopt.Option) (r *v1.ListAvailableCouponsResp, err error)
	ReserveCoupon(ctx context.Context, Req *v1.ReserveCouponReq, callOptions ...callopt.Option) (r *v1.ReserveCouponResp, err error)
	CommitCoupon(ctx context.Context, Req *v1.CommitCouponReq, callOptions ...callopt.Option) (r *v1.CommitCouponResp, err error)
	ReleaseCoupon(ctx context.Context, Req *v1.ReleaseCouponReq, callOptions ...callopt.Option) (r *v1.ReleaseCouponResp, err error)
	RefundCoupon(ctx context.Context, Req *v1.RefundCouponReq, callOptions ...callopt.Option) (r *v1.RefundCouponResp, err error)
	CreateCouponTemplate(ctx context.Context, Req *v1.CreateCouponTemplateReq, callOptions ...callopt.Option) (r *v1.CreateCouponTemplateResp, err error)
	IssueCoupon(ctx context.Context, Req *v1.IssueCouponReq, callOptions ...callopt.Option) (r *v1.IssueCouponResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCouponServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCouponServiceClient struct {
	*kClient
}

func (p *kCouponServiceClient) ListUserCoupons(ctx context.Context, Req *v1.ListUserCouponsReq, callOptions ...callopt.Option) (r *v1.ListUserCouponsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUserCoupons(ctx, Req)
}

func (p *kCouponServiceClient) ListAvailableCoupons(ctx context.Context, Req *v1.ListAvailableCouponsReq, callOptions ...callopt.Option) (r *v1.ListAvailableCouponsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAvailableCoupons(ctx, Req)
}

func (p *kCouponServiceClient) ReserveCoupon(ctx context.Context, Req *v1.ReserveCouponReq, callOptions ...callopt.Option) (r *v1.ReserveCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReserveCoupon(ctx, Req)
}

func (p *kCouponServiceClient) CommitCoupon(ctx context.Context, Req *v1.CommitCouponReq, callOptions ...callopt.Option) (r *v1.CommitCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommitCoupon(ctx, Req)
}

func (p *kCouponServiceClient) ReleaseCoupon(ctx context.Context, Req *v1.ReleaseCouponReq, callOptions ...callopt.Option) (r *v1.ReleaseCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReleaseCoupon(ctx, Req)
}

func (p *kCouponServiceClient) RefundCoupon(ctx context.Context, Req *v1.RefundCouponReq, callOptions ...callopt.Option) (r *v1.RefundCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundCoupon(ctx, Req)
}

func (p *kCouponServiceClient) CreateCouponTemplate(ctx context.Context, Req *v1.CreateCouponTemplateReq, callOptions ...callopt.Option) (r *v1.CreateCouponTemplateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCouponTemplate(ctx, Req)
}

func (p *kCouponServiceClient) IssueCoupon(ctx context.Context, Req *v1.IssueCouponReq, callOptions ...callopt.Option) (r *v1.IssueCouponResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.IssueCoupon(ctx, Req)
}
