// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/inventory/infra/cache"
	"github.com/XDWow/DouyinMall/backend/internal/inventory/infra/mq"
	"github.com/XDWow/DouyinMall/backend/internal/inventory/infra/repository"
	"github.com/XDWow/DouyinMall/backend/internal/inventory/ioc"
	transportgrpc "github.com/XDWow/DouyinMall/backend/internal/inventory/transport/grpc"
	"github.com/XDWow/DouyinMall/backend/internal/inventory/usecase"
	"github.com/cloudwego/kitex/server"
)

func InitApp() *App {
	db := ioc.InitDB()
	cmdable := ioc.InitRedis()
	inventoryCache := cache.NewRedisInventoryCache(cmdable)
	loggerV1 := ioc.InitLogger()
	inventoryRepository := repository.NewGormInventoryRepository(db, inventoryCache, loggerV1)
	reserveStockUsecase := usecase.NewReserveStockUsecase(inventoryRepository, loggerV1)
	commitStockUseCase := usecase.NewCommitStockUseCase(inventoryRepository, loggerV1)
	refundStockUseCase := usecase.NewRefundStockUseCase(inventoryRepository, loggerV1)
	releaseStockUseCase := usecase.NewReleaseStockUseCase(inventoryRepository, loggerV1)
	client := ioc.InitKafkaClient()
	syncProducer := ioc.InitKafkaSyncProducer(client)
	orderClient := ioc.InitOrderClient()
	orderConsumer := mq.NewOrderConsumer(client, syncProducer, releaseStockUseCase, refundStockUseCase, orderClient, loggerV1)
	inventoryHandler := transportgrpc.NewInventoryHandler(reserveStockUsecase, commitStockUseCase, releaseStockUseCase, refundStockUseCase, inventoryRepository)
	grpcServer := ioc.InitGRPCServer(inventoryHandler)
	return &App{
		GRPCServer:    grpcServer,
		OrderConsumer: orderConsumer,
	}
}

type App struct {
	GRPCServer    server.Server
	OrderConsumer *mq.OrderConsumer
}
