db:
  host: "134.175.67.79"
  port: 3306
  user: "root"
  password: ""
  database: "douyinmall"
  params: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "106.52.154.235:6379"

etcd:
  endpoints:
    - "42.193.160.221:2379"

grpc:
  server:
    name: user-service
    port: 8091
    etcdTTL: 60
