db:
  host: "douyinmall-mysql"
  port: 3306
  user: "root"
  password: ""
  database: "douyinmall"
  params: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "douyinmall-redis:6379"

etcd:
  endpoints:
    - "douyinmall-etcd:2379"

grpc:
  server:
    name: user-service
    port: 8091
    etcdTTL: 60
