http:
  addr: ":8080"

jwt:
  access_secret: "douyinmall-access-secret-dev"
  refresh_secret: "douyinmall-refresh-secret-dev"
  access_expiry: "2h"
  refresh_expiry: "168h"

redis:
  addr: "127.0.0.1:16379"

ratelimit:
  interval: "1m"
  rate: 100000

etcd:
  endpoints:
    - "127.0.0.1:12379"

rpc:
  agent:
    service_name: "agent-service"
    direct_addr: "127.0.0.1:8087"
  user:
    service_name: "user-service"
    direct_addr: "127.0.0.1:8091"
  checkout:
    service_name: "checkout-service"
    direct_addr: "127.0.0.1:8086"
  seckill:
    service_name: "seckill-service"
    direct_addr: "127.0.0.1:8098"
  order:
    service_name: "order-service"
    direct_addr: "127.0.0.1:8095"
  product:
    service_name: "product-service"
    direct_addr: "127.0.0.1:8096"
  inventory:
    service_name: "inventory-service"
    direct_addr: "127.0.0.1:8094"
