http:
  addr: ":8080"

jwt:
  access_secret: ""
  refresh_secret: ""
  access_expiry: "2h"
  refresh_expiry: "168h"

redis:
  addr: "106.52.154.235:6379"

ratelimit:
  interval: "1m"
  rate: 100000

etcd:
  endpoints:
    - "42.193.160.221:2379"

rpc:
  agent:
    service_name: "agent-service"
    direct_addr: "agent-service:8087"
  user:
    service_name: "user-service"
    direct_addr: "user-service:8091"
