// Code generated by Kitex v0.15.4. DO NOT EDIT.

package productservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/product/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListProducts(ctx context.Context, Req *v1.ListProductsReq, callOptions ...callopt.Option) (r *v1.ListProductsResp, err error)
	GetProducts(ctx context.Context, Req *v1.GetProductsReq, callOptions ...callopt.Option) (r *v1.GetProductsResp, err error)
	GetProductQuotes(ctx context.Context, Req *v1.GetProductQuotesReq, callOptions ...callopt.Option) (r *v1.GetProductQuotesResp, err error)
	CreateProduct(ctx context.Context, Req *v1.CreateProductReq, callOptions ...callopt.Option) (r *v1.CreateProductResp, err error)
	UpdateProduct(ctx context.Context, Req *v1.UpdateProductReq, callOptions ...callopt.Option) (r *v1.UpdateProductResp, err error)
	DeleteProduct(ctx context.Context, Req *v1.DeleteProductReq, callOptions ...callopt.Option) (r *v1.DeleteProductResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kProductServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kProductServiceClient struct {
	*kClient
}

func (p *kProductServiceClient) ListProducts(ctx context.Context, Req *v1.ListProductsReq, callOptions ...callopt.Option) (r *v1.ListProductsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListProducts(ctx, Req)
}

func (p *kProductServiceClient) GetProducts(ctx context.Context, Req *v1.GetProductsReq, callOptions ...callopt.Option) (r *v1.GetProductsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProducts(ctx, Req)
}

func (p *kProductServiceClient) GetProductQuotes(ctx context.Context, Req *v1.GetProductQuotesReq, callOptions ...callopt.Option) (r *v1.GetProductQuotesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProductQuotes(ctx, Req)
}

func (p *kProductServiceClient) CreateProduct(ctx context.Context, Req *v1.CreateProductReq, callOptions ...callopt.Option) (r *v1.CreateProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateProduct(ctx, Req)
}

func (p *kProductServiceClient) UpdateProduct(ctx context.Context, Req *v1.UpdateProductReq, callOptions ...callopt.Option) (r *v1.UpdateProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProduct(ctx, Req)
}

func (p *kProductServiceClient) DeleteProduct(ctx context.Context, Req *v1.DeleteProductReq, callOptions ...callopt.Option) (r *v1.DeleteProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteProduct(ctx, Req)
}
