// Code generated by Kitex v0.15.4. DO NOT EDIT.

package inventoryservice

import (
	"context"

	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/inventory/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

type Client interface {
	GetInventory(ctx context.Context, req *v1.GetInventoryReq, callOptions ...callopt.Option) (r *v1.GetInventoryResp, err error)
	BatchGetInventory(ctx context.Context, req *v1.BatchGetInventoryReq, callOptions ...callopt.Option) (r *v1.BatchGetInventoryResp, err error)
	CommitStock(ctx context.Context, req *v1.CommitStockReq, callOptions ...callopt.Option) (r *v1.InventoryOpResp, err error)
	RefundStock(ctx context.Context, req *v1.RefundStockReq, callOptions ...callopt.Option) (r *v1.InventoryOpResp, err error)
	AdjustStock(ctx context.Context, req *v1.AdjustStockReq, callOptions ...callopt.Option) (r *v1.InventoryOpResp, err error)
}

func NewClient(destService string, opts ...client.Option) (Client, error) {
	options := append([]client.Option{client.WithDestService(destService)}, opts...)
	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kInventoryServiceClient{kClient: newServiceClient(kc)}, nil
}

func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInventoryServiceClient struct {
	*kClient
}

func (p *kInventoryServiceClient) GetInventory(ctx context.Context, req *v1.GetInventoryReq, callOptions ...callopt.Option) (r *v1.GetInventoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetInventory(ctx, req)
}

func (p *kInventoryServiceClient) BatchGetInventory(ctx context.Context, req *v1.BatchGetInventoryReq, callOptions ...callopt.Option) (r *v1.BatchGetInventoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetInventory(ctx, req)
}

func (p *kInventoryServiceClient) CommitStock(ctx context.Context, req *v1.CommitStockReq, callOptions ...callopt.Option) (r *v1.InventoryOpResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommitStock(ctx, req)
}

func (p *kInventoryServiceClient) RefundStock(ctx context.Context, req *v1.RefundStockReq, callOptions ...callopt.Option) (r *v1.InventoryOpResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefundStock(ctx, req)
}

func (p *kInventoryServiceClient) AdjustStock(ctx context.Context, req *v1.AdjustStockReq, callOptions ...callopt.Option) (r *v1.InventoryOpResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdjustStock(ctx, req)
}
