// Code generated by Kitex v0.15.4. DO NOT EDIT.

package inventoryservice

import (
	"context"
	"errors"
	inventoryv1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/inventory/v1"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/inventory/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetInventory": kitex.NewMethodInfo(
		getInventoryHandler,
		newGetInventoryArgs,
		newGetInventoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchGetInventory": kitex.NewMethodInfo(
		batchGetInventoryHandler,
		newBatchGetInventoryArgs,
		newBatchGetInventoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ReserveStock": kitex.NewMethodInfo(
		reserveStockHandler,
		newReserveStockArgs,
		newReserveStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CommitStock": kitex.NewMethodInfo(
		commitStockHandler,
		newCommitStockArgs,
		newCommitStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ReleaseStock": kitex.NewMethodInfo(
		releaseStockHandler,
		newReleaseStockArgs,
		newReleaseStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"RefundStock": kitex.NewMethodInfo(
		refundStockHandler,
		newRefundStockArgs,
		newRefundStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AdjustStock": kitex.NewMethodInfo(
		adjustStockHandler,
		newAdjustStockArgs,
		newAdjustStockResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	inventoryServiceServiceInfo                = NewServiceInfo()
	inventoryServiceServiceInfoForClient       = NewServiceInfoForClient()
	inventoryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return inventoryServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return inventoryServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return inventoryServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InventoryService"
	handlerType := (*inventoryv1.InventoryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "inventory.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getInventoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetInventoryReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(inventoryv1.InventoryService).GetInventory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetInventoryArgs:
		success, err := handler.(inventoryv1.InventoryService).GetInventory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetInventoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetInventoryArgs() interface{} {
	return &GetInventoryArgs{}
}

func newGetInventoryResult() interface{} {
	return &GetInventoryResult{}
}

type GetInventoryArgs struct {
	Req *v1.GetInventoryReq
}

func (p *GetInventoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetInventoryArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetInventoryReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetInventoryArgs_Req_DEFAULT *v1.GetInventoryReq

func (p *GetInventoryArgs) GetReq() *v1.GetInventoryReq {
	if !p.IsSetReq() {
		return GetInventoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetInventoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetInventoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetInventoryResult struct {
	Success *v1.GetInventoryResp
}

var GetInventoryResult_Success_DEFAULT *v1.GetInventoryResp

func (p *GetInventoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetInventoryResult) Unmarshal(in []byte) error {
	msg := new(v1.GetInventoryResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetInventoryResult) GetSuccess() *v1.GetInventoryResp {
	if !p.IsSetSuccess() {
		return GetInventoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetInventoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetInventoryResp)
}

func (p *GetInventoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetInventoryResult) GetResult() interface{} {
	return p.Success
}

func batchGetInventoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.BatchGetInventoryReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(inventoryv1.InventoryService).BatchGetInventory(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchGetInventoryArgs:
		success, err := handler.(inventoryv1.InventoryService).BatchGetInventory(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchGetInventoryResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchGetInventoryArgs() interface{} {
	return &BatchGetInventoryArgs{}
}

func newBatchGetInventoryResult() interface{} {
	return &BatchGetInventoryResult{}
}

type BatchGetInventoryArgs struct {
	Req *v1.BatchGetInventoryReq
}

func (p *BatchGetInventoryArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchGetInventoryArgs) Unmarshal(in []byte) error {
	msg := new(v1.BatchGetInventoryReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchGetInventoryArgs_Req_DEFAULT *v1.BatchGetInventoryReq

func (p *BatchGetInventoryArgs) GetReq() *v1.BatchGetInventoryReq {
	if !p.IsSetReq() {
		return BatchGetInventoryArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchGetInventoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchGetInventoryArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchGetInventoryResult struct {
	Success *v1.BatchGetInventoryResp
}

var BatchGetInventoryResult_Success_DEFAULT *v1.BatchGetInventoryResp

func (p *BatchGetInventoryResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchGetInventoryResult) Unmarshal(in []byte) error {
	msg := new(v1.BatchGetInventoryResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchGetInventoryResult) GetSuccess() *v1.BatchGetInventoryResp {
	if !p.IsSetSuccess() {
		return BatchGetInventoryResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchGetInventoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.BatchGetInventoryResp)
}

func (p *BatchGetInventoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchGetInventoryResult) GetResult() interface{} {
	return p.Success
}

func reserveStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ReserveStockReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(inventoryv1.InventoryService).ReserveStock(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ReserveStockArgs:
		success, err := handler.(inventoryv1.InventoryService).ReserveStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ReserveStockResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newReserveStockArgs() interface{} {
	return &ReserveStockArgs{}
}

func newReserveStockResult() interface{} {
	return &ReserveStockResult{}
}

type ReserveStockArgs struct {
	Req *v1.ReserveStockReq
}

func (p *ReserveStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ReserveStockArgs) Unmarshal(in []byte) error {
	msg := new(v1.ReserveStockReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ReserveStockArgs_Req_DEFAULT *v1.ReserveStockReq

func (p *ReserveStockArgs) GetReq() *v1.ReserveStockReq {
	if !p.IsSetReq() {
		return ReserveStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ReserveStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ReserveStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ReserveStockResult struct {
	Success *v1.InventoryOpResp
}

var ReserveStockResult_Success_DEFAULT *v1.InventoryOpResp

func (p *ReserveStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ReserveStockResult) Unmarshal(in []byte) error {
	msg := new(v1.InventoryOpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ReserveStockResult) GetSuccess() *v1.InventoryOpResp {
	if !p.IsSetSuccess() {
		return ReserveStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ReserveStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.InventoryOpResp)
}

func (p *ReserveStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ReserveStockResult) GetResult() interface{} {
	return p.Success
}

func commitStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CommitStockReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(inventoryv1.InventoryService).CommitStock(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CommitStockArgs:
		success, err := handler.(inventoryv1.InventoryService).CommitStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CommitStockResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCommitStockArgs() interface{} {
	return &CommitStockArgs{}
}

func newCommitStockResult() interface{} {
	return &CommitStockResult{}
}

type CommitStockArgs struct {
	Req *v1.CommitStockReq
}

func (p *CommitStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CommitStockArgs) Unmarshal(in []byte) error {
	msg := new(v1.CommitStockReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CommitStockArgs_Req_DEFAULT *v1.CommitStockReq

func (p *CommitStockArgs) GetReq() *v1.CommitStockReq {
	if !p.IsSetReq() {
		return CommitStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CommitStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CommitStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CommitStockResult struct {
	Success *v1.InventoryOpResp
}

var CommitStockResult_Success_DEFAULT *v1.InventoryOpResp

func (p *CommitStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CommitStockResult) Unmarshal(in []byte) error {
	msg := new(v1.InventoryOpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CommitStockResult) GetSuccess() *v1.InventoryOpResp {
	if !p.IsSetSuccess() {
		return CommitStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CommitStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.InventoryOpResp)
}

func (p *CommitStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CommitStockResult) GetResult() interface{} {
	return p.Success
}

func releaseStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ReleaseStockReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(inventoryv1.InventoryService).ReleaseStock(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ReleaseStockArgs:
		success, err := handler.(inventoryv1.InventoryService).ReleaseStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ReleaseStockResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newReleaseStockArgs() interface{} {
	return &ReleaseStockArgs{}
}

func newReleaseStockResult() interface{} {
	return &ReleaseStockResult{}
}

type ReleaseStockArgs struct {
	Req *v1.ReleaseStockReq
}

func (p *ReleaseStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ReleaseStockArgs) Unmarshal(in []byte) error {
	msg := new(v1.ReleaseStockReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ReleaseStockArgs_Req_DEFAULT *v1.ReleaseStockReq

func (p *ReleaseStockArgs) GetReq() *v1.ReleaseStockReq {
	if !p.IsSetReq() {
		return ReleaseStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ReleaseStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ReleaseStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ReleaseStockResult struct {
	Success *v1.InventoryOpResp
}

var ReleaseStockResult_Success_DEFAULT *v1.InventoryOpResp

func (p *ReleaseStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ReleaseStockResult) Unmarshal(in []byte) error {
	msg := new(v1.InventoryOpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ReleaseStockResult) GetSuccess() *v1.InventoryOpResp {
	if !p.IsSetSuccess() {
		return ReleaseStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ReleaseStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.InventoryOpResp)
}

func (p *ReleaseStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ReleaseStockResult) GetResult() interface{} {
	return p.Success
}

func refundStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.RefundStockReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(inventoryv1.InventoryService).RefundStock(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *RefundStockArgs:
		success, err := handler.(inventoryv1.InventoryService).RefundStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*RefundStockResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newRefundStockArgs() interface{} {
	return &RefundStockArgs{}
}

func newRefundStockResult() interface{} {
	return &RefundStockResult{}
}

type RefundStockArgs struct {
	Req *v1.RefundStockReq
}

func (p *RefundStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *RefundStockArgs) Unmarshal(in []byte) error {
	msg := new(v1.RefundStockReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var RefundStockArgs_Req_DEFAULT *v1.RefundStockReq

func (p *RefundStockArgs) GetReq() *v1.RefundStockReq {
	if !p.IsSetReq() {
		return RefundStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *RefundStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RefundStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type RefundStockResult struct {
	Success *v1.InventoryOpResp
}

var RefundStockResult_Success_DEFAULT *v1.InventoryOpResp

func (p *RefundStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *RefundStockResult) Unmarshal(in []byte) error {
	msg := new(v1.InventoryOpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *RefundStockResult) GetSuccess() *v1.InventoryOpResp {
	if !p.IsSetSuccess() {
		return RefundStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *RefundStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.InventoryOpResp)
}

func (p *RefundStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RefundStockResult) GetResult() interface{} {
	return p.Success
}

func adjustStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.AdjustStockReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(inventoryv1.InventoryService).AdjustStock(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AdjustStockArgs:
		success, err := handler.(inventoryv1.InventoryService).AdjustStock(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AdjustStockResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAdjustStockArgs() interface{} {
	return &AdjustStockArgs{}
}

func newAdjustStockResult() interface{} {
	return &AdjustStockResult{}
}

type AdjustStockArgs struct {
	Req *v1.AdjustStockReq
}

func (p *AdjustStockArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AdjustStockArgs) Unmarshal(in []byte) error {
	msg := new(v1.AdjustStockReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AdjustStockArgs_Req_DEFAULT *v1.AdjustStockReq

func (p *AdjustStockArgs) GetReq() *v1.AdjustStockReq {
	if !p.IsSetReq() {
		return AdjustStockArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AdjustStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdjustStockArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AdjustStockResult struct {
	Success *v1.InventoryOpResp
}

var AdjustStockResult_Success_DEFAULT *v1.InventoryOpResp

func (p *AdjustStockResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AdjustStockResult) Unmarshal(in []byte) error {
	msg := new(v1.InventoryOpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AdjustStockResult) GetSuccess() *v1.InventoryOpResp {
	if !p.IsSetSuccess() {
		return AdjustStockResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AdjustStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.InventoryOpResp)
}

func (p *AdjustStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdjustStockResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetInventory(ctx context.Context, Req *v1.GetInventoryReq) (r *v1.GetInventoryResp, err error) {
	var _args GetInventoryArgs
	_args.Req = Req
	var _result GetInventoryResult
	if err = p.c.Call(ctx, "GetInventory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetInventory(ctx context.Context, Req *v1.BatchGetInventoryReq) (r *v1.BatchGetInventoryResp, err error) {
	var _args BatchGetInventoryArgs
	_args.Req = Req
	var _result BatchGetInventoryResult
	if err = p.c.Call(ctx, "BatchGetInventory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReserveStock(ctx context.Context, Req *v1.ReserveStockReq) (r *v1.InventoryOpResp, err error) {
	var _args ReserveStockArgs
	_args.Req = Req
	var _result ReserveStockResult
	if err = p.c.Call(ctx, "ReserveStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommitStock(ctx context.Context, Req *v1.CommitStockReq) (r *v1.InventoryOpResp, err error) {
	var _args CommitStockArgs
	_args.Req = Req
	var _result CommitStockResult
	if err = p.c.Call(ctx, "CommitStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ReleaseStock(ctx context.Context, Req *v1.ReleaseStockReq) (r *v1.InventoryOpResp, err error) {
	var _args ReleaseStockArgs
	_args.Req = Req
	var _result ReleaseStockResult
	if err = p.c.Call(ctx, "ReleaseStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefundStock(ctx context.Context, Req *v1.RefundStockReq) (r *v1.InventoryOpResp, err error) {
	var _args RefundStockArgs
	_args.Req = Req
	var _result RefundStockResult
	if err = p.c.Call(ctx, "RefundStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdjustStock(ctx context.Context, Req *v1.AdjustStockReq) (r *v1.InventoryOpResp, err error) {
	var _args AdjustStockArgs
	_args.Req = Req
	var _result AdjustStockResult
	if err = p.c.Call(ctx, "AdjustStock", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
