// Code generated by Kitex v0.15.4. DO NOT EDIT.

package inventoryservice

import (
	"context"
	"errors"

	inventoryv1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/inventory/v1"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/inventory/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetInventory":      kitex.NewMethodInfo(getInventoryHandler, newGetInventoryArgs, newGetInventoryResult, false, kitex.WithStreamingMode(kitex.StreamingUnary)),
	"BatchGetInventory": kitex.NewMethodInfo(batchGetInventoryHandler, newBatchGetInventoryArgs, newBatchGetInventoryResult, false, kitex.WithStreamingMode(kitex.StreamingUnary)),
	"CommitStock":       kitex.NewMethodInfo(commitStockHandler, newCommitStockArgs, newCommitStockResult, false, kitex.WithStreamingMode(kitex.StreamingUnary)),
	"RefundStock":       kitex.NewMethodInfo(refundStockHandler, newRefundStockArgs, newRefundStockResult, false, kitex.WithStreamingMode(kitex.StreamingUnary)),
	"AdjustStock":       kitex.NewMethodInfo(adjustStockHandler, newAdjustStockArgs, newAdjustStockResult, false, kitex.WithStreamingMode(kitex.StreamingUnary)),
}

var (
	inventoryServiceServiceInfo                = NewServiceInfo()
	inventoryServiceServiceInfoForClient       = NewServiceInfoForClient()
	inventoryServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

func serviceInfo() *kitex.ServiceInfo { return inventoryServiceServiceInfo }
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return inventoryServiceServiceInfoForStreamClient
}
func serviceInfoForClient() *kitex.ServiceInfo          { return inventoryServiceServiceInfoForClient }
func NewServiceInfo() *kitex.ServiceInfo                { return newServiceInfo(false, true, true) }
func NewServiceInfoForClient() *kitex.ServiceInfo       { return newServiceInfo(false, false, true) }
func NewServiceInfoForStreamClient() *kitex.ServiceInfo { return newServiceInfo(true, true, false) }

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InventoryService"
	handlerType := (*inventoryv1.InventoryService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{"PackageName": "inventory.v1"}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	return &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
}

type unaryHandler[Req any, Resp any] func(context.Context, inventoryv1.InventoryService, *Req) (*Resp, error)

func handleUnary[Req any, Resp any](ctx context.Context, handler interface{}, arg interface{}, result interface{}, call unaryHandler[Req, Resp], set func(interface{}, *Resp)) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(Req)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := call(ctx, handler.(inventoryv1.InventoryService), req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	default:
		return errInvalidMessageType
	case interface{ GetReq() *Req }:
		success, err := call(ctx, handler.(inventoryv1.InventoryService), s.GetReq())
		if err != nil {
			return err
		}
		set(result, success)
		return nil
	}
}

func getInventoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	return handleUnary(ctx, handler, arg, result, func(ctx context.Context, h inventoryv1.InventoryService, req *v1.GetInventoryReq) (*v1.GetInventoryResp, error) {
		return h.GetInventory(ctx, req)
	}, func(result interface{}, success *v1.GetInventoryResp) { result.(*GetInventoryResult).Success = success })
}

func batchGetInventoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	return handleUnary(ctx, handler, arg, result, func(ctx context.Context, h inventoryv1.InventoryService, req *v1.BatchGetInventoryReq) (*v1.BatchGetInventoryResp, error) {
		return h.BatchGetInventory(ctx, req)
	}, func(result interface{}, success *v1.BatchGetInventoryResp) {
		result.(*BatchGetInventoryResult).Success = success
	})
}

func commitStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	return handleUnary(ctx, handler, arg, result, func(ctx context.Context, h inventoryv1.InventoryService, req *v1.CommitStockReq) (*v1.InventoryOpResp, error) {
		return h.CommitStock(ctx, req)
	}, func(result interface{}, success *v1.InventoryOpResp) { result.(*InventoryOpResult).Success = success })
}

func refundStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	return handleUnary(ctx, handler, arg, result, func(ctx context.Context, h inventoryv1.InventoryService, req *v1.RefundStockReq) (*v1.InventoryOpResp, error) {
		return h.RefundStock(ctx, req)
	}, func(result interface{}, success *v1.InventoryOpResp) { result.(*InventoryOpResult).Success = success })
}

func adjustStockHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	return handleUnary(ctx, handler, arg, result, func(ctx context.Context, h inventoryv1.InventoryService, req *v1.AdjustStockReq) (*v1.InventoryOpResp, error) {
		return h.AdjustStock(ctx, req)
	}, func(result interface{}, success *v1.InventoryOpResp) { result.(*InventoryOpResult).Success = success })
}

type GetInventoryArgs struct{ Req *v1.GetInventoryReq }
type BatchGetInventoryArgs struct{ Req *v1.BatchGetInventoryReq }
type CommitStockArgs struct{ Req *v1.CommitStockReq }
type RefundStockArgs struct{ Req *v1.RefundStockReq }
type AdjustStockArgs struct{ Req *v1.AdjustStockReq }

func (p *GetInventoryArgs) Marshal(out []byte) ([]byte, error)      { return marshalReq(out, p.Req) }
func (p *BatchGetInventoryArgs) Marshal(out []byte) ([]byte, error) { return marshalReq(out, p.Req) }
func (p *CommitStockArgs) Marshal(out []byte) ([]byte, error)       { return marshalReq(out, p.Req) }
func (p *RefundStockArgs) Marshal(out []byte) ([]byte, error)       { return marshalReq(out, p.Req) }
func (p *AdjustStockArgs) Marshal(out []byte) ([]byte, error)       { return marshalReq(out, p.Req) }

func (p *GetInventoryArgs) Unmarshal(in []byte) error      { return unmarshalReq(in, &p.Req) }
func (p *BatchGetInventoryArgs) Unmarshal(in []byte) error { return unmarshalReq(in, &p.Req) }
func (p *CommitStockArgs) Unmarshal(in []byte) error       { return unmarshalReq(in, &p.Req) }
func (p *RefundStockArgs) Unmarshal(in []byte) error       { return unmarshalReq(in, &p.Req) }
func (p *AdjustStockArgs) Unmarshal(in []byte) error       { return unmarshalReq(in, &p.Req) }

func (p *GetInventoryArgs) GetReq() *v1.GetInventoryReq           { return p.Req }
func (p *BatchGetInventoryArgs) GetReq() *v1.BatchGetInventoryReq { return p.Req }
func (p *CommitStockArgs) GetReq() *v1.CommitStockReq             { return p.Req }
func (p *RefundStockArgs) GetReq() *v1.RefundStockReq             { return p.Req }
func (p *AdjustStockArgs) GetReq() *v1.AdjustStockReq             { return p.Req }

func (p *GetInventoryArgs) GetFirstArgument() interface{}      { return p.Req }
func (p *BatchGetInventoryArgs) GetFirstArgument() interface{} { return p.Req }
func (p *CommitStockArgs) GetFirstArgument() interface{}       { return p.Req }
func (p *RefundStockArgs) GetFirstArgument() interface{}       { return p.Req }
func (p *AdjustStockArgs) GetFirstArgument() interface{}       { return p.Req }

type GetInventoryResult struct{ Success *v1.GetInventoryResp }
type BatchGetInventoryResult struct{ Success *v1.BatchGetInventoryResp }
type InventoryOpResult struct{ Success *v1.InventoryOpResp }

func (p *GetInventoryResult) Marshal(out []byte) ([]byte, error) { return marshalReq(out, p.Success) }
func (p *BatchGetInventoryResult) Marshal(out []byte) ([]byte, error) {
	return marshalReq(out, p.Success)
}
func (p *InventoryOpResult) Marshal(out []byte) ([]byte, error) { return marshalReq(out, p.Success) }

func (p *GetInventoryResult) Unmarshal(in []byte) error      { return unmarshalReq(in, &p.Success) }
func (p *BatchGetInventoryResult) Unmarshal(in []byte) error { return unmarshalReq(in, &p.Success) }
func (p *InventoryOpResult) Unmarshal(in []byte) error       { return unmarshalReq(in, &p.Success) }

func (p *GetInventoryResult) GetSuccess() *v1.GetInventoryResp           { return p.Success }
func (p *BatchGetInventoryResult) GetSuccess() *v1.BatchGetInventoryResp { return p.Success }
func (p *InventoryOpResult) GetSuccess() *v1.InventoryOpResp             { return p.Success }
func (p *GetInventoryResult) SetSuccess(x interface{})                   { p.Success = x.(*v1.GetInventoryResp) }
func (p *BatchGetInventoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.BatchGetInventoryResp)
}
func (p *InventoryOpResult) SetSuccess(x interface{})     { p.Success = x.(*v1.InventoryOpResp) }
func (p *GetInventoryResult) IsSetSuccess() bool          { return p.Success != nil }
func (p *BatchGetInventoryResult) IsSetSuccess() bool     { return p.Success != nil }
func (p *InventoryOpResult) IsSetSuccess() bool           { return p.Success != nil }
func (p *GetInventoryResult) GetResult() interface{}      { return p.Success }
func (p *BatchGetInventoryResult) GetResult() interface{} { return p.Success }
func (p *InventoryOpResult) GetResult() interface{}       { return p.Success }

func newGetInventoryArgs() interface{}      { return &GetInventoryArgs{} }
func newBatchGetInventoryArgs() interface{} { return &BatchGetInventoryArgs{} }
func newCommitStockArgs() interface{}       { return &CommitStockArgs{} }
func newRefundStockArgs() interface{}       { return &RefundStockArgs{} }
func newAdjustStockArgs() interface{}       { return &AdjustStockArgs{} }

func newGetInventoryResult() interface{}      { return &GetInventoryResult{} }
func newBatchGetInventoryResult() interface{} { return &BatchGetInventoryResult{} }
func newCommitStockResult() interface{}       { return &InventoryOpResult{} }
func newRefundStockResult() interface{}       { return &InventoryOpResult{} }
func newAdjustStockResult() interface{}       { return &InventoryOpResult{} }

func marshalReq[T any](out []byte, req *T) ([]byte, error) {
	if req == nil {
		return out, nil
	}
	return proto.Marshal(req)
}

func unmarshalReq[T any](in []byte, target **T) error {
	msg := new(T)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	*target = msg
	return nil
}

type kClient struct{ c client.Client }

func newServiceClient(c client.Client) *kClient { return &kClient{c: c} }

func (p *kClient) GetInventory(ctx context.Context, req *v1.GetInventoryReq) (r *v1.GetInventoryResp, err error) {
	var args GetInventoryArgs
	args.Req = req
	var result GetInventoryResult
	if err = p.c.Call(ctx, "GetInventory", &args, &result); err != nil {
		return
	}
	return result.GetSuccess(), nil
}

func (p *kClient) BatchGetInventory(ctx context.Context, req *v1.BatchGetInventoryReq) (r *v1.BatchGetInventoryResp, err error) {
	var args BatchGetInventoryArgs
	args.Req = req
	var result BatchGetInventoryResult
	if err = p.c.Call(ctx, "BatchGetInventory", &args, &result); err != nil {
		return
	}
	return result.GetSuccess(), nil
}

func (p *kClient) CommitStock(ctx context.Context, req *v1.CommitStockReq) (r *v1.InventoryOpResp, err error) {
	return p.callInventoryOp(ctx, "CommitStock", &CommitStockArgs{Req: req})
}

func (p *kClient) RefundStock(ctx context.Context, req *v1.RefundStockReq) (r *v1.InventoryOpResp, err error) {
	return p.callInventoryOp(ctx, "RefundStock", &RefundStockArgs{Req: req})
}

func (p *kClient) AdjustStock(ctx context.Context, req *v1.AdjustStockReq) (r *v1.InventoryOpResp, err error) {
	return p.callInventoryOp(ctx, "AdjustStock", &AdjustStockArgs{Req: req})
}

func (p *kClient) callInventoryOp(ctx context.Context, method string, args interface{}) (r *v1.InventoryOpResp, err error) {
	var result InventoryOpResult
	if err = p.c.Call(ctx, method, args, &result); err != nil {
		return
	}
	return result.GetSuccess(), nil
}
