// Code generated by Kitex v0.15.4. DO NOT EDIT.

package orderv1

import (
	"context"

	"github.com/cloudwego/prutal"
)

// 更改订单状态
type ChangeOrderStatusReq struct {
	OrderId     int64  `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
	OrderStatus uint32 `protobuf:"varint,2,opt,name=order_status" json:"order_status,omitempty"`
}

func (x *ChangeOrderStatusReq) Reset() { *x = ChangeOrderStatusReq{} }

func (x *ChangeOrderStatusReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChangeOrderStatusReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChangeOrderStatusReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ChangeOrderStatusReq) GetOrderStatus() uint32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

type ChangeOrderStatusResp struct {
}

func (x *ChangeOrderStatusResp) Reset() { *x = ChangeOrderStatusResp{} }

func (x *ChangeOrderStatusResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ChangeOrderStatusResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type Address struct {
	StreetAddress string `protobuf:"bytes,1,opt,name=street_address" json:"street_address,omitempty"`
	City          string `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	State         string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Country       string `protobuf:"bytes,4,opt,name=country" json:"country,omitempty"`
	ZipCode       string `protobuf:"bytes,5,opt,name=zip_code" json:"zip_code,omitempty"`
}

func (x *Address) Reset() { *x = Address{} }

func (x *Address) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Address) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Address) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

// 订单项：只存储商品ID、数量、价格快照（目的是审计，不冗余存储商品详情，展示时从Product服务查询）
type OrderItem struct {
	ProductId        int64  `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	Quantity         int64  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	SnapshotPrice    int64  `protobuf:"varint,3,opt,name=snapshot_price" json:"snapshot_price,omitempty"` // 商品原始单价快照
	SnapshotCurrency string `protobuf:"bytes,4,opt,name=snapshot_currency" json:"snapshot_currency,omitempty"`
	ConvertedPrice   int64  `protobuf:"varint,5,opt,name=converted_price" json:"converted_price,omitempty"` // 转换为支付货币类型的价格
}

func (x *OrderItem) Reset() { *x = OrderItem{} }

func (x *OrderItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OrderItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetSnapshotPrice() int64 {
	if x != nil {
		return x.SnapshotPrice
	}
	return 0
}

func (x *OrderItem) GetSnapshotCurrency() string {
	if x != nil {
		return x.SnapshotCurrency
	}
	return ""
}

func (x *OrderItem) GetConvertedPrice() int64 {
	if x != nil {
		return x.ConvertedPrice
	}
	return 0
}

type CreateOrderReq struct {
	UserId   int64        `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Currency string       `protobuf:"bytes,2,opt,name=currency" json:"currency,omitempty"` // 用户选择的支付货币
	Address  *Address     `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Phone    string       `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Items    []*OrderItem `protobuf:"bytes,5,rep,name=items" json:"items,omitempty"`
}

func (x *CreateOrderReq) Reset() { *x = CreateOrderReq{} }

func (x *CreateOrderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateOrderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderReq) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CreateOrderReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateOrderReq) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResp struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *CreateOrderResp) Reset() { *x = CreateOrderResp{} }

func (x *CreateOrderResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateOrderResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateOrderResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ListOrderReq struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *ListOrderReq) Reset() { *x = ListOrderReq{} }

func (x *ListOrderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListOrderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Order struct {
	OrderId     int64        `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
	UserId      int64        `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	OrderStatus uint32       `protobuf:"varint,3,opt,name=order_status" json:"order_status,omitempty"` // 订单状态 0 - 待支付 1 - 支付成功 2 - 支付失败 3 - 取消订单
	Items       []*OrderItem `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	TotalAmount int64        `protobuf:"varint,5,opt,name=total_amount" json:"total_amount,omitempty"`
	Currency    string       `protobuf:"bytes,6,opt,name=currency" json:"currency,omitempty"` // 订单支付货币
	Address     *Address     `protobuf:"bytes,7,opt,name=address" json:"address,omitempty"`
	Phone       string       `protobuf:"bytes,8,opt,name=phone" json:"phone,omitempty"`
	CreatedAt   int64        `protobuf:"varint,9,opt,name=created_at" json:"created_at,omitempty"`
}

func (x *Order) Reset() { *x = Order{} }

func (x *Order) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Order) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Order) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetOrderStatus() uint32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Order) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListOrderResp struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (x *ListOrderResp) Reset() { *x = ListOrderResp{} }

func (x *ListOrderResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListOrderResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListOrderResp) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderReq) (res *CreateOrderResp, err error)
	ChangeOrderStatus(ctx context.Context, req *ChangeOrderStatusReq) (res *ChangeOrderStatusResp, err error)
	ListOrder(ctx context.Context, req *ListOrderReq) (res *ListOrderResp, err error)
}
