db:
  dsn: "root:root@tcp(douyinmall-mysql:3306)/douyinmall?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "douyinmall-redis:6379"

etcd:
  endpoints:
    - "douyinmall-etcd:2379"

grpc:
  server:
    name: seckill.service
    port: 8098

kafka:
  brokers:
    - "10.1.4.4:29092"
