db:
  host: "134.175.67.79"
  port: 3306
  user: "app"
  password: ""
  database: "douyin_mall"
  params: "charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "114.132.75.56:16379"
  password: ""
  db: 0

etcd:
  endpoints:
    - "42.193.160.221:2379"

grpc:
  server:
    name: seckill.service
    port: 8098

kafka:
  brokers:
    - "43.136.121.171:29092"
