// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/bff/handler"
	"github.com/XDWow/DouyinMall/backend/internal/bff/ioc"
	"github.com/XDWow/DouyinMall/backend/pkg/ginx"
)

// Injectors from wire.go:

func InitApp() *App {
	client := ioc.InitAgentClient()
	streamClient := ioc.InitAgentStreamClient()
	agentHandler := handler.NewAgentHandler(client, streamClient)
	userserviceClient := ioc.InitUserClient()
	jwtManager := ioc.InitJWTManager()
	authHandler := handler.NewAuthHandler(userserviceClient, jwtManager)
	cmdable := ioc.InitRedis()
	limiter := ioc.InitRateLimiter(cmdable)
	server := ioc.InitGinServer(agentHandler, authHandler, jwtManager, limiter)
	app := newApp(server)
	return app
}

// wire.go:

func newApp(svr *ginx.Server) *App {
	return &App{Server: svr}
}
