apisix:
  node_listen: 9080
  enable_admin: true
  enable_admin_cors: true
  allow_admin:
    - 0.0.0.0/0
  admin_key:
    - name: admin
      key: ${{APISIX_ADMIN_KEY}}
      role: admin

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd

etcd:
  host:
    - ${{APISIX_ETCD_HOST}}
  prefix: /apisix
  timeout: 30
