// Code generated by Kitex v0.16.1. DO NOT EDIT.

package aftersaleservice

import (
	"context"
	"errors"
	aftersalev1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/aftersale/v1"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/aftersale/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateAfterSaleRequest": kitex.NewMethodInfo(
		createAfterSaleRequestHandler,
		newCreateAfterSaleRequestArgs,
		newCreateAfterSaleRequestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetAfterSaleRequest": kitex.NewMethodInfo(
		getAfterSaleRequestHandler,
		newGetAfterSaleRequestArgs,
		newGetAfterSaleRequestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	afterSaleServiceServiceInfo                = NewServiceInfo()
	afterSaleServiceServiceInfoForClient       = NewServiceInfoForClient()
	afterSaleServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return afterSaleServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return afterSaleServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return afterSaleServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AfterSaleService"
	handlerType := (*aftersalev1.AfterSaleService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "aftersale",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createAfterSaleRequestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.CreateAfterSaleRequestReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(aftersalev1.AfterSaleService).CreateAfterSaleRequest(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateAfterSaleRequestArgs:
		success, err := handler.(aftersalev1.AfterSaleService).CreateAfterSaleRequest(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateAfterSaleRequestResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateAfterSaleRequestArgs() interface{} {
	return &CreateAfterSaleRequestArgs{}
}

func newCreateAfterSaleRequestResult() interface{} {
	return &CreateAfterSaleRequestResult{}
}

type CreateAfterSaleRequestArgs struct {
	Req *v1.CreateAfterSaleRequestReq
}

func (p *CreateAfterSaleRequestArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateAfterSaleRequestArgs) Unmarshal(in []byte) error {
	msg := new(v1.CreateAfterSaleRequestReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateAfterSaleRequestArgs_Req_DEFAULT *v1.CreateAfterSaleRequestReq

func (p *CreateAfterSaleRequestArgs) GetReq() *v1.CreateAfterSaleRequestReq {
	if !p.IsSetReq() {
		return CreateAfterSaleRequestArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateAfterSaleRequestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateAfterSaleRequestArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateAfterSaleRequestResult struct {
	Success *v1.CreateAfterSaleRequestResp
}

var CreateAfterSaleRequestResult_Success_DEFAULT *v1.CreateAfterSaleRequestResp

func (p *CreateAfterSaleRequestResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateAfterSaleRequestResult) Unmarshal(in []byte) error {
	msg := new(v1.CreateAfterSaleRequestResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateAfterSaleRequestResult) GetSuccess() *v1.CreateAfterSaleRequestResp {
	if !p.IsSetSuccess() {
		return CreateAfterSaleRequestResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateAfterSaleRequestResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.CreateAfterSaleRequestResp)
}

func (p *CreateAfterSaleRequestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateAfterSaleRequestResult) GetResult() interface{} {
	return p.Success
}

func getAfterSaleRequestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.GetAfterSaleRequestReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(aftersalev1.AfterSaleService).GetAfterSaleRequest(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetAfterSaleRequestArgs:
		success, err := handler.(aftersalev1.AfterSaleService).GetAfterSaleRequest(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetAfterSaleRequestResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetAfterSaleRequestArgs() interface{} {
	return &GetAfterSaleRequestArgs{}
}

func newGetAfterSaleRequestResult() interface{} {
	return &GetAfterSaleRequestResult{}
}

type GetAfterSaleRequestArgs struct {
	Req *v1.GetAfterSaleRequestReq
}

func (p *GetAfterSaleRequestArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetAfterSaleRequestArgs) Unmarshal(in []byte) error {
	msg := new(v1.GetAfterSaleRequestReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetAfterSaleRequestArgs_Req_DEFAULT *v1.GetAfterSaleRequestReq

func (p *GetAfterSaleRequestArgs) GetReq() *v1.GetAfterSaleRequestReq {
	if !p.IsSetReq() {
		return GetAfterSaleRequestArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetAfterSaleRequestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetAfterSaleRequestArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetAfterSaleRequestResult struct {
	Success *v1.GetAfterSaleRequestResp
}

var GetAfterSaleRequestResult_Success_DEFAULT *v1.GetAfterSaleRequestResp

func (p *GetAfterSaleRequestResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetAfterSaleRequestResult) Unmarshal(in []byte) error {
	msg := new(v1.GetAfterSaleRequestResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetAfterSaleRequestResult) GetSuccess() *v1.GetAfterSaleRequestResp {
	if !p.IsSetSuccess() {
		return GetAfterSaleRequestResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetAfterSaleRequestResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.GetAfterSaleRequestResp)
}

func (p *GetAfterSaleRequestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetAfterSaleRequestResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateAfterSaleRequest(ctx context.Context, Req *v1.CreateAfterSaleRequestReq) (r *v1.CreateAfterSaleRequestResp, err error) {
	var _args CreateAfterSaleRequestArgs
	_args.Req = Req
	var _result CreateAfterSaleRequestResult
	if err = p.c.Call(ctx, "CreateAfterSaleRequest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAfterSaleRequest(ctx context.Context, Req *v1.GetAfterSaleRequestReq) (r *v1.GetAfterSaleRequestResp, err error) {
	var _args GetAfterSaleRequestArgs
	_args.Req = Req
	var _result GetAfterSaleRequestResult
	if err = p.c.Call(ctx, "GetAfterSaleRequest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}


