// Code generated by Kitex v0.16.1. DO NOT EDIT.

package aftersaleservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/aftersale/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateAfterSaleRequest(ctx context.Context, Req *v1.CreateAfterSaleRequestReq, callOptions ...callopt.Option) (r *v1.CreateAfterSaleRequestResp, err error)
	GetAfterSaleRequest(ctx context.Context, Req *v1.GetAfterSaleRequestReq, callOptions ...callopt.Option) (r *v1.GetAfterSaleRequestResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAfterSaleServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAfterSaleServiceClient struct {
	*kClient
}

func (p *kAfterSaleServiceClient) CreateAfterSaleRequest(ctx context.Context, Req *v1.CreateAfterSaleRequestReq, callOptions ...callopt.Option) (r *v1.CreateAfterSaleRequestResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAfterSaleRequest(ctx, Req)
}

func (p *kAfterSaleServiceClient) GetAfterSaleRequest(ctx context.Context, Req *v1.GetAfterSaleRequestReq, callOptions ...callopt.Option) (r *v1.GetAfterSaleRequestResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAfterSaleRequest(ctx, Req)
}
