// Code generated by Kitex v0.16.1. DO NOT EDIT.
package aftersaleservice

import (
	aftersalev1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/aftersale/v1"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler aftersalev1.AfterSaleService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler aftersalev1.AfterSaleService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
