// Code generated by Kitex v0.15.4. DO NOT EDIT.

package paymentv1

import (
	"context"
	"strconv"

	"github.com/cloudwego/prutal"
)

type PaymentStatus int32

const (
	PaymentStatus_PaymentStatusUnknown PaymentStatus = 0
	PaymentStatus_PaymentStatusInit    PaymentStatus = 1
	PaymentStatus_PaymentStatusSuccess PaymentStatus = 2
	PaymentStatus_PaymentStatusFailed  PaymentStatus = 3
	PaymentStatus_PaymentStatusRefund  PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var PaymentStatus_name = map[int32]string{
	0: "PaymentStatusUnknown",
	1: "PaymentStatusInit",
	2: "PaymentStatusSuccess",
	3: "PaymentStatusFailed",
	4: "PaymentStatusRefund",
}

var PaymentStatus_value = map[string]int32{
	"PaymentStatusUnknown": 0,
	"PaymentStatusInit":    1,
	"PaymentStatusSuccess": 2,
	"PaymentStatusFailed":  3,
	"PaymentStatusRefund":  4,
}

func (x PaymentStatus) String() string {
	s, ok := PaymentStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type NativePrePayRequest struct {
	// 带一个 type，标记是扫码支付，还是 js 跳转支付，还是唤醒本地 APP
	// type = "native"
	Amt         *Amount `protobuf:"bytes,1,opt,name=amt" json:"amt,omitempty"`
	BizTradeNo  string  `protobuf:"bytes,2,opt,name=biz_trade_no" json:"biz_trade_no,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (x *NativePrePayRequest) Reset() { *x = NativePrePayRequest{} }

func (x *NativePrePayRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *NativePrePayRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *NativePrePayRequest) GetAmt() *Amount {
	if x != nil {
		return x.Amt
	}
	return nil
}

func (x *NativePrePayRequest) GetBizTradeNo() string {
	if x != nil {
		return x.BizTradeNo
	}
	return ""
}

func (x *NativePrePayRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 支付方式不同，所以响应的含义也会有不同，这里就是一个能打开支付二维码的 url
type NativePrePayResponse struct {
	CodeUrl string `protobuf:"bytes,1,opt,name=code_url" json:"code_url,omitempty"`
}

func (x *NativePrePayResponse) Reset() { *x = NativePrePayResponse{} }

func (x *NativePrePayResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *NativePrePayResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *NativePrePayResponse) GetCodeUrl() string {
	if x != nil {
		return x.CodeUrl
	}
	return ""
}

type Amount struct {
	Total    int64  `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Currency string `protobuf:"bytes,2,opt,name=currency" json:"currency,omitempty"`
}

func (x *Amount) Reset() { *x = Amount{} }

func (x *Amount) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Amount) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Amount) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// 业务方的唯一 no，通用
type GetPaymentRequest struct {
	BizTradeNo string `protobuf:"bytes,1,opt,name=biz_trade_no" json:"biz_trade_no,omitempty"`
}

func (x *GetPaymentRequest) Reset() { *x = GetPaymentRequest{} }

func (x *GetPaymentRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetPaymentRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPaymentRequest) GetBizTradeNo() string {
	if x != nil {
		return x.BizTradeNo
	}
	return ""
}

type GetPaymentResponse struct {
	// 有需要再加字段
	Status PaymentStatus `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (x *GetPaymentResponse) Reset() { *x = GetPaymentResponse{} }

func (x *GetPaymentResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetPaymentResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PaymentStatusUnknown
}

type PaymentService interface {
	NativePrepay(ctx context.Context, req *NativePrePayRequest) (res *NativePrePayResponse, err error)
	GetPayment(ctx context.Context, req *GetPaymentRequest) (res *GetPaymentResponse, err error)
}
