// Code generated by Kitex v0.15.4. DO NOT EDIT.

package inventoryv1

import (
	"context"

	"github.com/cloudwego/prutal"
)

type StockItem struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	Quantity  int32 `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *StockItem) Reset()                            { *x = StockItem{} }
func (x *StockItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *StockItem) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *StockItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}
func (x *StockItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type InventoryOpResp struct {
	StatusCode        int32               `protobuf:"varint,1,opt,name=status_code" json:"status_code,omitempty"`
	StatusMsg         string              `protobuf:"bytes,2,opt,name=status_msg" json:"status_msg,omitempty"`
	InsufficientItems []*InsufficientItem `protobuf:"bytes,3,rep,name=insufficient_items" json:"insufficient_items,omitempty"`
}

func (x *InventoryOpResp) Reset()                            { *x = InventoryOpResp{} }
func (x *InventoryOpResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *InventoryOpResp) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *InventoryOpResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}
func (x *InventoryOpResp) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}
func (x *InventoryOpResp) GetInsufficientItems() []*InsufficientItem {
	if x != nil {
		return x.InsufficientItems
	}
	return nil
}

type InsufficientItem struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	Requested int32 `protobuf:"varint,2,opt,name=requested" json:"requested,omitempty"`
	Available int64 `protobuf:"varint,3,opt,name=available" json:"available,omitempty"`
}

func (x *InsufficientItem) Reset()                            { *x = InsufficientItem{} }
func (x *InsufficientItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *InsufficientItem) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *InsufficientItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}
func (x *InsufficientItem) GetRequested() int32 {
	if x != nil {
		return x.Requested
	}
	return 0
}
func (x *InsufficientItem) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type GetInventoryReq struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
}

func (x *GetInventoryReq) Reset()                            { *x = GetInventoryReq{} }
func (x *GetInventoryReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *GetInventoryReq) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *GetInventoryReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetInventoryResp struct {
	ProductId      int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	AvailableStock int64 `protobuf:"varint,2,opt,name=available_stock" json:"available_stock,omitempty"`
	SoldStock      int64 `protobuf:"varint,3,opt,name=sold_stock" json:"sold_stock,omitempty"`
}

func (x *GetInventoryResp) Reset()                            { *x = GetInventoryResp{} }
func (x *GetInventoryResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *GetInventoryResp) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *GetInventoryResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}
func (x *GetInventoryResp) GetAvailableStock() int64 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}
func (x *GetInventoryResp) GetSoldStock() int64 {
	if x != nil {
		return x.SoldStock
	}
	return 0
}

type BatchGetInventoryReq struct {
	ProductIds []int64 `protobuf:"varint,1,rep,packed,name=product_ids" json:"product_ids,omitempty"`
}

func (x *BatchGetInventoryReq) Reset()                            { *x = BatchGetInventoryReq{} }
func (x *BatchGetInventoryReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *BatchGetInventoryReq) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *BatchGetInventoryReq) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type BatchGetInventoryResp struct {
	Inventories []*GetInventoryResp `protobuf:"bytes,1,rep,name=inventories" json:"inventories,omitempty"`
}

func (x *BatchGetInventoryResp) Reset() { *x = BatchGetInventoryResp{} }
func (x *BatchGetInventoryResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}
func (x *BatchGetInventoryResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }
func (x *BatchGetInventoryResp) GetInventories() []*GetInventoryResp {
	if x != nil {
		return x.Inventories
	}
	return nil
}

type CommitStockReq struct {
	OperationId string       `protobuf:"bytes,1,opt,name=operation_id" json:"operation_id,omitempty"`
	Items       []*StockItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (x *CommitStockReq) Reset()                            { *x = CommitStockReq{} }
func (x *CommitStockReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *CommitStockReq) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *CommitStockReq) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}
func (x *CommitStockReq) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RefundStockReq struct {
	OperationId string       `protobuf:"bytes,1,opt,name=operation_id" json:"operation_id,omitempty"`
	Items       []*StockItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (x *RefundStockReq) Reset()                            { *x = RefundStockReq{} }
func (x *RefundStockReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *RefundStockReq) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *RefundStockReq) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}
func (x *RefundStockReq) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AdjustStockReq struct {
	Reason string       `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	Items  []*StockItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (x *AdjustStockReq) Reset()                            { *x = AdjustStockReq{} }
func (x *AdjustStockReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }
func (x *AdjustStockReq) Unmarshal(in []byte) error         { return prutal.Unmarshal(in, x) }
func (x *AdjustStockReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}
func (x *AdjustStockReq) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type InventoryService interface {
	GetInventory(ctx context.Context, req *GetInventoryReq) (res *GetInventoryResp, err error)
	BatchGetInventory(ctx context.Context, req *BatchGetInventoryReq) (res *BatchGetInventoryResp, err error)
	CommitStock(ctx context.Context, req *CommitStockReq) (res *InventoryOpResp, err error)
	RefundStock(ctx context.Context, req *RefundStockReq) (res *InventoryOpResp, err error)
	AdjustStock(ctx context.Context, req *AdjustStockReq) (res *InventoryOpResp, err error)
}
