// Code generated by Kitex v0.15.4. DO NOT EDIT.

package agentv1

import (
	"context"
	"strconv"

	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/prutal"
)

type ChunkType int32

const (
	ChunkType_STAGE_UPDATE ChunkType = 0 // Pipeline 闃舵鐘舵€佹帹閫?
	ChunkType_TEXT_DELTA   ChunkType = 1 // 鍥炲鏂囨湰澧為噺锛堥€愬瓧/閫愬彞锛?
	ChunkType_DONE         ChunkType = 2 // 缁撴潫鏍囪
)

// Enum value maps for ChunkType.
var ChunkType_name = map[int32]string{
	0: "STAGE_UPDATE",
	1: "TEXT_DELTA",
	2: "DONE",
}

var ChunkType_value = map[string]int32{
	"STAGE_UPDATE": 0,
	"TEXT_DELTA":   1,
	"DONE":         2,
}

func (x ChunkType) String() string {
	s, ok := ChunkType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type MessageRole int32

const (
	MessageRole_ROLE_UNKNOWN   MessageRole = 0
	MessageRole_ROLE_USER      MessageRole = 1
	MessageRole_ROLE_ASSISTANT MessageRole = 2
	MessageRole_ROLE_SYSTEM    MessageRole = 3 // 绯荤粺鎻愮ず锛堜笉瀵圭敤鎴峰睍绀猴級
	MessageRole_ROLE_TOOL      MessageRole = 4 // 宸ュ叿璋冪敤缁撴灉锛圥hase 2锛?
)

// Enum value maps for MessageRole.
var MessageRole_name = map[int32]string{
	0: "ROLE_UNKNOWN",
	1: "ROLE_USER",
	2: "ROLE_ASSISTANT",
	3: "ROLE_SYSTEM",
	4: "ROLE_TOOL",
}

var MessageRole_value = map[string]int32{
	"ROLE_UNKNOWN":   0,
	"ROLE_USER":      1,
	"ROLE_ASSISTANT": 2,
	"ROLE_SYSTEM":    3,
	"ROLE_TOOL":      4,
}

func (x MessageRole) String() string {
	s, ok := MessageRole_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type IntentType int32

const (
	IntentType_INTENT_UNKNOWN           IntentType = 0
	IntentType_INTENT_FAQ               IntentType = 1  // 甯歌闂
	IntentType_INTENT_PRODUCT_INQUIRY   IntentType = 2  // 鍟嗗搧鍜ㄨ
	IntentType_INTENT_ORDER_INQUIRY     IntentType = 3  // 璁㈠崟鏌ヨ
	IntentType_INTENT_LOGISTICS         IntentType = 4  // 鐗╂祦鏌ヨ
	IntentType_INTENT_PAYMENT           IntentType = 5  // 鏀粯闂
	IntentType_INTENT_RETURN            IntentType = 6  // 閫€璐ч€€娆?
	IntentType_INTENT_COMPLAINT         IntentType = 7  // 鎶曡瘔寤鸿
	IntentType_INTENT_PROMOTION         IntentType = 8  // 钀ラ攢娲诲姩
	IntentType_INTENT_CHITCHAT          IntentType = 9  // 闂茶亰
	IntentType_INTENT_TRANSFER_TO_HUMAN IntentType = 10 // 杞汉宸?
)

// Enum value maps for IntentType.
var IntentType_name = map[int32]string{
	0:  "INTENT_UNKNOWN",
	1:  "INTENT_FAQ",
	2:  "INTENT_PRODUCT_INQUIRY",
	3:  "INTENT_ORDER_INQUIRY",
	4:  "INTENT_LOGISTICS",
	5:  "INTENT_PAYMENT",
	6:  "INTENT_RETURN",
	7:  "INTENT_COMPLAINT",
	8:  "INTENT_PROMOTION",
	9:  "INTENT_CHITCHAT",
	10: "INTENT_TRANSFER_TO_HUMAN",
}

var IntentType_value = map[string]int32{
	"INTENT_UNKNOWN":           0,
	"INTENT_FAQ":               1,
	"INTENT_PRODUCT_INQUIRY":   2,
	"INTENT_ORDER_INQUIRY":     3,
	"INTENT_LOGISTICS":         4,
	"INTENT_PAYMENT":           5,
	"INTENT_RETURN":            6,
	"INTENT_COMPLAINT":         7,
	"INTENT_PROMOTION":         8,
	"INTENT_CHITCHAT":          9,
	"INTENT_TRANSFER_TO_HUMAN": 10,
}

func (x IntentType) String() string {
	s, ok := IntentType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type SessionStatus int32

const (
	SessionStatus_SESSION_ACTIVE SessionStatus = 0 // 娲昏穬
	SessionStatus_SESSION_CLOSED SessionStatus = 1 // 宸茬粨鏉?
	SessionStatus_SESSION_HUMAN  SessionStatus = 2 // 宸茶浆浜哄伐
)

// Enum value maps for SessionStatus.
var SessionStatus_name = map[int32]string{
	0: "SESSION_ACTIVE",
	1: "SESSION_CLOSED",
	2: "SESSION_HUMAN",
}

var SessionStatus_value = map[string]int32{
	"SESSION_ACTIVE": 0,
	"SESSION_CLOSED": 1,
	"SESSION_HUMAN":  2,
}

func (x SessionStatus) String() string {
	s, ok := SessionStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type ChatRequest struct {
	SessionId   string            `protobuf:"bytes,1,opt,name=session_id" json:"session_id,omitempty"`
	UserId      int64             `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	Message     string            `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	ResumeToken string            `protobuf:"bytes,4,opt,name=resume_token" json:"resume_token,omitempty"`
	Metadata    map[string]string `protobuf:"bytes,5,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *ChatRequest) Reset() { *x = ChatRequest{} }

func (x *ChatRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChatRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *ChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ChatResponse struct {
	Reply              string          `protobuf:"bytes,1,opt,name=reply" json:"reply,omitempty"`                             // AI 鍥炲鍐呭
	Intent             IntentType      `protobuf:"varint,2,opt,name=intent" json:"intent,omitempty"`                          // 璇嗗埆鍑虹殑鎰忓浘
	Knowledge          []*KnowledgeRef `protobuf:"bytes,4,rep,name=knowledge" json:"knowledge,omitempty"`                     // 鍛戒腑鐨勭煡璇嗘潯鐩紙閫忔槑鍙В閲婏級
	ToolExecs          []*ToolExec     `protobuf:"bytes,5,rep,name=tool_execs" json:"tool_execs,omitempty"`                   // 鏈瑙﹀彂鐨勫伐鍏疯皟鐢ㄩ摼锛圥hase 2锛?
	SuggestedQuestions []string        `protobuf:"bytes,6,rep,name=suggested_questions" json:"suggested_questions,omitempty"` // 涓诲姩鎺ㄨ崘鐨勫叧鑱旈棶棰橈紙2~3 涓級
	Handoff            *HandoffSummary `protobuf:"bytes,7,opt,name=handoff" json:"handoff,omitempty"`                         // 杞汉宸ヤ氦鎺ユ憳瑕侊紙浠呰浆浜哄伐鏃堕檮甯︼級
	SessionId          string          `protobuf:"bytes,8,opt,name=session_id" json:"session_id,omitempty"`
	TraceId            string          `protobuf:"bytes,9,opt,name=trace_id" json:"trace_id,omitempty"`
	CheckpointId       string          `protobuf:"bytes,10,opt,name=checkpoint_id" json:"checkpoint_id,omitempty"`
	RerunNodes         []string        `protobuf:"bytes,11,rep,name=rerun_nodes" json:"rerun_nodes,omitempty"`
}

func (x *ChatResponse) Reset() { *x = ChatResponse{} }

func (x *ChatResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChatResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetIntent() IntentType {
	if x != nil {
		return x.Intent
	}
	return IntentType_INTENT_UNKNOWN
}

func (x *ChatResponse) GetKnowledge() []*KnowledgeRef {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

func (x *ChatResponse) GetToolExecs() []*ToolExec {
	if x != nil {
		return x.ToolExecs
	}
	return nil
}

func (x *ChatResponse) GetSuggestedQuestions() []string {
	if x != nil {
		return x.SuggestedQuestions
	}
	return nil
}

func (x *ChatResponse) GetHandoff() *HandoffSummary {
	if x != nil {
		return x.Handoff
	}
	return nil
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *ChatResponse) GetRerunNodes() []string {
	if x != nil {
		return x.RerunNodes
	}
	return nil
}

// 娴佸紡鍥炲鍗曚釜鍒嗙墖
// STAGE_UPDATE: Pipeline 闃舵鐘舵€佹帹閫?
type ChatStreamChunk struct {
	Type  ChunkType     `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Text  string        `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`   // TEXT_DELTA 鏃朵负鏂囨湰澧為噺
	Stage string        `protobuf:"bytes,3,opt,name=stage" json:"stage,omitempty"` // STAGE_UPDATE 鏃舵爣璇嗗綋鍓嶉樁娈?
	Final *ChatResponse `protobuf:"bytes,4,opt,name=final" json:"final,omitempty"` // DONE 鏃舵惡甯﹀畬鏁村搷搴旓紙鍚?debug/handoff/suggested_questions锛?
}

func (x *ChatStreamChunk) Reset() { *x = ChatStreamChunk{} }

func (x *ChatStreamChunk) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChatStreamChunk) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChatStreamChunk) GetType() ChunkType {
	if x != nil {
		return x.Type
	}
	return ChunkType_STAGE_UPDATE
}

func (x *ChatStreamChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatStreamChunk) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ChatStreamChunk) GetFinal() *ChatResponse {
	if x != nil {
		return x.Final
	}
	return nil
}

type CreateSessionRequest struct {
	UserId  int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Channel string `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
}

func (x *CreateSessionRequest) Reset() { *x = CreateSessionRequest{} }

func (x *CreateSessionRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateSessionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateSessionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSessionRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type CreateSessionResponse struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id" json:"session_id,omitempty"`
}

func (x *CreateSessionResponse) Reset() { *x = CreateSessionResponse{} }

func (x *CreateSessionResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateSessionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSessionsRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"` // 榛樿 10
	Offset int32 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (x *ListSessionsRequest) Reset() { *x = ListSessionsRequest{} }

func (x *ListSessionsRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListSessionsRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListSessionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	Sessions []*SessionBrief `protobuf:"bytes,1,rep,name=sessions" json:"sessions,omitempty"`
	Total    int32           `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListSessionsResponse) Reset() { *x = ListSessionsResponse{} }

func (x *ListSessionsResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListSessionsResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListSessionsResponse) GetSessions() []*SessionBrief {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SessionBrief 浼氳瘽鎽樿锛堝垪琛ㄥ睍绀虹敤锛?
type SessionBrief struct {
	SessionId   string        `protobuf:"bytes,1,opt,name=session_id" json:"session_id,omitempty"`
	LastMessage string        `protobuf:"bytes,2,opt,name=last_message" json:"last_message,omitempty"` // 鏈€鍚庝竴鏉℃秷鎭瑙?
	Status      SessionStatus `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	CreatedAt   string        `protobuf:"bytes,4,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt   string        `protobuf:"bytes,5,opt,name=updated_at" json:"updated_at,omitempty"`
	TotalTurns  int32         `protobuf:"varint,6,opt,name=total_turns" json:"total_turns,omitempty"`
}

func (x *SessionBrief) Reset() { *x = SessionBrief{} }

func (x *SessionBrief) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SessionBrief) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SessionBrief) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionBrief) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *SessionBrief) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_ACTIVE
}

func (x *SessionBrief) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SessionBrief) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SessionBrief) GetTotalTurns() int32 {
	if x != nil {
		return x.TotalTurns
	}
	return 0
}

type GetChatHistoryRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id" json:"session_id,omitempty"`
	Limit     int32  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"` // 榛樿 20
	Offset    int32  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (x *GetChatHistoryRequest) Reset() { *x = GetChatHistoryRequest{} }

func (x *GetChatHistoryRequest) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetChatHistoryRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetChatHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetChatHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetChatHistoryResponse struct {
	Messages []*Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	Total    int32      `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *GetChatHistoryResponse) Reset() { *x = GetChatHistoryResponse{} }

func (x *GetChatHistoryResponse) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetChatHistoryResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetChatHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ClearSessionRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id" json:"session_id,omitempty"`
}

func (x *ClearSessionRequest) Reset() { *x = ClearSessionRequest{} }

func (x *ClearSessionRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ClearSessionRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ClearSessionResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *ClearSessionResponse) Reset() { *x = ClearSessionResponse{} }

func (x *ClearSessionResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ClearSessionResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClearSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Message struct {
	Id         string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	SessionId  string      `protobuf:"bytes,2,opt,name=session_id" json:"session_id,omitempty"`
	Role       MessageRole `protobuf:"varint,3,opt,name=role" json:"role,omitempty"`
	Content    string      `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	Intent     IntentType  `protobuf:"varint,5,opt,name=intent" json:"intent,omitempty"`          // assistant 娑堟伅鐨勮瘑鍒剰鍥?
	Confidence float32     `protobuf:"fixed32,6,opt,name=confidence" json:"confidence,omitempty"` // assistant 娑堟伅鐨勭疆淇″害
	CreatedAt  string      `protobuf:"bytes,7,opt,name=created_at" json:"created_at,omitempty"`
}

func (x *Message) Reset() { *x = Message{} }

func (x *Message) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Message) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_ROLE_UNKNOWN
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetIntent() IntentType {
	if x != nil {
		return x.Intent
	}
	return IntentType_INTENT_UNKNOWN
}

func (x *Message) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// HandoffSummary AI 鈫?浜哄伐瀹㈡湇鐨勭粨鏋勫寲浜ゆ帴鎽樿
// 璁╀汉宸ュ鏈嶄竴鐪肩湅娓?AI 宸插仛鐨勪簨鍜岀敤鎴疯瘔姹傞」
type HandoffSummary struct {
	CoreIssue        string            `protobuf:"bytes,1,opt,name=core_issue" json:"core_issue,omitempty"`                                                                       // 涓€鍙ヨ瘽姒傛嫭鐢ㄦ埛鏍稿績璇夋眰
	AiActions        []string          `protobuf:"bytes,2,rep,name=ai_actions" json:"ai_actions,omitempty"`                                                                       // AI 宸茬粡鍋氫簡浠€涔?
	EscalationReason string            `protobuf:"bytes,3,opt,name=escalation_reason" json:"escalation_reason,omitempty"`                                                         // 涓轰粈涔堥渶瑕佽浆浜哄伐
	UserEmotion      string            `protobuf:"bytes,4,opt,name=user_emotion" json:"user_emotion,omitempty"`                                                                   // neutral/mild_frustration/angry/urgent
	Entities         map[string]string `protobuf:"bytes,5,rep,name=entities" json:"entities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 鍏抽敭瀹炰綋锛堣鍗曞彿銆佸晢鍝佸悕绛夛級
}

func (x *HandoffSummary) Reset() { *x = HandoffSummary{} }

func (x *HandoffSummary) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HandoffSummary) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HandoffSummary) GetCoreIssue() string {
	if x != nil {
		return x.CoreIssue
	}
	return ""
}

func (x *HandoffSummary) GetAiActions() []string {
	if x != nil {
		return x.AiActions
	}
	return nil
}

func (x *HandoffSummary) GetEscalationReason() string {
	if x != nil {
		return x.EscalationReason
	}
	return ""
}

func (x *HandoffSummary) GetUserEmotion() string {
	if x != nil {
		return x.UserEmotion
	}
	return ""
}

func (x *HandoffSummary) GetEntities() map[string]string {
	if x != nil {
		return x.Entities
	}
	return nil
}

// KnowledgeRef RAG 鍛戒腑鐨勭煡璇嗘潯鐩紩鐢?
type KnowledgeRef struct {
	Id        string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title     string  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content   string  `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`       // chunk 瀹屾暣鍐呭
	Category  string  `protobuf:"bytes,4,opt,name=category" json:"category,omitempty"`     // faq / product / policy / promotion
	Relevance float32 `protobuf:"fixed32,5,opt,name=relevance" json:"relevance,omitempty"` // 鐩稿叧鎬у緱鍒?
}

func (x *KnowledgeRef) Reset() { *x = KnowledgeRef{} }

func (x *KnowledgeRef) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *KnowledgeRef) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *KnowledgeRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeRef) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeRef) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeRef) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *KnowledgeRef) GetRelevance() float32 {
	if x != nil {
		return x.Relevance
	}
	return 0
}

// ToolExec 宸ュ叿璋冪敤鎵ц璁板綍锛圥hase 2锛?
type ToolExec struct {
	ToolName  string            `protobuf:"bytes,1,opt,name=tool_name" json:"tool_name,omitempty"`                                                                     // get_order / search_product / get_logistics
	Params    map[string]string `protobuf:"bytes,2,rep,name=params" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 璋冪敤鍙傛暟
	Reasoning string            `protobuf:"bytes,3,opt,name=reasoning" json:"reasoning,omitempty"`                                                                     // LLM 缁欏嚭鐨勮皟鐢ㄧ悊鐢?
	Success   bool              `protobuf:"varint,4,opt,name=success" json:"success,omitempty"`
	Result    string            `protobuf:"bytes,5,opt,name=result" json:"result,omitempty"` // 鎵ц缁撴灉锛圝SON锛?
	Error     string            `protobuf:"bytes,6,opt,name=error" json:"error,omitempty"`   // 澶辫触鍘熷洜
	LatencyMs int64             `protobuf:"varint,7,opt,name=latency_ms" json:"latency_ms,omitempty"`
}

func (x *ToolExec) Reset() { *x = ToolExec{} }

func (x *ToolExec) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ToolExec) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ToolExec) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolExec) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ToolExec) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ToolExec) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolExec) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolExec) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolExec) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type AgentService interface {
	SendMessage(ctx context.Context, req *ChatRequest) (res *ChatResponse, err error)
	SendMessageStream(req *ChatRequest, stream AgentService_SendMessageStreamServer) (err error)
	GetChatHistory(ctx context.Context, req *GetChatHistoryRequest) (res *GetChatHistoryResponse, err error)
	CreateSession(ctx context.Context, req *CreateSessionRequest) (res *CreateSessionResponse, err error)
	ListSessions(ctx context.Context, req *ListSessionsRequest) (res *ListSessionsResponse, err error)
	ClearSession(ctx context.Context, req *ClearSessionRequest) (res *ClearSessionResponse, err error)
}

type AgentService_SendMessageStreamServer interface {
	streaming.Stream
	Send(*ChatStreamChunk) error
}
