// Code generated by Kitex v0.15.4. DO NOT EDIT.

package orderservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/order/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrder(ctx context.Context, Req *v1.CreateOrderReq, callOptions ...callopt.Option) (r *v1.CreateOrderResp, err error)
	ChangeOrderStatus(ctx context.Context, Req *v1.ChangeOrderStatusReq, callOptions ...callopt.Option) (r *v1.ChangeOrderStatusResp, err error)
	GetOrder(ctx context.Context, Req *v1.GetOrderReq, callOptions ...callopt.Option) (r *v1.GetOrderResp, err error)
	ListOrder(ctx context.Context, Req *v1.ListOrderReq, callOptions ...callopt.Option) (r *v1.ListOrderResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) CreateOrder(ctx context.Context, Req *v1.CreateOrderReq, callOptions ...callopt.Option) (r *v1.CreateOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, Req)
}

func (p *kOrderServiceClient) ChangeOrderStatus(ctx context.Context, Req *v1.ChangeOrderStatusReq, callOptions ...callopt.Option) (r *v1.ChangeOrderStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeOrderStatus(ctx, Req)
}

func (p *kOrderServiceClient) GetOrder(ctx context.Context, Req *v1.GetOrderReq, callOptions ...callopt.Option) (r *v1.GetOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrder(ctx, Req)
}

func (p *kOrderServiceClient) ListOrder(ctx context.Context, Req *v1.ListOrderReq, callOptions ...callopt.Option) (r *v1.ListOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrder(ctx, Req)
}


