// Code generated by Kitex v0.15.4. DO NOT EDIT.

package agentservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/kitex_gen/agent/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streamclient "github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendMessage(ctx context.Context, Req *v1.ChatRequest, callOptions ...callopt.Option) (r *v1.ChatResponse, err error)
	SendMessageStream(ctx context.Context, Req *v1.ChatRequest, callOptions ...callopt.Option) (stream AgentService_SendMessageStreamClient, err error)
	GetChatHistory(ctx context.Context, Req *v1.GetChatHistoryRequest, callOptions ...callopt.Option) (r *v1.GetChatHistoryResponse, err error)
	CreateSession(ctx context.Context, Req *v1.CreateSessionRequest, callOptions ...callopt.Option) (r *v1.CreateSessionResponse, err error)
	ListSessions(ctx context.Context, Req *v1.ListSessionsRequest, callOptions ...callopt.Option) (r *v1.ListSessionsResponse, err error)
	ClearSession(ctx context.Context, Req *v1.ClearSessionRequest, callOptions ...callopt.Option) (r *v1.ClearSessionResponse, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	SendMessageStream(ctx context.Context, Req *v1.ChatRequest, callOptions ...streamcall.Option) (stream AgentService_SendMessageStreamClient, err error)
}

type AgentService_SendMessageStreamClient interface {
	streaming.Stream
	Recv() (*v1.ChatStreamChunk, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAgentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAgentServiceClient struct {
	*kClient
}

func (p *kAgentServiceClient) SendMessage(ctx context.Context, Req *v1.ChatRequest, callOptions ...callopt.Option) (r *v1.ChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessage(ctx, Req)
}

func (p *kAgentServiceClient) SendMessageStream(ctx context.Context, Req *v1.ChatRequest, callOptions ...callopt.Option) (stream AgentService_SendMessageStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendMessageStream(ctx, Req)
}

func (p *kAgentServiceClient) GetChatHistory(ctx context.Context, Req *v1.GetChatHistoryRequest, callOptions ...callopt.Option) (r *v1.GetChatHistoryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetChatHistory(ctx, Req)
}

func (p *kAgentServiceClient) CreateSession(ctx context.Context, Req *v1.CreateSessionRequest, callOptions ...callopt.Option) (r *v1.CreateSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSession(ctx, Req)
}

func (p *kAgentServiceClient) ListSessions(ctx context.Context, Req *v1.ListSessionsRequest, callOptions ...callopt.Option) (r *v1.ListSessionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSessions(ctx, Req)
}

func (p *kAgentServiceClient) ClearSession(ctx context.Context, Req *v1.ClearSessionRequest, callOptions ...callopt.Option) (r *v1.ClearSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ClearSession(ctx, Req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAgentServiceStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAgentServiceStreamClient struct {
	*kClient
}

func (p *kAgentServiceStreamClient) SendMessageStream(ctx context.Context, Req *v1.ChatRequest, callOptions ...streamcall.Option) (stream AgentService_SendMessageStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.SendMessageStream(ctx, Req)
}


