// Code generated by Kitex v0.15.4. DO NOT EDIT.

package checkoutv1

import (
	"context"

	"github.com/cloudwego/prutal"
)

type CheckoutItem struct {
	ProductId int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	Quantity  int64 `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *CheckoutItem) Reset() { *x = CheckoutItem{} }

func (x *CheckoutItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CheckoutItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CheckoutItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CheckoutItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Address struct {
	ReceiverName string `protobuf:"bytes,1,opt,name=receiver_name" json:"receiver_name,omitempty"`
	Phone        string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	Province     string `protobuf:"bytes,3,opt,name=province" json:"province,omitempty"`
	City         string `protobuf:"bytes,4,opt,name=city" json:"city,omitempty"`
	District     string `protobuf:"bytes,5,opt,name=district" json:"district,omitempty"`
	Street       string `protobuf:"bytes,6,opt,name=street" json:"street,omitempty"`
	ZipCode      string `protobuf:"bytes,7,opt,name=zip_code" json:"zip_code,omitempty"`
}

func (x *Address) Reset() { *x = Address{} }

func (x *Address) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Address) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Address) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *Address) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

type PreviewOrderReq struct {
	UserId int64           `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Items  []*CheckoutItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (x *PreviewOrderReq) Reset() { *x = PreviewOrderReq{} }

func (x *PreviewOrderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PreviewOrderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PreviewOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PreviewOrderReq) GetItems() []*CheckoutItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PreviewOrderResp struct {
	Products         []*ProductDetail `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
	AvailableCoupons []*CouponItem    `protobuf:"bytes,3,rep,name=available_coupons" json:"available_coupons,omitempty"`
}

func (x *PreviewOrderResp) Reset() { *x = PreviewOrderResp{} }

func (x *PreviewOrderResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PreviewOrderResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PreviewOrderResp) GetProducts() []*ProductDetail {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *PreviewOrderResp) GetAvailableCoupons() []*CouponItem {
	if x != nil {
		return x.AvailableCoupons
	}
	return nil
}

type ProductDetail struct {
	ProductId         int64  `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Picture           string `protobuf:"bytes,3,opt,name=picture" json:"picture,omitempty"`
	Price             int64  `protobuf:"varint,4,opt,name=price" json:"price,omitempty"`
	Currency          string `protobuf:"bytes,5,opt,name=currency" json:"currency,omitempty"`
	Quantity          int64  `protobuf:"varint,6,opt,name=quantity" json:"quantity,omitempty"`
	Subtotal          int64  `protobuf:"varint,7,opt,name=subtotal" json:"subtotal,omitempty"`
	Available         bool   `protobuf:"varint,8,opt,name=available" json:"available,omitempty"`
	UnavailableReason string `protobuf:"bytes,9,opt,name=unavailable_reason" json:"unavailable_reason,omitempty"`
}

func (x *ProductDetail) Reset() { *x = ProductDetail{} }

func (x *ProductDetail) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ProductDetail) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ProductDetail) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDetail) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *ProductDetail) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductDetail) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProductDetail) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductDetail) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *ProductDetail) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ProductDetail) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

type CouponItem struct {
	CouponId         int64           `protobuf:"varint,1,opt,name=coupon_id" json:"coupon_id,omitempty"`
	Name             string          `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description      string          `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	DiscountAmount   int64           `protobuf:"varint,4,opt,name=discount_amount" json:"discount_amount,omitempty"`
	Usable           bool            `protobuf:"varint,5,opt,name=usable" json:"usable,omitempty"`
	UnusableReason   string          `protobuf:"bytes,6,opt,name=unusable_reason" json:"unusable_reason,omitempty"`
	PerLineDiscounts map[int64]int64 `protobuf:"bytes,7,rep,name=per_line_discounts" json:"per_line_discounts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (x *CouponItem) Reset() { *x = CouponItem{} }

func (x *CouponItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CouponItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CouponItem) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *CouponItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CouponItem) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CouponItem) GetUsable() bool {
	if x != nil {
		return x.Usable
	}
	return false
}

func (x *CouponItem) GetUnusableReason() string {
	if x != nil {
		return x.UnusableReason
	}
	return ""
}

func (x *CouponItem) GetPerLineDiscounts() map[int64]int64 {
	if x != nil {
		return x.PerLineDiscounts
	}
	return nil
}

type PlaceOrderReq struct {
	UserId         int64           `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Items          []*CheckoutItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	CouponIds      []int64         `protobuf:"varint,3,rep,packed,name=coupon_ids" json:"coupon_ids,omitempty"`
	Address        *Address        `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	PaymentMethod  string          `protobuf:"bytes,5,opt,name=payment_method" json:"payment_method,omitempty"`
	Currency       string          `protobuf:"bytes,6,opt,name=currency" json:"currency,omitempty"`
	Remark         string          `protobuf:"bytes,7,opt,name=remark" json:"remark,omitempty"`
	ExpectedAmount int64           `protobuf:"varint,8,opt,name=expected_amount" json:"expected_amount,omitempty"`
	OrderKind      string          `protobuf:"bytes,9,opt,name=order_kind" json:"order_kind,omitempty"`
}

func (x *PlaceOrderReq) Reset() { *x = PlaceOrderReq{} }

func (x *PlaceOrderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PlaceOrderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PlaceOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceOrderReq) GetItems() []*CheckoutItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlaceOrderReq) GetCouponIds() []int64 {
	if x != nil {
		return x.CouponIds
	}
	return nil
}

func (x *PlaceOrderReq) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PlaceOrderReq) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PlaceOrderReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PlaceOrderReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PlaceOrderReq) GetExpectedAmount() int64 {
	if x != nil {
		return x.ExpectedAmount
	}
	return 0
}

func (x *PlaceOrderReq) GetOrderKind() string {
	if x != nil {
		return x.OrderKind
	}
	return ""
}

type PlaceOrderResp struct {
	OrderId     int64  `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
	PaymentUrl  string `protobuf:"bytes,2,opt,name=payment_url" json:"payment_url,omitempty"`
	TotalAmount int64  `protobuf:"varint,3,opt,name=total_amount" json:"total_amount,omitempty"`
	ExpireAt    int64  `protobuf:"varint,4,opt,name=expire_at" json:"expire_at,omitempty"`
}

func (x *PlaceOrderResp) Reset() { *x = PlaceOrderResp{} }

func (x *PlaceOrderResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PlaceOrderResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PlaceOrderResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PlaceOrderResp) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *PlaceOrderResp) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *PlaceOrderResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type PayOrderReq struct {
	UserId  int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	OrderId int64 `protobuf:"varint,2,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *PayOrderReq) Reset() { *x = PayOrderReq{} }

func (x *PayOrderReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PayOrderReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PayOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type PayOrderResp struct {
	OrderId     int64  `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
	PaymentUrl  string `protobuf:"bytes,2,opt,name=payment_url" json:"payment_url,omitempty"`
	TotalAmount int64  `protobuf:"varint,3,opt,name=total_amount" json:"total_amount,omitempty"`
	ExpireAt    int64  `protobuf:"varint,4,opt,name=expire_at" json:"expire_at,omitempty"`
}

func (x *PayOrderResp) Reset() { *x = PayOrderResp{} }

func (x *PayOrderResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *PayOrderResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *PayOrderResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PayOrderResp) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *PayOrderResp) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *PayOrderResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type CheckoutService interface {
	PreviewOrder(ctx context.Context, req *PreviewOrderReq) (res *PreviewOrderResp, err error)
	PlaceOrder(ctx context.Context, req *PlaceOrderReq) (res *PlaceOrderResp, err error)
	PayOrder(ctx context.Context, req *PayOrderReq) (res *PayOrderResp, err error)
}


