// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/payment/infra/db"
	"github.com/XDWow/DouyinMall/backend/internal/payment/infra/repository"
	"github.com/XDWow/DouyinMall/backend/internal/payment/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/payment/job"
	"github.com/XDWow/DouyinMall/backend/internal/payment/transport/grpc"
	"github.com/XDWow/DouyinMall/backend/internal/payment/usecase"
	"github.com/XDWow/DouyinMall/backend/pkg/ginx"
	"github.com/cloudwego/kitex/server"
	"github.com/robfig/cron/v3"
)

// Injectors from wire.go:

func InitApp() *App {
	gormDB := ioc.InitDB()
	loggerV1 := ioc.InitLogger()
	paymentRepository := repository.NewPaymentRepository(gormDB, loggerV1)
	nativePayService := ioc.InitNativePayService()
	nativePrePaymentUC := ioc.InitNativePrePaymentUC(paymentRepository, loggerV1, nativePayService)
	getPaymentUC := usecase.NewGetPaymentUC(paymentRepository, loggerV1)
	paymentOutboxRepository := repository.NewPaymentOutboxRepository(gormDB)
	txManager := db.NewGormTxManager(gormDB)
	payCallbackUC := usecase.NewPayCallbackUC(paymentRepository, paymentOutboxRepository, txManager, loggerV1)
	syncPaymentOrderUC := ioc.InitSyncPaymentOrderUC(nativePayService, payCallbackUC, loggerV1)
	confirmPaymentUC := usecase.NewConfirmPaymentUC(paymentRepository, syncPaymentOrderUC)
	paymentHandler := grpc.NewPaymentHandler(nativePrePaymentUC, getPaymentUC, confirmPaymentUC)
	server := ioc.InitGRPCServer(paymentHandler)
	alipayWebConfig := ioc.InitAlipayWebConfig()
	alipayNotifyUC := usecase.NewAlipayNotifyUC(paymentRepository, payCallbackUC, alipayWebConfig)
	client := ioc.InitOrderClient()
	alipayClient := ioc.InitAlipayClient()
	pagePayService := ioc.InitPagePayService(alipayClient)
	alipayPagePayUC := usecase.NewAlipayPagePayUC(client, paymentRepository, pagePayService, alipayWebConfig, loggerV1)
	alipayReturnPageUC := usecase.NewAlipayReturnPageUC(client)
	string2 := ioc.InitPaymentProvider()
	handler := ioc.InitWechatNotifyHandler()
	ginxServer := ioc.InitHTTPServer(payCallbackUC, alipayNotifyUC, alipayPagePayUC, alipayReturnPageUC, loggerV1, string2, alipayClient, handler)
	syncPaymentOrderJob := job.NewSyncPaymentOrderJob(syncPaymentOrderUC, paymentRepository, loggerV1)
	producer := ioc.InitRocketMQProducerClient()
	messageProducer := ioc.InitPaymentStatusProducer(producer)
	paymentStatusProducer := ioc.InitPaymentMQProducer(messageProducer)
	paymentOutboxWorkerJob := job.NewPaymentOutboxWorkerJob(paymentOutboxRepository, paymentStatusProducer, loggerV1)
	cron := ioc.InitJobs(syncPaymentOrderJob, paymentOutboxWorkerJob, loggerV1)
	app := newApp(server, ginxServer, cron)
	return app
}

// wire.go:

type App struct {
	GRPCServer server.Server
	HTTPServer interface {
		Start() error
	}
	Cron *cron.Cron
}

func newApp(
	grpcServer server.Server,
	httpServer *ginx.Server, cron2 *cron.Cron,
) *App {
	return &App{
		GRPCServer: grpcServer,
		HTTPServer: httpServer,
		Cron:       cron2,
	}
}
