// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/XDWow/DouyinMall/backend/internal/payment/infra/repository"
	"github.com/XDWow/DouyinMall/backend/internal/payment/ioc"
	"github.com/XDWow/DouyinMall/backend/internal/payment/job"
	"github.com/XDWow/DouyinMall/backend/internal/payment/transport/grpc"
	"github.com/XDWow/DouyinMall/backend/internal/payment/usecase"
	"github.com/XDWow/DouyinMall/backend/pkg/ginx"
	"github.com/cloudwego/kitex/server"
	"github.com/robfig/cron/v3"
)

func InitApp() *App {
	db := ioc.InitDB()
	loggerV1 := ioc.InitLogger()
	paymentRepository := repository.NewPaymentRepository(db, loggerV1)
	orderClient := ioc.InitOrderClient()
	payCallbackUC := usecase.NewPayCallbackUC(paymentRepository, orderClient)
	wechatService := ioc.InitWechatNativeApiService()
	nativeApiService := ioc.InitWechatNativeService(wechatService)
	nativePrePaymentUC := ioc.InitNativePrePaymentUC(paymentRepository, loggerV1, nativeApiService)
	syncWechatOrderUC := ioc.InitSyncWechatOrderUC(nativeApiService, payCallbackUC, loggerV1)
	getPaymentUC := usecase.NewGetPaymentUC(paymentRepository, loggerV1)
	confirmPaymentUC := usecase.NewConfirmPaymentUC(paymentRepository, syncWechatOrderUC)
	paymentHandler := grpc.NewPaymentHandler(nativePrePaymentUC, getPaymentUC, confirmPaymentUC)
	server := ioc.InitGRPCServer(paymentHandler)
	ginxServer := ioc.InitHTTPServer(payCallbackUC, loggerV1)
	syncWechatOrderJob := job.NewSyncWechatOrderJob(syncWechatOrderUC, paymentRepository, loggerV1)
	cron := ioc.InitJobs(syncWechatOrderJob, loggerV1)
	app := newApp(server, ginxServer, cron)
	return app
}

type App struct {
	GRPCServer server.Server
	HTTPServer interface {
		Start() error
	}
	Cron *cron.Cron
}

func newApp(
	grpcServer server.Server,
	httpServer *ginx.Server,
	cron *cron.Cron,
) *App {
	return &App{
		GRPCServer: grpcServer,
		HTTPServer: httpServer,
		Cron:       cron,
	}
}


