// Code generated by Kitex v0.16.1. DO NOT EDIT.

package aftersalev1

import (
	"context"
	"strconv"

	"github.com/cloudwego/prutal"
)

type AfterSaleRequestType int32

const (
	AfterSaleRequestType_AFTER_SALE_REQUEST_TYPE_UNKNOWN  AfterSaleRequestType = 0
	AfterSaleRequestType_AFTER_SALE_REQUEST_TYPE_RETURN   AfterSaleRequestType = 1
	AfterSaleRequestType_AFTER_SALE_REQUEST_TYPE_EXCHANGE AfterSaleRequestType = 2
)

// Enum value maps for AfterSaleRequestType.
var AfterSaleRequestType_name = map[int32]string{
	0: "AFTER_SALE_REQUEST_TYPE_UNKNOWN",
	1: "AFTER_SALE_REQUEST_TYPE_RETURN",
	2: "AFTER_SALE_REQUEST_TYPE_EXCHANGE",
}

var AfterSaleRequestType_value = map[string]int32{
	"AFTER_SALE_REQUEST_TYPE_UNKNOWN":  0,
	"AFTER_SALE_REQUEST_TYPE_RETURN":   1,
	"AFTER_SALE_REQUEST_TYPE_EXCHANGE": 2,
}

func (x AfterSaleRequestType) String() string {
	s, ok := AfterSaleRequestType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type AfterSaleRequestStatus int32

const (
	AfterSaleRequestStatus_AFTER_SALE_REQUEST_STATUS_UNKNOWN        AfterSaleRequestStatus = 0
	AfterSaleRequestStatus_AFTER_SALE_REQUEST_STATUS_PENDING_REVIEW AfterSaleRequestStatus = 1
	AfterSaleRequestStatus_AFTER_SALE_REQUEST_STATUS_APPROVED       AfterSaleRequestStatus = 2
	AfterSaleRequestStatus_AFTER_SALE_REQUEST_STATUS_REJECTED       AfterSaleRequestStatus = 3
	AfterSaleRequestStatus_AFTER_SALE_REQUEST_STATUS_CANCELED       AfterSaleRequestStatus = 4
	AfterSaleRequestStatus_AFTER_SALE_REQUEST_STATUS_COMPLETED      AfterSaleRequestStatus = 5
)

// Enum value maps for AfterSaleRequestStatus.
var AfterSaleRequestStatus_name = map[int32]string{
	0: "AFTER_SALE_REQUEST_STATUS_UNKNOWN",
	1: "AFTER_SALE_REQUEST_STATUS_PENDING_REVIEW",
	2: "AFTER_SALE_REQUEST_STATUS_APPROVED",
	3: "AFTER_SALE_REQUEST_STATUS_REJECTED",
	4: "AFTER_SALE_REQUEST_STATUS_CANCELED",
	5: "AFTER_SALE_REQUEST_STATUS_COMPLETED",
}

var AfterSaleRequestStatus_value = map[string]int32{
	"AFTER_SALE_REQUEST_STATUS_UNKNOWN":        0,
	"AFTER_SALE_REQUEST_STATUS_PENDING_REVIEW": 1,
	"AFTER_SALE_REQUEST_STATUS_APPROVED":       2,
	"AFTER_SALE_REQUEST_STATUS_REJECTED":       3,
	"AFTER_SALE_REQUEST_STATUS_CANCELED":       4,
	"AFTER_SALE_REQUEST_STATUS_COMPLETED":      5,
}

func (x AfterSaleRequestStatus) String() string {
	s, ok := AfterSaleRequestStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

type AfterSaleRequest struct {
	RequestNo   string                 `protobuf:"bytes,1,opt,name=request_no" json:"request_no,omitempty"`
	UserId      int64                  `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	OrderId     int64                  `protobuf:"varint,3,opt,name=order_id" json:"order_id,omitempty"`
	ItemId      int64                  `protobuf:"varint,4,opt,name=item_id" json:"item_id,omitempty"`
	RequestType AfterSaleRequestType   `protobuf:"varint,5,opt,name=request_type" json:"request_type,omitempty"`
	Reason      string                 `protobuf:"bytes,6,opt,name=reason" json:"reason,omitempty"`
	Status      AfterSaleRequestStatus `protobuf:"varint,7,opt,name=status" json:"status,omitempty"`
	CreatedAt   int64                  `protobuf:"varint,8,opt,name=created_at" json:"created_at,omitempty"`
}

func (x *AfterSaleRequest) Reset() { *x = AfterSaleRequest{} }

func (x *AfterSaleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AfterSaleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AfterSaleRequest) GetRequestNo() string {
	if x != nil {
		return x.RequestNo
	}
	return ""
}

func (x *AfterSaleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AfterSaleRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AfterSaleRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AfterSaleRequest) GetRequestType() AfterSaleRequestType {
	if x != nil {
		return x.RequestType
	}
	return AfterSaleRequestType_AFTER_SALE_REQUEST_TYPE_UNKNOWN
}

func (x *AfterSaleRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AfterSaleRequest) GetStatus() AfterSaleRequestStatus {
	if x != nil {
		return x.Status
	}
	return AfterSaleRequestStatus_AFTER_SALE_REQUEST_STATUS_UNKNOWN
}

func (x *AfterSaleRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateAfterSaleRequestReq struct {
	UserId       int64                `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	OrderId      int64                `protobuf:"varint,2,opt,name=order_id" json:"order_id,omitempty"`
	ItemId       int64                `protobuf:"varint,3,opt,name=item_id" json:"item_id,omitempty"`
	RequestType  AfterSaleRequestType `protobuf:"varint,4,opt,name=request_type" json:"request_type,omitempty"`
	Reason       string               `protobuf:"bytes,5,opt,name=reason" json:"reason,omitempty"`
	SessionId    string               `protobuf:"bytes,6,opt,name=session_id" json:"session_id,omitempty"`
	TraceId      string               `protobuf:"bytes,7,opt,name=trace_id" json:"trace_id,omitempty"`
	MetadataJson string               `protobuf:"bytes,8,opt,name=metadata_json" json:"metadata_json,omitempty"`
}

func (x *CreateAfterSaleRequestReq) Reset() { *x = CreateAfterSaleRequestReq{} }

func (x *CreateAfterSaleRequestReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateAfterSaleRequestReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateAfterSaleRequestReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAfterSaleRequestReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateAfterSaleRequestReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CreateAfterSaleRequestReq) GetRequestType() AfterSaleRequestType {
	if x != nil {
		return x.RequestType
	}
	return AfterSaleRequestType_AFTER_SALE_REQUEST_TYPE_UNKNOWN
}

func (x *CreateAfterSaleRequestReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateAfterSaleRequestReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateAfterSaleRequestReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateAfterSaleRequestReq) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type CreateAfterSaleRequestResp struct {
	Request *AfterSaleRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (x *CreateAfterSaleRequestResp) Reset() { *x = CreateAfterSaleRequestResp{} }

func (x *CreateAfterSaleRequestResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateAfterSaleRequestResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateAfterSaleRequestResp) GetRequest() *AfterSaleRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetAfterSaleRequestReq struct {
	RequestNo string `protobuf:"bytes,1,opt,name=request_no" json:"request_no,omitempty"`
}

func (x *GetAfterSaleRequestReq) Reset() { *x = GetAfterSaleRequestReq{} }

func (x *GetAfterSaleRequestReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetAfterSaleRequestReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetAfterSaleRequestReq) GetRequestNo() string {
	if x != nil {
		return x.RequestNo
	}
	return ""
}

type GetAfterSaleRequestResp struct {
	Request *AfterSaleRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (x *GetAfterSaleRequestResp) Reset() { *x = GetAfterSaleRequestResp{} }

func (x *GetAfterSaleRequestResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *GetAfterSaleRequestResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetAfterSaleRequestResp) GetRequest() *AfterSaleRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type AfterSaleService interface {
	CreateAfterSaleRequest(ctx context.Context, req *CreateAfterSaleRequestReq) (res *CreateAfterSaleRequestResp, err error)
	GetAfterSaleRequest(ctx context.Context, req *GetAfterSaleRequestReq) (res *GetAfterSaleRequestResp, err error)
}


