// Code generated by Kitex v0.15.4. DO NOT EDIT.

package userv1

import (
	"context"
	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/cloudwego/prutal"
)

type SignupReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (x *SignupReq) Reset() { *x = SignupReq{} }

func (x *SignupReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SignupReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SignupReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignupResp struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *SignupResp) Reset() { *x = SignupResp{} }

func (x *SignupResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SignupResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SignupResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginReq struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (x *LoginReq) Reset() { *x = LoginReq{} }

func (x *LoginReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *LoginResp) Reset() { *x = LoginResp{} }

func (x *LoginResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *LoginResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *LoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateProfileReq struct {
	UserId   int64   `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Username *string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Avatar   *string `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
}

func (x *UpdateProfileReq) Reset() { *x = UpdateProfileReq{} }

func (x *UpdateProfileReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UpdateProfileReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UpdateProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileReq) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateProfileReq) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

type ChangePasswordReq struct {
	UserId      int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	OldPassword string `protobuf:"bytes,2,opt,name=old_password" json:"old_password,omitempty"`
	NewPassword string `protobuf:"bytes,3,opt,name=new_password" json:"new_password,omitempty"`
}

func (x *ChangePasswordReq) Reset() { *x = ChangePasswordReq{} }

func (x *ChangePasswordReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChangePasswordReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChangePasswordReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangeEmailReq struct {
	UserId   int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"` // 楠岃瘉瀵嗙爜
	NewEmail string `protobuf:"bytes,3,opt,name=new_email" json:"new_email,omitempty"`
}

func (x *ChangeEmailReq) Reset() { *x = ChangeEmailReq{} }

func (x *ChangeEmailReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChangeEmailReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChangeEmailReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangeEmailReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ChangeEmailReq) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

type ChangePhoneReq struct {
	UserId   int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	OldPhone string `protobuf:"bytes,2,opt,name=old_phone" json:"old_phone,omitempty"`
	NewPhone string `protobuf:"bytes,3,opt,name=new_phone" json:"new_phone,omitempty"`
}

func (x *ChangePhoneReq) Reset() { *x = ChangePhoneReq{} }

func (x *ChangePhoneReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ChangePhoneReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ChangePhoneReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangePhoneReq) GetOldPhone() string {
	if x != nil {
		return x.OldPhone
	}
	return ""
}

func (x *ChangePhoneReq) GetNewPhone() string {
	if x != nil {
		return x.NewPhone
	}
	return ""
}

type DeleteUserReq struct {
	UserId   int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"` // 娉ㄩ攢璐﹀彿闇€瑕侀獙璇佸瘑鐮?
}

func (x *DeleteUserReq) Reset() { *x = DeleteUserReq{} }

func (x *DeleteUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DeleteUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DeleteUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type QueryUserReq struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *QueryUserReq) Reset() { *x = QueryUserReq{} }

func (x *QueryUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *QueryUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *QueryUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type QueryUserResp struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *QueryUserResp) Reset() { *x = QueryUserResp{} }

func (x *QueryUserResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *QueryUserResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *QueryUserResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	UserId   int64  `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Avatar   string `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserService interface {
	Signup(ctx context.Context, req *SignupReq) (res *SignupResp, err error)
	Login(ctx context.Context, req *LoginReq) (res *LoginResp, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileReq) (res *emptypb.Empty, err error)
	ChangePassword(ctx context.Context, req *ChangePasswordReq) (res *emptypb.Empty, err error)
	ChangeEmail(ctx context.Context, req *ChangeEmailReq) (res *emptypb.Empty, err error)
	ChangePhone(ctx context.Context, req *ChangePhoneReq) (res *emptypb.Empty, err error)
	Delete(ctx context.Context, req *DeleteUserReq) (res *emptypb.Empty, err error)
	Query(ctx context.Context, req *QueryUserReq) (res *QueryUserResp, err error)
}


