// Code generated by Kitex v0.16.1. DO NOT EDIT.

package searchservice

import (
	"context"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/search/v1"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SearchProducts(ctx context.Context, Req *v1.SearchProductsReq, callOptions ...callopt.Option) (r *v1.SearchProductsResp, err error)
	GetSearchAggregations(ctx context.Context, Req *v1.SearchProductsReq, callOptions ...callopt.Option) (r *v1.SearchAggregationsResp, err error)
	SearchMerchants(ctx context.Context, Req *v1.SearchMerchantsReq, callOptions ...callopt.Option) (r *v1.SearchMerchantsResp, err error)
	SearchSuggest(ctx context.Context, Req *v1.SearchSuggestReq, callOptions ...callopt.Option) (r *v1.SearchSuggestResp, err error)
	InitES(ctx context.Context, Req *v1.InitESReq, callOptions ...callopt.Option) (r *v1.InitESResp, err error)
	AISearchProducts(ctx context.Context, Req *v1.AISearchProductsReq, callOptions ...callopt.Option) (r *v1.AISearchProductsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSearchServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSearchServiceClient struct {
	*kClient
}

func (p *kSearchServiceClient) SearchProducts(ctx context.Context, Req *v1.SearchProductsReq, callOptions ...callopt.Option) (r *v1.SearchProductsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchProducts(ctx, Req)
}

func (p *kSearchServiceClient) GetSearchAggregations(ctx context.Context, Req *v1.SearchProductsReq, callOptions ...callopt.Option) (r *v1.SearchAggregationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSearchAggregations(ctx, Req)
}

func (p *kSearchServiceClient) SearchMerchants(ctx context.Context, Req *v1.SearchMerchantsReq, callOptions ...callopt.Option) (r *v1.SearchMerchantsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchMerchants(ctx, Req)
}

func (p *kSearchServiceClient) SearchSuggest(ctx context.Context, Req *v1.SearchSuggestReq, callOptions ...callopt.Option) (r *v1.SearchSuggestResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchSuggest(ctx, Req)
}

func (p *kSearchServiceClient) InitES(ctx context.Context, Req *v1.InitESReq, callOptions ...callopt.Option) (r *v1.InitESResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InitES(ctx, Req)
}

func (p *kSearchServiceClient) AISearchProducts(ctx context.Context, Req *v1.AISearchProductsReq, callOptions ...callopt.Option) (r *v1.AISearchProductsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AISearchProducts(ctx, Req)
}


