// Code generated by Kitex v0.16.1. DO NOT EDIT.

package searchservice

import (
	"context"
	"errors"
	searchv1 "github.com/XDWow/DouyinMall/backend/rpc_gen/search/v1"
	v1 "github.com/XDWow/DouyinMall/backend/rpc_gen/search/v1"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SearchProducts": kitex.NewMethodInfo(
		searchProductsHandler,
		newSearchProductsArgs,
		newSearchProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetSearchAggregations": kitex.NewMethodInfo(
		getSearchAggregationsHandler,
		newGetSearchAggregationsArgs,
		newGetSearchAggregationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchMerchants": kitex.NewMethodInfo(
		searchMerchantsHandler,
		newSearchMerchantsArgs,
		newSearchMerchantsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"SearchSuggest": kitex.NewMethodInfo(
		searchSuggestHandler,
		newSearchSuggestArgs,
		newSearchSuggestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"InitES": kitex.NewMethodInfo(
		initESHandler,
		newInitESArgs,
		newInitESResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AISearchProducts": kitex.NewMethodInfo(
		aISearchProductsHandler,
		newAISearchProductsArgs,
		newAISearchProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	searchServiceServiceInfo                = NewServiceInfo()
	searchServiceServiceInfoForClient       = NewServiceInfoForClient()
	searchServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return searchServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return searchServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return searchServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SearchService"
	handlerType := (*searchv1.SearchService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "search",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func searchProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.SearchProductsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(searchv1.SearchService).SearchProducts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchProductsArgs:
		success, err := handler.(searchv1.SearchService).SearchProducts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchProductsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchProductsArgs() interface{} {
	return &SearchProductsArgs{}
}

func newSearchProductsResult() interface{} {
	return &SearchProductsResult{}
}

type SearchProductsArgs struct {
	Req *v1.SearchProductsReq
}

func (p *SearchProductsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchProductsArgs) Unmarshal(in []byte) error {
	msg := new(v1.SearchProductsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchProductsArgs_Req_DEFAULT *v1.SearchProductsReq

func (p *SearchProductsArgs) GetReq() *v1.SearchProductsReq {
	if !p.IsSetReq() {
		return SearchProductsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchProductsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchProductsResult struct {
	Success *v1.SearchProductsResp
}

var SearchProductsResult_Success_DEFAULT *v1.SearchProductsResp

func (p *SearchProductsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchProductsResult) Unmarshal(in []byte) error {
	msg := new(v1.SearchProductsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchProductsResult) GetSuccess() *v1.SearchProductsResp {
	if !p.IsSetSuccess() {
		return SearchProductsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.SearchProductsResp)
}

func (p *SearchProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchProductsResult) GetResult() interface{} {
	return p.Success
}

func getSearchAggregationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.SearchProductsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(searchv1.SearchService).GetSearchAggregations(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetSearchAggregationsArgs:
		success, err := handler.(searchv1.SearchService).GetSearchAggregations(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetSearchAggregationsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetSearchAggregationsArgs() interface{} {
	return &GetSearchAggregationsArgs{}
}

func newGetSearchAggregationsResult() interface{} {
	return &GetSearchAggregationsResult{}
}

type GetSearchAggregationsArgs struct {
	Req *v1.SearchProductsReq
}

func (p *GetSearchAggregationsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetSearchAggregationsArgs) Unmarshal(in []byte) error {
	msg := new(v1.SearchProductsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetSearchAggregationsArgs_Req_DEFAULT *v1.SearchProductsReq

func (p *GetSearchAggregationsArgs) GetReq() *v1.SearchProductsReq {
	if !p.IsSetReq() {
		return GetSearchAggregationsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetSearchAggregationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetSearchAggregationsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetSearchAggregationsResult struct {
	Success *v1.SearchAggregationsResp
}

var GetSearchAggregationsResult_Success_DEFAULT *v1.SearchAggregationsResp

func (p *GetSearchAggregationsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetSearchAggregationsResult) Unmarshal(in []byte) error {
	msg := new(v1.SearchAggregationsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetSearchAggregationsResult) GetSuccess() *v1.SearchAggregationsResp {
	if !p.IsSetSuccess() {
		return GetSearchAggregationsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetSearchAggregationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.SearchAggregationsResp)
}

func (p *GetSearchAggregationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetSearchAggregationsResult) GetResult() interface{} {
	return p.Success
}

func searchMerchantsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.SearchMerchantsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(searchv1.SearchService).SearchMerchants(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchMerchantsArgs:
		success, err := handler.(searchv1.SearchService).SearchMerchants(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchMerchantsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchMerchantsArgs() interface{} {
	return &SearchMerchantsArgs{}
}

func newSearchMerchantsResult() interface{} {
	return &SearchMerchantsResult{}
}

type SearchMerchantsArgs struct {
	Req *v1.SearchMerchantsReq
}

func (p *SearchMerchantsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchMerchantsArgs) Unmarshal(in []byte) error {
	msg := new(v1.SearchMerchantsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchMerchantsArgs_Req_DEFAULT *v1.SearchMerchantsReq

func (p *SearchMerchantsArgs) GetReq() *v1.SearchMerchantsReq {
	if !p.IsSetReq() {
		return SearchMerchantsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchMerchantsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchMerchantsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchMerchantsResult struct {
	Success *v1.SearchMerchantsResp
}

var SearchMerchantsResult_Success_DEFAULT *v1.SearchMerchantsResp

func (p *SearchMerchantsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchMerchantsResult) Unmarshal(in []byte) error {
	msg := new(v1.SearchMerchantsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchMerchantsResult) GetSuccess() *v1.SearchMerchantsResp {
	if !p.IsSetSuccess() {
		return SearchMerchantsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchMerchantsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.SearchMerchantsResp)
}

func (p *SearchMerchantsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchMerchantsResult) GetResult() interface{} {
	return p.Success
}

func searchSuggestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.SearchSuggestReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(searchv1.SearchService).SearchSuggest(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchSuggestArgs:
		success, err := handler.(searchv1.SearchService).SearchSuggest(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchSuggestResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchSuggestArgs() interface{} {
	return &SearchSuggestArgs{}
}

func newSearchSuggestResult() interface{} {
	return &SearchSuggestResult{}
}

type SearchSuggestArgs struct {
	Req *v1.SearchSuggestReq
}

func (p *SearchSuggestArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchSuggestArgs) Unmarshal(in []byte) error {
	msg := new(v1.SearchSuggestReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchSuggestArgs_Req_DEFAULT *v1.SearchSuggestReq

func (p *SearchSuggestArgs) GetReq() *v1.SearchSuggestReq {
	if !p.IsSetReq() {
		return SearchSuggestArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchSuggestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchSuggestArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchSuggestResult struct {
	Success *v1.SearchSuggestResp
}

var SearchSuggestResult_Success_DEFAULT *v1.SearchSuggestResp

func (p *SearchSuggestResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchSuggestResult) Unmarshal(in []byte) error {
	msg := new(v1.SearchSuggestResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchSuggestResult) GetSuccess() *v1.SearchSuggestResp {
	if !p.IsSetSuccess() {
		return SearchSuggestResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchSuggestResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.SearchSuggestResp)
}

func (p *SearchSuggestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchSuggestResult) GetResult() interface{} {
	return p.Success
}

func initESHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.InitESReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(searchv1.SearchService).InitES(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *InitESArgs:
		success, err := handler.(searchv1.SearchService).InitES(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*InitESResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newInitESArgs() interface{} {
	return &InitESArgs{}
}

func newInitESResult() interface{} {
	return &InitESResult{}
}

type InitESArgs struct {
	Req *v1.InitESReq
}

func (p *InitESArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *InitESArgs) Unmarshal(in []byte) error {
	msg := new(v1.InitESReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var InitESArgs_Req_DEFAULT *v1.InitESReq

func (p *InitESArgs) GetReq() *v1.InitESReq {
	if !p.IsSetReq() {
		return InitESArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *InitESArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InitESArgs) GetFirstArgument() interface{} {
	return p.Req
}

type InitESResult struct {
	Success *v1.InitESResp
}

var InitESResult_Success_DEFAULT *v1.InitESResp

func (p *InitESResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *InitESResult) Unmarshal(in []byte) error {
	msg := new(v1.InitESResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *InitESResult) GetSuccess() *v1.InitESResp {
	if !p.IsSetSuccess() {
		return InitESResult_Success_DEFAULT
	}
	return p.Success
}

func (p *InitESResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.InitESResp)
}

func (p *InitESResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InitESResult) GetResult() interface{} {
	return p.Success
}

func aISearchProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.AISearchProductsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(searchv1.SearchService).AISearchProducts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AISearchProductsArgs:
		success, err := handler.(searchv1.SearchService).AISearchProducts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AISearchProductsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAISearchProductsArgs() interface{} {
	return &AISearchProductsArgs{}
}

func newAISearchProductsResult() interface{} {
	return &AISearchProductsResult{}
}

type AISearchProductsArgs struct {
	Req *v1.AISearchProductsReq
}

func (p *AISearchProductsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AISearchProductsArgs) Unmarshal(in []byte) error {
	msg := new(v1.AISearchProductsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AISearchProductsArgs_Req_DEFAULT *v1.AISearchProductsReq

func (p *AISearchProductsArgs) GetReq() *v1.AISearchProductsReq {
	if !p.IsSetReq() {
		return AISearchProductsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AISearchProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AISearchProductsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AISearchProductsResult struct {
	Success *v1.AISearchProductsResp
}

var AISearchProductsResult_Success_DEFAULT *v1.AISearchProductsResp

func (p *AISearchProductsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AISearchProductsResult) Unmarshal(in []byte) error {
	msg := new(v1.AISearchProductsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AISearchProductsResult) GetSuccess() *v1.AISearchProductsResp {
	if !p.IsSetSuccess() {
		return AISearchProductsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AISearchProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.AISearchProductsResp)
}

func (p *AISearchProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AISearchProductsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SearchProducts(ctx context.Context, Req *v1.SearchProductsReq) (r *v1.SearchProductsResp, err error) {
	var _args SearchProductsArgs
	_args.Req = Req
	var _result SearchProductsResult
	if err = p.c.Call(ctx, "SearchProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSearchAggregations(ctx context.Context, Req *v1.SearchProductsReq) (r *v1.SearchAggregationsResp, err error) {
	var _args GetSearchAggregationsArgs
	_args.Req = Req
	var _result GetSearchAggregationsResult
	if err = p.c.Call(ctx, "GetSearchAggregations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchMerchants(ctx context.Context, Req *v1.SearchMerchantsReq) (r *v1.SearchMerchantsResp, err error) {
	var _args SearchMerchantsArgs
	_args.Req = Req
	var _result SearchMerchantsResult
	if err = p.c.Call(ctx, "SearchMerchants", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchSuggest(ctx context.Context, Req *v1.SearchSuggestReq) (r *v1.SearchSuggestResp, err error) {
	var _args SearchSuggestArgs
	_args.Req = Req
	var _result SearchSuggestResult
	if err = p.c.Call(ctx, "SearchSuggest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InitES(ctx context.Context, Req *v1.InitESReq) (r *v1.InitESResp, err error) {
	var _args InitESArgs
	_args.Req = Req
	var _result InitESResult
	if err = p.c.Call(ctx, "InitES", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AISearchProducts(ctx context.Context, Req *v1.AISearchProductsReq) (r *v1.AISearchProductsResp, err error) {
	var _args AISearchProductsArgs
	_args.Req = Req
	var _result AISearchProductsResult
	if err = p.c.Call(ctx, "AISearchProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}


