// Code generated by Kitex v0.16.1. DO NOT EDIT.

package v1

import (
	"context"
	"strconv"

	"github.com/cloudwego/prutal"
)

// 浼樻儬鍒哥被鍨?type CouponType int32

const (
	CouponType_COUPON_TYPE_UNSPECIFIED CouponType = 0
	CouponType_COUPON_TYPE_AMOUNT      CouponType = 1 // 婊″噺鍒?	CouponType_COUPON_TYPE_PERCENT     CouponType = 2 // 鎶樻墸鍒?	CouponType_COUPON_TYPE_FIXED       CouponType = 3 // 绔嬪噺鍒革紝鏃犻棬妲?)

// Enum value maps for CouponType.
var CouponType_name = map[int32]string{
	0: "COUPON_TYPE_UNSPECIFIED",
	1: "COUPON_TYPE_AMOUNT",
	2: "COUPON_TYPE_PERCENT",
	3: "COUPON_TYPE_FIXED",
}

var CouponType_value = map[string]int32{
	"COUPON_TYPE_UNSPECIFIED": 0,
	"COUPON_TYPE_AMOUNT":      1,
	"COUPON_TYPE_PERCENT":     2,
	"COUPON_TYPE_FIXED":       3,
}

func (x CouponType) String() string {
	s, ok := CouponType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 浼樻儬鍒哥姸鎬?type UserCouponStatus int32

const (
	UserCouponStatus_USER_COUPON_STATUS_UNSPECIFIED UserCouponStatus = 0
	UserCouponStatus_USER_COUPON_STATUS_UNUSED      UserCouponStatus = 1 // 鏈娇鐢?	UserCouponStatus_USER_COUPON_STATUS_LOCKED      UserCouponStatus = 2 // 宸查攣瀹氾紙棰勬墸涓級锛屽疄渚嬮€氳繃鐘舵€侀鎵ｏ紝闃叉瓒呭崠
	UserCouponStatus_USER_COUPON_STATUS_USED        UserCouponStatus = 3 // 宸蹭娇鐢?	UserCouponStatus_USER_COUPON_STATUS_EXPIRED     UserCouponStatus = 4 // 宸茶繃鏈?)

// Enum value maps for UserCouponStatus.
var UserCouponStatus_name = map[int32]string{
	0: "USER_COUPON_STATUS_UNSPECIFIED",
	1: "USER_COUPON_STATUS_UNUSED",
	2: "USER_COUPON_STATUS_LOCKED",
	3: "USER_COUPON_STATUS_USED",
	4: "USER_COUPON_STATUS_EXPIRED",
}

var UserCouponStatus_value = map[string]int32{
	"USER_COUPON_STATUS_UNSPECIFIED": 0,
	"USER_COUPON_STATUS_UNUSED":      1,
	"USER_COUPON_STATUS_LOCKED":      2,
	"USER_COUPON_STATUS_USED":        3,
	"USER_COUPON_STATUS_EXPIRED":     4,
}

func (x UserCouponStatus) String() string {
	s, ok := UserCouponStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 浼樻儬鍒告ā鏉匡紙绠＄悊鍛樺垱寤虹殑鍒歌鍒欙級
type CouponTemplate struct {
	Id             int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name           string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`                          // 鍒稿悕绉?	Type           CouponType `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`                         // 鍒哥被鍨?	Threshold      int64      `protobuf:"varint,4,opt,name=threshold" json:"threshold,omitempty"`               // 浣跨敤闂ㄦ锛堝垎锛夛紝0琛ㄧず鏃犻棬妲?	DiscountValue  int64      `protobuf:"varint,5,opt,name=discount_value" json:"discount_value,omitempty"`     // 浼樻儬鍊硷細婊″噺/绔嬪噺鏄噾棰濓紙鍒嗭級锛屾姌鎵ｆ槸鐧惧垎姣旓紙80琛ㄧず8鎶橈級
	MaxDiscount    int64      `protobuf:"varint,6,opt,name=max_discount" json:"max_discount,omitempty"`         // 鎶樻墸鍒告渶澶т紭鎯犻噾棰濓紙鍒嗭級锛?琛ㄧず涓嶉檺
	ValidDays      int64      `protobuf:"varint,7,opt,name=valid_days" json:"valid_days,omitempty"`             // 棰嗗彇鍚庢湁鏁堝ぉ鏁帮紙0琛ㄧず浣跨敤鍥哄畾鏃堕棿锛?	ValidStartTime int64      `protobuf:"varint,8,opt,name=valid_start_time" json:"valid_start_time,omitempty"` // 鍥哄畾鐢熸晥寮€濮嬫椂闂达紙unix绉掞級
	ValidEndTime   int64      `protobuf:"varint,9,opt,name=valid_end_time" json:"valid_end_time,omitempty"`     // 鍥哄畾鐢熸晥缁撴潫鏃堕棿锛坲nix绉掞級
	TotalCount     int32      `protobuf:"varint,10,opt,name=total_count" json:"total_count,omitempty"`          // 鍙戣鎬婚噺锛?1琛ㄧず涓嶉檺锛?	IssuedCount    int32      `protobuf:"varint,11,opt,name=issued_count" json:"issued_count,omitempty"`        // 宸插彂鏀炬暟閲?	PerUserLimit   int32      `protobuf:"varint,12,opt,name=per_user_limit" json:"per_user_limit,omitempty"`    // 姣忎汉闄愰鏁伴噺
	ProductIds     []int64    `protobuf:"varint,13,rep,packed,name=product_ids" json:"product_ids,omitempty"`   // 閫傜敤鍟嗗搧ID锛堢┖琛ㄧず鍏ㄥ満閫氱敤锛?	CategoryIds    []int64    `protobuf:"varint,14,rep,packed,name=category_ids" json:"category_ids,omitempty"` // 閫傜敤鍒嗙被ID锛堢┖琛ㄧず鍏ㄥ満閫氱敤锛?	Enabled        bool       `protobuf:"varint,15,opt,name=enabled" json:"enabled,omitempty"`                  // 鏄惁鍚敤
	CreatedAt      int64      `protobuf:"varint,16,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt      int64      `protobuf:"varint,17,opt,name=updated_at" json:"updated_at,omitempty"`
}

func (x *CouponTemplate) Reset() { *x = CouponTemplate{} }

func (x *CouponTemplate) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CouponTemplate) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CouponTemplate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponTemplate) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNSPECIFIED
}

func (x *CouponTemplate) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CouponTemplate) GetDiscountValue() int64 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *CouponTemplate) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *CouponTemplate) GetValidDays() int64 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

func (x *CouponTemplate) GetValidStartTime() int64 {
	if x != nil {
		return x.ValidStartTime
	}
	return 0
}

func (x *CouponTemplate) GetValidEndTime() int64 {
	if x != nil {
		return x.ValidEndTime
	}
	return 0
}

func (x *CouponTemplate) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CouponTemplate) GetIssuedCount() int32 {
	if x != nil {
		return x.IssuedCount
	}
	return 0
}

func (x *CouponTemplate) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CouponTemplate) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *CouponTemplate) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *CouponTemplate) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CouponTemplate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CouponTemplate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 鐢ㄦ埛浼樻儬鍒革紙鐢ㄦ埛棰嗗彇鐨勫埜瀹炰緥锛?type UserCoupon struct {
	Id             int64            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"` // 鐢ㄦ埛鍒窱D锛堝敮涓€锛?	UserId         int64            `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	TemplateId     int64            `protobuf:"varint,3,opt,name=template_id" json:"template_id,omitempty"`
	Template       *CouponTemplate  `protobuf:"bytes,4,opt,name=template" json:"template,omitempty"` // 鍒告ā鏉胯鎯咃紙鍐椾綑锛屾柟渚垮睍绀猴級
	Status         UserCouponStatus `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	LockedOrderId  int64            `protobuf:"varint,6,opt,name=locked_order_id" json:"locked_order_id,omitempty"`   // 閿佸畾鐨勮鍗旾D锛堥鎵ｆ椂璁剧疆锛?	UsedOrderId    int64            `protobuf:"varint,7,opt,name=used_order_id" json:"used_order_id,omitempty"`       // 浣跨敤鐨勮鍗旾D锛堟牳閿€鏃惰缃級
	ValidStartTime int64            `protobuf:"varint,8,opt,name=valid_start_time" json:"valid_start_time,omitempty"` // 鐢熸晥寮€濮嬫椂闂?	ValidEndTime   int64            `protobuf:"varint,9,opt,name=valid_end_time" json:"valid_end_time,omitempty"`     // 鐢熸晥缁撴潫鏃堕棿
	CreatedAt      int64            `protobuf:"varint,10,opt,name=created_at" json:"created_at,omitempty"`
	UsedAt         int64            `protobuf:"varint,11,opt,name=used_at" json:"used_at,omitempty"`
}

func (x *UserCoupon) Reset() { *x = UserCoupon{} }

func (x *UserCoupon) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserCoupon) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserCoupon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCoupon) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCoupon) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *UserCoupon) GetTemplate() *CouponTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *UserCoupon) GetStatus() UserCouponStatus {
	if x != nil {
		return x.Status
	}
	return UserCouponStatus_USER_COUPON_STATUS_UNSPECIFIED
}

func (x *UserCoupon) GetLockedOrderId() int64 {
	if x != nil {
		return x.LockedOrderId
	}
	return 0
}

func (x *UserCoupon) GetUsedOrderId() int64 {
	if x != nil {
		return x.UsedOrderId
	}
	return 0
}

func (x *UserCoupon) GetValidStartTime() int64 {
	if x != nil {
		return x.ValidStartTime
	}
	return 0
}

func (x *UserCoupon) GetValidEndTime() int64 {
	if x != nil {
		return x.ValidEndTime
	}
	return 0
}

func (x *UserCoupon) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserCoupon) GetUsedAt() int64 {
	if x != nil {
		return x.UsedAt
	}
	return 0
}

// 璁㈠崟鍟嗗搧
type OrderItem struct {
	ProductId  int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	CategoryId int64 `protobuf:"varint,2,opt,name=category_id" json:"category_id,omitempty"`
	Price      int64 `protobuf:"varint,3,opt,name=price" json:"price,omitempty"` // 鍗曚环锛堝垎锛?	Quantity   int32 `protobuf:"varint,4,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *OrderItem) Reset() { *x = OrderItem{} }

func (x *OrderItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OrderItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *OrderItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 鏌ヨ鐢ㄦ埛浼樻儬鍒稿垪琛?type ListUserCouponsReq struct {
	UserId   int64            `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Status   UserCouponStatus `protobuf:"varint,2,opt,name=status" json:"status,omitempty"` // 绛涢€夌姸鎬侊紙0琛ㄧず鍏ㄩ儴锛?	Page     int32            `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize int32            `protobuf:"varint,4,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListUserCouponsReq) Reset() { *x = ListUserCouponsReq{} }

func (x *ListUserCouponsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListUserCouponsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListUserCouponsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserCouponsReq) GetStatus() UserCouponStatus {
	if x != nil {
		return x.Status
	}
	return UserCouponStatus_USER_COUPON_STATUS_UNSPECIFIED
}

func (x *ListUserCouponsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserCouponsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserCouponsResp struct {
	Coupons []*UserCoupon `protobuf:"bytes,1,rep,name=coupons" json:"coupons,omitempty"`
	Total   int32         `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListUserCouponsResp) Reset() { *x = ListUserCouponsResp{} }

func (x *ListUserCouponsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListUserCouponsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListUserCouponsResp) GetCoupons() []*UserCoupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *ListUserCouponsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 鏌ヨ璁㈠崟鍙敤浼樻儬鍒?type ListAvailableCouponsReq struct {
	UserId int64        `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Items  []*OrderItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"` // 璁㈠崟鍟嗗搧鍒楄〃
}

func (x *ListAvailableCouponsReq) Reset() { *x = ListAvailableCouponsReq{} }

func (x *ListAvailableCouponsReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListAvailableCouponsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListAvailableCouponsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAvailableCouponsReq) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListAvailableCouponsResp struct {
	Coupons []*UserCoupon `protobuf:"bytes,1,rep,name=coupons" json:"coupons,omitempty"` // 鍙敤鐨勫埜锛岀粰鐢ㄦ埛閫夋嫨锛岃繖閲屼笉鍋氳嚜鍔ㄨ绠楁渶浼樻儬绛栫暐浜嗗惂
}

func (x *ListAvailableCouponsResp) Reset() { *x = ListAvailableCouponsResp{} }

func (x *ListAvailableCouponsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListAvailableCouponsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListAvailableCouponsResp) GetCoupons() []*UserCoupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

// 鎵归噺棰勬墸浼樻儬鍒革紙浜嬪姟鍐呮壒閲忔洿鏂帮紝鍏ㄩ儴鎴愬姛鎴栧叏閮ㄥけ璐ワ級
// 鐘舵€佹満淇濊瘉骞傜瓑锛歎nused->Locked锛岄噸澶嶈皟鐢ㄦ鏌?status 鍜?order_id
type ReserveCouponReq struct {
	UserId        int64        `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	UserCouponIds []int64      `protobuf:"varint,2,rep,packed,name=user_coupon_ids" json:"user_coupon_ids,omitempty"` // 鐢ㄦ埛鍒窱D鍒楄〃锛堟壒閲忥級
	OrderId       int64        `protobuf:"varint,3,opt,name=order_id" json:"order_id,omitempty"`                      // 璁㈠崟ID
	Items         []*OrderItem `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`                             // 璁㈠崟鍟嗗搧锛堢敤浜庢牎楠岄€傜敤鎬э級
}

func (x *ReserveCouponReq) Reset() { *x = ReserveCouponReq{} }

func (x *ReserveCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReserveCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReserveCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveCouponReq) GetUserCouponIds() []int64 {
	if x != nil {
		return x.UserCouponIds
	}
	return nil
}

func (x *ReserveCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveCouponReq) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveCouponResp struct {
	Success  bool             `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`  // 鍏ㄩ儴鎴愬姛涓?true
	Message  string           `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`   // 姒傝淇℃伅
	Failures []*CouponFailure `protobuf:"bytes,3,rep,name=failures" json:"failures,omitempty"` // 澶辫触鏄庣粏锛堝叏閮ㄦ垚鍔熸椂涓虹┖锛?}

func (x *ReserveCouponResp) Reset() { *x = ReserveCouponResp{} }

func (x *ReserveCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReserveCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReserveCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveCouponResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReserveCouponResp) GetFailures() []*CouponFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

// 鍗曞紶鍒搁鎵ｅけ璐ョ殑鍘熷洜
type CouponFailure struct {
	UserCouponId int64  `protobuf:"varint,1,opt,name=user_coupon_id" json:"user_coupon_id,omitempty"`
	Reason       string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"` // 濡?"浼樻儬鍒稿凡杩囨湡"銆?涓嶆弧瓒充娇鐢ㄦ潯浠?
}

func (x *CouponFailure) Reset() { *x = CouponFailure{} }

func (x *CouponFailure) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CouponFailure) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CouponFailure) GetUserCouponId() int64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *CouponFailure) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 纭鏍搁攢锛堢姸鎬佹満淇濊瘉骞傜瓑锛歀ocked->Used锛?type CommitCouponReq struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *CommitCouponReq) Reset() { *x = CommitCouponReq{} }

func (x *CommitCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommitCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommitCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CommitCouponResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *CommitCouponResp) Reset() { *x = CommitCouponResp{} }

func (x *CommitCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommitCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommitCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 閲婃斁棰勬墸锛堢姸鎬佹満淇濊瘉骞傜瓑锛歀ocked->Unused锛?type ReleaseCouponReq struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *ReleaseCouponReq) Reset() { *x = ReleaseCouponReq{} }

func (x *ReleaseCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReleaseCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReleaseCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ReleaseCouponResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *ReleaseCouponResp) Reset() { *x = ReleaseCouponResp{} }

func (x *ReleaseCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReleaseCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReleaseCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 閫€杩樹紭鎯犲埜锛堢姸鎬佹満淇濊瘉骞傜瓑锛歎sed->Unused锛?type RefundCouponReq struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *RefundCouponReq) Reset() { *x = RefundCouponReq{} }

func (x *RefundCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefundCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefundCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type RefundCouponResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *RefundCouponResp) Reset() { *x = RefundCouponResp{} }

func (x *RefundCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefundCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefundCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 鍒涘缓浼樻儬鍒告ā鏉?type CreateCouponTemplateReq struct {
	Name           string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type           CouponType `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Threshold      int64      `protobuf:"varint,3,opt,name=threshold" json:"threshold,omitempty"`
	DiscountValue  int64      `protobuf:"varint,4,opt,name=discount_value" json:"discount_value,omitempty"`
	MaxDiscount    int64      `protobuf:"varint,5,opt,name=max_discount" json:"max_discount,omitempty"`
	ValidDays      int64      `protobuf:"varint,6,opt,name=valid_days" json:"valid_days,omitempty"`
	ValidStartTime int64      `protobuf:"varint,7,opt,name=valid_start_time" json:"valid_start_time,omitempty"`
	ValidEndTime   int64      `protobuf:"varint,8,opt,name=valid_end_time" json:"valid_end_time,omitempty"`
	TotalCount     int32      `protobuf:"varint,9,opt,name=total_count" json:"total_count,omitempty"`
	PerUserLimit   int32      `protobuf:"varint,10,opt,name=per_user_limit" json:"per_user_limit,omitempty"`
	ProductIds     []int64    `protobuf:"varint,11,rep,packed,name=product_ids" json:"product_ids,omitempty"`
	CategoryIds    []int64    `protobuf:"varint,12,rep,packed,name=category_ids" json:"category_ids,omitempty"`
}

func (x *CreateCouponTemplateReq) Reset() { *x = CreateCouponTemplateReq{} }

func (x *CreateCouponTemplateReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateCouponTemplateReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateCouponTemplateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCouponTemplateReq) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNSPECIFIED
}

func (x *CreateCouponTemplateReq) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetDiscountValue() int64 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidDays() int64 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidStartTime() int64 {
	if x != nil {
		return x.ValidStartTime
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidEndTime() int64 {
	if x != nil {
		return x.ValidEndTime
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *CreateCouponTemplateReq) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

type CreateCouponTemplateResp struct {
	TemplateId int64 `protobuf:"varint,1,opt,name=template_id" json:"template_id,omitempty"`
}

func (x *CreateCouponTemplateResp) Reset() { *x = CreateCouponTemplateResp{} }

func (x *CreateCouponTemplateResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateCouponTemplateResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateCouponTemplateResp) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

// 鍙戞斁浼樻儬鍒革紝杩欓噷涓嶆悶鏁伴噺锛屽疄鐜颁細绠€鍗曞緢澶氾紝閭ｈ竟鎵嶈兘鐢ㄧ姸鎬佹満锛屾悶鏁伴噺灏卞拰搴撳瓨涓€鏍蜂簡
// 鍙戞斁浼樻儬鍒镐粛鐒堕渶瑕乷peration_id锛岄伩鍏嶉噸璇曞鑷撮敊璇彂澶氬紶
type IssueCouponReq struct {
	OperationId string `protobuf:"bytes,1,opt,name=operation_id" json:"operation_id,omitempty"` // 骞傜瓑ID锛堝锛歝oupon:issue:user_123_template_456_20260204锛?	UserId      int64  `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	TemplateId  int64  `protobuf:"varint,3,opt,name=template_id" json:"template_id,omitempty"`
	Source      string `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"` // 鍙戞斁鏉ユ簮锛堝锛歯ew_user, activity_123锛?}

func (x *IssueCouponReq) Reset() { *x = IssueCouponReq{} }

func (x *IssueCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IssueCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IssueCouponReq) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *IssueCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IssueCouponReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *IssueCouponReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type IssueCouponResp struct {
	Success      bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`               // 鏄惁鎴愬姛
	UserCouponId int64  `protobuf:"varint,2,opt,name=user_coupon_id" json:"user_coupon_id,omitempty"` // 鍙戞斁鐨勭敤鎴峰埜ID
	Message      string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`                // 澶辫触鍘熷洜锛堝锛氬凡棰嗗彇杩囥€佸簱瀛樹笉瓒筹級
}

func (x *IssueCouponResp) Reset() { *x = IssueCouponResp{} }

func (x *IssueCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IssueCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IssueCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IssueCouponResp) GetUserCouponId() int64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *IssueCouponResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CouponService interface {
	ListUserCoupons(ctx context.Context, req *ListUserCouponsReq) (res *ListUserCouponsResp, err error)
	ListAvailableCoupons(ctx context.Context, req *ListAvailableCouponsReq) (res *ListAvailableCouponsResp, err error)
	ReserveCoupon(ctx context.Context, req *ReserveCouponReq) (res *ReserveCouponResp, err error)
	CommitCoupon(ctx context.Context, req *CommitCouponReq) (res *CommitCouponResp, err error)
	ReleaseCoupon(ctx context.Context, req *ReleaseCouponReq) (res *ReleaseCouponResp, err error)
	RefundCoupon(ctx context.Context, req *RefundCouponReq) (res *RefundCouponResp, err error)
	CreateCouponTemplate(ctx context.Context, req *CreateCouponTemplateReq) (res *CreateCouponTemplateResp, err error)
	IssueCoupon(ctx context.Context, req *IssueCouponReq) (res *IssueCouponResp, err error)
}


