// Code generated by Kitex v0.16.1. DO NOT EDIT.

package v1

import (
	"context"
	"strconv"

	"github.com/cloudwego/prutal"
)

// 优惠券类型
type CouponType int32

const (
	CouponType_COUPON_TYPE_UNSPECIFIED CouponType = 0
	CouponType_COUPON_TYPE_AMOUNT      CouponType = 1 // 满减券
	CouponType_COUPON_TYPE_PERCENT     CouponType = 2 // 折扣券
	CouponType_COUPON_TYPE_FIXED       CouponType = 3 // 立减券，无门槛
)

// Enum value maps for CouponType.
var CouponType_name = map[int32]string{
	0: "COUPON_TYPE_UNSPECIFIED",
	1: "COUPON_TYPE_AMOUNT",
	2: "COUPON_TYPE_PERCENT",
	3: "COUPON_TYPE_FIXED",
}

var CouponType_value = map[string]int32{
	"COUPON_TYPE_UNSPECIFIED": 0,
	"COUPON_TYPE_AMOUNT":      1,
	"COUPON_TYPE_PERCENT":     2,
	"COUPON_TYPE_FIXED":       3,
}

func (x CouponType) String() string {
	s, ok := CouponType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 优惠券状态
type UserCouponStatus int32

const (
	UserCouponStatus_USER_COUPON_STATUS_UNSPECIFIED UserCouponStatus = 0
	UserCouponStatus_USER_COUPON_STATUS_UNUSED      UserCouponStatus = 1 // 未使用
	UserCouponStatus_USER_COUPON_STATUS_LOCKED      UserCouponStatus = 2 // 已锁定（预扣中），实例通过状态预扣，防止超卖
	UserCouponStatus_USER_COUPON_STATUS_USED        UserCouponStatus = 3 // 已使用
	UserCouponStatus_USER_COUPON_STATUS_EXPIRED     UserCouponStatus = 4 // 已过期
)

// Enum value maps for UserCouponStatus.
var UserCouponStatus_name = map[int32]string{
	0: "USER_COUPON_STATUS_UNSPECIFIED",
	1: "USER_COUPON_STATUS_UNUSED",
	2: "USER_COUPON_STATUS_LOCKED",
	3: "USER_COUPON_STATUS_USED",
	4: "USER_COUPON_STATUS_EXPIRED",
}

var UserCouponStatus_value = map[string]int32{
	"USER_COUPON_STATUS_UNSPECIFIED": 0,
	"USER_COUPON_STATUS_UNUSED":      1,
	"USER_COUPON_STATUS_LOCKED":      2,
	"USER_COUPON_STATUS_USED":        3,
	"USER_COUPON_STATUS_EXPIRED":     4,
}

func (x UserCouponStatus) String() string {
	s, ok := UserCouponStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// 优惠券模板（管理员创建的券规则）
type CouponTemplate struct {
	Id             int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name           string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`                          // 券名称
	Type           CouponType `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`                         // 券类型
	Threshold      int64      `protobuf:"varint,4,opt,name=threshold" json:"threshold,omitempty"`               // 使用门槛（分），0表示无门槛
	DiscountValue  int64      `protobuf:"varint,5,opt,name=discount_value" json:"discount_value,omitempty"`     // 优惠值：满减/立减是金额（分），折扣是百分比（80表示8折）
	MaxDiscount    int64      `protobuf:"varint,6,opt,name=max_discount" json:"max_discount,omitempty"`         // 折扣券最大优惠金额（分），0表示不限
	ValidDays      int64      `protobuf:"varint,7,opt,name=valid_days" json:"valid_days,omitempty"`             // 领取后有效天数（0表示使用固定时间）
	ValidStartTime int64      `protobuf:"varint,8,opt,name=valid_start_time" json:"valid_start_time,omitempty"` // 固定生效开始时间（unix秒）
	ValidEndTime   int64      `protobuf:"varint,9,opt,name=valid_end_time" json:"valid_end_time,omitempty"`     // 固定生效结束时间（unix秒）
	TotalCount     int32      `protobuf:"varint,10,opt,name=total_count" json:"total_count,omitempty"`          // 发行总量（-1表示不限）
	IssuedCount    int32      `protobuf:"varint,11,opt,name=issued_count" json:"issued_count,omitempty"`        // 已发放数量
	PerUserLimit   int32      `protobuf:"varint,12,opt,name=per_user_limit" json:"per_user_limit,omitempty"`    // 每人限领数量
	ProductIds     []int64    `protobuf:"varint,13,rep,packed,name=product_ids" json:"product_ids,omitempty"`   // 适用商品ID（空表示全场通用）
	CategoryIds    []int64    `protobuf:"varint,14,rep,packed,name=category_ids" json:"category_ids,omitempty"` // 适用分类ID（空表示全场通用）
	Enabled        bool       `protobuf:"varint,15,opt,name=enabled" json:"enabled,omitempty"`                  // 是否启用
	CreatedAt      int64      `protobuf:"varint,16,opt,name=created_at" json:"created_at,omitempty"`
	UpdatedAt      int64      `protobuf:"varint,17,opt,name=updated_at" json:"updated_at,omitempty"`
}

func (x *CouponTemplate) Reset() { *x = CouponTemplate{} }

func (x *CouponTemplate) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CouponTemplate) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CouponTemplate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponTemplate) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNSPECIFIED
}

func (x *CouponTemplate) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CouponTemplate) GetDiscountValue() int64 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *CouponTemplate) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *CouponTemplate) GetValidDays() int64 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

func (x *CouponTemplate) GetValidStartTime() int64 {
	if x != nil {
		return x.ValidStartTime
	}
	return 0
}

func (x *CouponTemplate) GetValidEndTime() int64 {
	if x != nil {
		return x.ValidEndTime
	}
	return 0
}

func (x *CouponTemplate) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CouponTemplate) GetIssuedCount() int32 {
	if x != nil {
		return x.IssuedCount
	}
	return 0
}

func (x *CouponTemplate) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CouponTemplate) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *CouponTemplate) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *CouponTemplate) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CouponTemplate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CouponTemplate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 用户优惠券（用户领取的券实例）
type UserCoupon struct {
	Id             int64            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"` // 用户券ID（唯一）
	UserId         int64            `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	TemplateId     int64            `protobuf:"varint,3,opt,name=template_id" json:"template_id,omitempty"`
	Template       *CouponTemplate  `protobuf:"bytes,4,opt,name=template" json:"template,omitempty"` // 券模板详情（冗余，方便展示）
	Status         UserCouponStatus `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	LockedOrderId  int64            `protobuf:"varint,6,opt,name=locked_order_id" json:"locked_order_id,omitempty"`   // 锁定的订单ID（预扣时设置）
	UsedOrderId    int64            `protobuf:"varint,7,opt,name=used_order_id" json:"used_order_id,omitempty"`       // 使用的订单ID（核销时设置）
	ValidStartTime int64            `protobuf:"varint,8,opt,name=valid_start_time" json:"valid_start_time,omitempty"` // 生效开始时间
	ValidEndTime   int64            `protobuf:"varint,9,opt,name=valid_end_time" json:"valid_end_time,omitempty"`     // 生效结束时间
	CreatedAt      int64            `protobuf:"varint,10,opt,name=created_at" json:"created_at,omitempty"`
	UsedAt         int64            `protobuf:"varint,11,opt,name=used_at" json:"used_at,omitempty"`
}

func (x *UserCoupon) Reset() { *x = UserCoupon{} }

func (x *UserCoupon) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserCoupon) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserCoupon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCoupon) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCoupon) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *UserCoupon) GetTemplate() *CouponTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *UserCoupon) GetStatus() UserCouponStatus {
	if x != nil {
		return x.Status
	}
	return UserCouponStatus_USER_COUPON_STATUS_UNSPECIFIED
}

func (x *UserCoupon) GetLockedOrderId() int64 {
	if x != nil {
		return x.LockedOrderId
	}
	return 0
}

func (x *UserCoupon) GetUsedOrderId() int64 {
	if x != nil {
		return x.UsedOrderId
	}
	return 0
}

func (x *UserCoupon) GetValidStartTime() int64 {
	if x != nil {
		return x.ValidStartTime
	}
	return 0
}

func (x *UserCoupon) GetValidEndTime() int64 {
	if x != nil {
		return x.ValidEndTime
	}
	return 0
}

func (x *UserCoupon) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserCoupon) GetUsedAt() int64 {
	if x != nil {
		return x.UsedAt
	}
	return 0
}

// 订单商品
type OrderItem struct {
	ProductId  int64 `protobuf:"varint,1,opt,name=product_id" json:"product_id,omitempty"`
	CategoryId int64 `protobuf:"varint,2,opt,name=category_id" json:"category_id,omitempty"`
	Price      int64 `protobuf:"varint,3,opt,name=price" json:"price,omitempty"` // 单价（分）
	Quantity   int32 `protobuf:"varint,4,opt,name=quantity" json:"quantity,omitempty"`
}

func (x *OrderItem) Reset() { *x = OrderItem{} }

func (x *OrderItem) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OrderItem) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *OrderItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 查询用户优惠券列表
type ListUserCouponsReq struct {
	UserId   int64            `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Status   UserCouponStatus `protobuf:"varint,2,opt,name=status" json:"status,omitempty"` // 筛选状态（0表示全部）
	Page     int32            `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize int32            `protobuf:"varint,4,opt,name=page_size" json:"page_size,omitempty"`
}

func (x *ListUserCouponsReq) Reset() { *x = ListUserCouponsReq{} }

func (x *ListUserCouponsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListUserCouponsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListUserCouponsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserCouponsReq) GetStatus() UserCouponStatus {
	if x != nil {
		return x.Status
	}
	return UserCouponStatus_USER_COUPON_STATUS_UNSPECIFIED
}

func (x *ListUserCouponsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserCouponsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserCouponsResp struct {
	Coupons []*UserCoupon `protobuf:"bytes,1,rep,name=coupons" json:"coupons,omitempty"`
	Total   int32         `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

func (x *ListUserCouponsResp) Reset() { *x = ListUserCouponsResp{} }

func (x *ListUserCouponsResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListUserCouponsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListUserCouponsResp) GetCoupons() []*UserCoupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

func (x *ListUserCouponsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 查询订单可用优惠券
type ListAvailableCouponsReq struct {
	UserId int64        `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Items  []*OrderItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"` // 订单商品列表
}

func (x *ListAvailableCouponsReq) Reset() { *x = ListAvailableCouponsReq{} }

func (x *ListAvailableCouponsReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListAvailableCouponsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListAvailableCouponsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListAvailableCouponsReq) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListAvailableCouponsResp struct {
	Coupons []*UserCoupon `protobuf:"bytes,1,rep,name=coupons" json:"coupons,omitempty"` // 可用的券，给用户选择，这里不做自动计算最优惠策略了吧
}

func (x *ListAvailableCouponsResp) Reset() { *x = ListAvailableCouponsResp{} }

func (x *ListAvailableCouponsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListAvailableCouponsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListAvailableCouponsResp) GetCoupons() []*UserCoupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

// 批量预扣优惠券（事务内批量更新，全部成功或全部失败）
// 状态机保证幂等：Unused->Locked，重复调用检查 status 和 order_id
type ReserveCouponReq struct {
	UserId        int64        `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	UserCouponIds []int64      `protobuf:"varint,2,rep,packed,name=user_coupon_ids" json:"user_coupon_ids,omitempty"` // 用户券ID列表（批量）
	OrderId       int64        `protobuf:"varint,3,opt,name=order_id" json:"order_id,omitempty"`                      // 订单ID
	Items         []*OrderItem `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`                             // 订单商品（用于校验适用性）
}

func (x *ReserveCouponReq) Reset() { *x = ReserveCouponReq{} }

func (x *ReserveCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReserveCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReserveCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveCouponReq) GetUserCouponIds() []int64 {
	if x != nil {
		return x.UserCouponIds
	}
	return nil
}

func (x *ReserveCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReserveCouponReq) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveCouponResp struct {
	Success  bool             `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`  // 全部成功为 true
	Message  string           `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`   // 概要信息
	Failures []*CouponFailure `protobuf:"bytes,3,rep,name=failures" json:"failures,omitempty"` // 失败明细（全部成功时为空）
}

func (x *ReserveCouponResp) Reset() { *x = ReserveCouponResp{} }

func (x *ReserveCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReserveCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReserveCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveCouponResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReserveCouponResp) GetFailures() []*CouponFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

// 单张券预扣失败的原因
type CouponFailure struct {
	UserCouponId int64  `protobuf:"varint,1,opt,name=user_coupon_id" json:"user_coupon_id,omitempty"`
	Reason       string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"` // 如 "优惠券已过期"、"不满足使用条件"
}

func (x *CouponFailure) Reset() { *x = CouponFailure{} }

func (x *CouponFailure) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CouponFailure) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CouponFailure) GetUserCouponId() int64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *CouponFailure) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 确认核销（状态机保证幂等：Locked->Used）
type CommitCouponReq struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *CommitCouponReq) Reset() { *x = CommitCouponReq{} }

func (x *CommitCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommitCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommitCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CommitCouponResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *CommitCouponResp) Reset() { *x = CommitCouponResp{} }

func (x *CommitCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CommitCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CommitCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 释放预扣（状态机保证幂等：Locked->Unused）
type ReleaseCouponReq struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *ReleaseCouponReq) Reset() { *x = ReleaseCouponReq{} }

func (x *ReleaseCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReleaseCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReleaseCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ReleaseCouponResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *ReleaseCouponResp) Reset() { *x = ReleaseCouponResp{} }

func (x *ReleaseCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ReleaseCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ReleaseCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 退还优惠券（状态机保证幂等：Used->Unused）
type RefundCouponReq struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (x *RefundCouponReq) Reset() { *x = RefundCouponReq{} }

func (x *RefundCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefundCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefundCouponReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type RefundCouponResp struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (x *RefundCouponResp) Reset() { *x = RefundCouponResp{} }

func (x *RefundCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RefundCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RefundCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 创建优惠券模板
type CreateCouponTemplateReq struct {
	Name           string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type           CouponType `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Threshold      int64      `protobuf:"varint,3,opt,name=threshold" json:"threshold,omitempty"`
	DiscountValue  int64      `protobuf:"varint,4,opt,name=discount_value" json:"discount_value,omitempty"`
	MaxDiscount    int64      `protobuf:"varint,5,opt,name=max_discount" json:"max_discount,omitempty"`
	ValidDays      int64      `protobuf:"varint,6,opt,name=valid_days" json:"valid_days,omitempty"`
	ValidStartTime int64      `protobuf:"varint,7,opt,name=valid_start_time" json:"valid_start_time,omitempty"`
	ValidEndTime   int64      `protobuf:"varint,8,opt,name=valid_end_time" json:"valid_end_time,omitempty"`
	TotalCount     int32      `protobuf:"varint,9,opt,name=total_count" json:"total_count,omitempty"`
	PerUserLimit   int32      `protobuf:"varint,10,opt,name=per_user_limit" json:"per_user_limit,omitempty"`
	ProductIds     []int64    `protobuf:"varint,11,rep,packed,name=product_ids" json:"product_ids,omitempty"`
	CategoryIds    []int64    `protobuf:"varint,12,rep,packed,name=category_ids" json:"category_ids,omitempty"`
}

func (x *CreateCouponTemplateReq) Reset() { *x = CreateCouponTemplateReq{} }

func (x *CreateCouponTemplateReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateCouponTemplateReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateCouponTemplateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCouponTemplateReq) GetType() CouponType {
	if x != nil {
		return x.Type
	}
	return CouponType_COUPON_TYPE_UNSPECIFIED
}

func (x *CreateCouponTemplateReq) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetDiscountValue() int64 {
	if x != nil {
		return x.DiscountValue
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetMaxDiscount() int64 {
	if x != nil {
		return x.MaxDiscount
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidDays() int64 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidStartTime() int64 {
	if x != nil {
		return x.ValidStartTime
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetValidEndTime() int64 {
	if x != nil {
		return x.ValidEndTime
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CreateCouponTemplateReq) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *CreateCouponTemplateReq) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

type CreateCouponTemplateResp struct {
	TemplateId int64 `protobuf:"varint,1,opt,name=template_id" json:"template_id,omitempty"`
}

func (x *CreateCouponTemplateResp) Reset() { *x = CreateCouponTemplateResp{} }

func (x *CreateCouponTemplateResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateCouponTemplateResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateCouponTemplateResp) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

// 发放优惠券，这里不搞数量，实现会简单很多，那边才能用状态机，搞数量就和库存一样了
// 发放优惠券仍然需要operation_id，避免重试导致错误发多张
type IssueCouponReq struct {
	OperationId string `protobuf:"bytes,1,opt,name=operation_id" json:"operation_id,omitempty"` // 幂等ID（如：coupon:issue:user_123_template_456_20260204）
	UserId      int64  `protobuf:"varint,2,opt,name=user_id" json:"user_id,omitempty"`
	TemplateId  int64  `protobuf:"varint,3,opt,name=template_id" json:"template_id,omitempty"`
	Source      string `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"` // 发放来源（如：new_user, activity_123）
}

func (x *IssueCouponReq) Reset() { *x = IssueCouponReq{} }

func (x *IssueCouponReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IssueCouponReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IssueCouponReq) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *IssueCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IssueCouponReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *IssueCouponReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type IssueCouponResp struct {
	Success      bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`               // 是否成功
	UserCouponId int64  `protobuf:"varint,2,opt,name=user_coupon_id" json:"user_coupon_id,omitempty"` // 发放的用户券ID
	Message      string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`                // 失败原因（如：已领取过、库存不足）
}

func (x *IssueCouponResp) Reset() { *x = IssueCouponResp{} }

func (x *IssueCouponResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *IssueCouponResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *IssueCouponResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IssueCouponResp) GetUserCouponId() int64 {
	if x != nil {
		return x.UserCouponId
	}
	return 0
}

func (x *IssueCouponResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CouponService interface {
	ListUserCoupons(ctx context.Context, req *ListUserCouponsReq) (res *ListUserCouponsResp, err error)
	ListAvailableCoupons(ctx context.Context, req *ListAvailableCouponsReq) (res *ListAvailableCouponsResp, err error)
	ReserveCoupon(ctx context.Context, req *ReserveCouponReq) (res *ReserveCouponResp, err error)
	CommitCoupon(ctx context.Context, req *CommitCouponReq) (res *CommitCouponResp, err error)
	ReleaseCoupon(ctx context.Context, req *ReleaseCouponReq) (res *ReleaseCouponResp, err error)
	RefundCoupon(ctx context.Context, req *RefundCouponReq) (res *RefundCouponResp, err error)
	CreateCouponTemplate(ctx context.Context, req *CreateCouponTemplateReq) (res *CreateCouponTemplateResp, err error)
	IssueCoupon(ctx context.Context, req *IssueCouponReq) (res *IssueCouponResp, err error)
}
